### ISSUE TITLE
"strange object" in ordinary play

### ISSUE THREAD

**Issue by g-branden-robinson** [NetHack/NetHack#1001]
I'm playing

```
Unix NetHack Version 3.7.0-80 Work-in-progress - last build Mar 19 2023 21:40:36
(fa0ae08f942b94298af70382ff47b5ecefc73aab,branch:NetHack-3.7).
```

I'm seeing a "strange object" in Izchak's lighting shop, both on the normal map and in the farlook pop-up for "showing all objects".  This was stable across a save and reload. 

![Screenshot from 2023-03-22 06-52-59](https://user-images.githubusercontent.com/91402745/226898672-f704aa07-0f85-4e48-9271-2b94d4f798e8.png)
![Screenshot from 2023-03-22 06-53-38](https://user-images.githubusercontent.com/91402745/226898776-e376a84f-e16c-4b5b-92c4-ac3988381376.png)

The item might be out of visual range to discern color...?

**Comment by entrez** [comment]
It's not a mimic in disguise? What happens if you go pick it up?

**Comment by pat-rankin** [comment]
In case the previous comment wasn't entirely clear, 'strange object' is one of the forms that mimics can conceal themselves as and it is normal for such to appear on the map from time to time, especially in shops where concealed mimics are common.

As to /why/ that's one of their potential shapes, I don't know....

**Comment by paxed** [comment]
> As to /why/ that's one of their potential shapes, I don't know....

Even though the tile is a chest with red eyes peeking out, I think the rationale is it's mimicking an object, but doesn't get the shape correct, so is something completely strange.

**Comment by g-branden-robinson** [comment]
Ah, okay.  In all my years (20+) of playing NetHack I never managed to notice a mimic giving itself away in this manner.  (The increasing usability of the farlook feature, and a game where I _still_ haven't found a towel or blindfold, may be what brought it to my attention in this game.)  In past versions I probably would have just assumed the mimic was giving itself away by being an item of armor in a potion shop or similar.

I had thought "strange object" was a special value in an enum or similar to alert (source) hackers to the fact that something had been assigned a value of zero when it shouldn't have been.  Looking at the sources now, the symbol names `ILLOBJ_CLASS` and `GENERIC_ILLOBJ` suggest something "illegal".  But to be fair I think `impossible()` or even `panic()` are used for this sort of run-time validation.

Feel free to close!
