### ISSUE TITLE
Anti-magic field can leave hero with more energy than maximum

### ISSUE THREAD

**Issue by vultur-cadens** [NetHack/NetHack#1003]
A minor bug with little practical effect, but it looks wrong.

Anti-magic field can drain 1 more point of `u.uenmax` than `u.uen`, leaving a hero that had full energy with more energy than maximum energy (by 1 point, possibly more if this happens more than once in a row).

I believe this happens if `drain` is an odd number (for example, 11), and then `halfd` rolls the maximum value of half of that odd number, rounded up (for example, 6). `u.uenmax` and `drain` will both be decremented by `halfd`, making `drain` 5 in the example.  Then `drain`  is subtracted from `u.uen`, which is still at the previous maximum value, leaving `u.uen` greater than `u.uenmax`.

https://github.com/NetHack/NetHack/blob/a3d8557ea63d8b10b01cce8f0a9e087adf53e80e/src/trap.c#L2118-L2119
https://github.com/NetHack/NetHack/blob/a3d8557ea63d8b10b01cce8f0a9e087adf53e80e/src/trap.c#L2151-L2155

**Comment by pat-rankin** [comment]
'drain -= halfd' should actually be 'drain = halfd'.  Fix pending.

**Comment by pat-rankin** [comment]
Upon further review, the 'drain = halfd' fix changes semantics in an unintended way.  New fix pending...
