### ISSUE TITLE
Duplicate altar output

### ISSUE THREAD

**Issue by Umbire** [NetHack/NetHack#1014]
Version for clarity: Unix NetHack Version 3.7.0-82 Work-in-progress - last build Apr 17 2023 03:07:26 (e853d47aa369caa3f400cfc56ad4c4ae4a18b75a,branch:master), played via hardfought.org.

When dropping items onto an altar, the feedback is near-duplicated, with one providing the normal output and the second describing its beatitude, but otherwise being the same:
![image](https://user-images.githubusercontent.com/56782189/234837606-83ab9421-e4ec-41e0-85aa-1fc54c56e74d.png)

The screenshot above is focused on message history, with the relevant output in order as follows:

- A studded leather armor lands on the altar.
- An uncursed studded leather armor lands on the altar.
- Your movements are only slowed slightly by your load.
- A small shield lands on the altar.
- An uncursed small shield lands on the altar.

**EDIT:** A much clearer screenshot that displays relevant output: 
![image](https://user-images.githubusercontent.com/56782189/234841684-47658adb-0a5a-4463-bd28-833511191a23.png)

I've seen a couple of other players on IRC, joes and oh6, mention this bug as well.

**Comment by paxed** [comment]
This has already been fixed in commit 80a8eaf7e6a375a1ee538f0eef516e7278ae434d

**Comment by Umbire** [comment]
Good to know, thank you.
