### ISSUE TITLE
Win32: Names containing spaces don't save and restore properly

### ISSUE THREAD

**Issue by chasonr** [NetHack/NetHack#1015]
To test this issue:
* Run the Win32 version of NetHack, either text or graphical
* Create a character whose name includes a space
* Save the game
* Restore the game

The game cannot be restored, because the save file is named with the space included ("Lews Therin") but the restore looks for it with the space escaped ("Lews%20Therin"). Renaming the file doesn't help.

**Comment by nhmall** [comment]
Are you reporting this against the development 3.7 work-in-progress or the 3.6.7 release?

**Comment by chasonr** [comment]
I observe this bug in 3.7.

**Comment by nhmall** [comment]
Has commit a687e75e9b8a9262567955ab7bc2454aa231f2f7 resolved the issue?

**Comment by chasonr** [comment]
It seems to be resolved.
