### ISSUE TITLE
You can get trapped in the Gnome King's Wine Cellar treasure chamber

### ISSUE THREAD

**Issue by AndrioCelos** [NetHack/NetHack#1025]
This was reported on [Reddit](https://www.reddit.com/r/nethack/comments/13ets79/got_stuck_in_gnomish_mines_vault_what_can_i_do/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button).

The player ended up in the treasure chamber without having dug in (possibly thorough the very rare event of teleporting or falling into that spot), with no means of escape.

Perhaps it is worth adding a scroll of teleportation to the chamber, like closets have.

**Comment by copperwater** [comment]
Alternatively, put a pick in the chamber, so the 99% of players who reach the chamber via normal means don't get a free teleport scroll and knowledge of which scroll is teleportation, and instead get a tool that they've likely found one of anyway.

Or probably better: use `des.teleport_region()` to confine players arriving via falling or levelport to a certain area of the map. This could be either the entire level minus the treasure chamber, or just the starting room.
