### ISSUE TITLE
curses + Enhanced1 appears to load in plain ASCII

### ISSUE THREAD

**Issue by ostrosablin** [NetHack/NetHack#1026]
I've first reproduced this on Hardfought, but seems to be a general problem with curses windowport.

I have an UTF-8 capable KDE Konsole terminal (but can reproduce in PuTTY, too, so doesn't seem to be terminal-related).

All screenshots were taken with same config with only difference being windowtype.

With Enhanced1 + windowtype:tty, game launches correctly:

![1](https://github.com/NetHack/NetHack/assets/5955408/fbd2720b-74fe-4c8b-9c03-b4d74e810ec5)

With Enhanced1 + windowtype:curses, symset appears to be a plain ASCII symset:

![2](https://github.com/NetHack/NetHack/assets/5955408/12e65c88-8a98-448c-beee-0ecd4c49e40c)

However, if in-game options are opened, game claims that active symset is Enhanced1:

![3](https://github.com/NetHack/NetHack/assets/5955408/6f91e017-6823-4e8f-b03c-b6d5a132e8ef)

Even more interesting, if I actually pick Enhanced1 through in-game options by hitting "i":

![4](https://github.com/NetHack/NetHack/assets/5955408/c062639a-64ba-450f-bd87-617738458382)

Game would fix itself up and from this point - curses will display the map properly, with all new UTF-8 characters in-place:

![5](https://github.com/NetHack/NetHack/assets/5955408/0cff5fb5-a64a-492b-a84f-619e1f82a952)

This workaround is not persistent, however. Saving and re-loading game would result in curses windowport displaying in plain ASCII again (so I guess, during initialization, some non-persistent flag is not being set, however picking symset from menu forces it to apply).

**Comment by chasonr** [comment]
I observed this bug while testing for pull request #1028.
The function symset_is_compatible in src/symbols.c allows Unicode symbol sets only if the window port sets both WC2_U_UTF8STR and WC2_U_24BITCOLOR. The Curses port sets only WC2_U_UTF8STR; it honors the character selection but not the configured color.

**Comment by ostrosablin** [comment]
Yeah, that's it. But it seems like a non-trivial problem to resolve.

In any case, there's an inconsistency (picking symset through menu apparently bypasses symset_is_compatible check), which is bad. But fixing just that will completely lock-out from using UTF-8 in curses.

On one hand, relaxing symset_is_compatible check to ignore WC2_U_24BITCOLOR seems to be a cheap and viable workaround. After all, Enhanced1 is quite playable under curses even if it doesn't honor configured character colors and is a major quality-of-life improvement over IBMGraphics, DECGraphics and other older symsets.

It seems that ncurses 6.1 added a support for 24-bit color extension (direct RGB mode), but since it's a ncurses-specific extension, it would make curses windowport non-portable across curses implementations. So adding a proper support for WC2_U_24BITCOLOR in curses windowport would be tricky.

**Comment by nhmall** [comment]
@ostrosablin wrote:
> I've first reproduced this on Hardfought, but seems to be a general problem with curses windowport

 The function symset_is_compatible() itself looks to be called only from Windows right now, but I'll look into a similar underlying issue involving the WC2 bits for the other platforms.

**Comment by ostrosablin** [comment]
I think I've found it.

https://github.com/NetHack/NetHack/blob/2abe156516cc5f1045f1cf32e2723f9ec9e88f56/win/curses/cursinit.c#L749-L753

These four lines were, apparently, meant to define default fallback symsets for curses (in case symset option wasn't _explicitly_ defined).

However, the condition seems to be broken (.explicitly flag not being properly set?), so it must be always evaluating to TRUE during windowport init. Commenting out these lines fixes the problem and NetHack starts with appropriate symset, as defined in config (but probably would break if config doesn't have an explicitly specified symset).

Condition in windowport code seems to be correct and setting .explicitly flag seems to be handled only in files.c:read_sym_file, but I don't understand, why would it be FALSE (unless symset file opening or parsing failed).

**Comment by FredrIQ** [comment]
IIRC this is my code (the windowport code, not the options handling in the engine itself); it was added as part of the 3.6.x port of the curses windowport. The explicitly flag is meant to be set if the user has specified the option either in the options menu or in their rc file. If their rc file doesn't specify a symset at all, then the "explicitly" flag is meant to not be set. Is it this part that isn't working properly?

**Comment by ostrosablin** [comment]
Yes, then I've understood the code correctly, however, rc file certainly requests the symset explicitly:

`OPTIONS=symset:Enhanced1`

But since default symset is used when game is started/loaded, this could only mean that explicitly flag is actually unset. However, if symset is manually chosen via options menu, then it would apply (which obviously bypasses the check in cursinit.c, since windowport is already up and running). Must be some weird quirk in handling of UTF-8 symsets.

Since tty windowport doesn't check explicitly flag like curses do, it would also explain why there's no similar issue under tty.

**Comment by duwling** [comment]
Additionally, if the enhanced symset is choosen via options menu, it does not read <code>options=glyph</code>.

**Comment by pat-rankin** [comment]
I'm chiming in a bit late here.  The discovery that the curses_init_options() code of

|  if (!gs.symset[PRIMARYSET].explicitly)  load_symset("curses", PRIMARYSET); 
|  if (!gs.symset[ROGUESET].explicitly)  load_symset("default", ROGUESET); 

is the source of the problem didn't quite go far enough.  Even though the primary symbol set ends up not being rendered properly, it is setting the rogue symbol set here that triggers the bug.  (It isn't curses specific.)

Loading any symbol set calls clear_symsetentry() for the set being loaded but that routine calls free_all_glyphmap_u() which affects both sets if they have UTF8 handling specified and data for it cached.

I'm pretty sure that someone else had already reported this (with less detail, so this didn't register as the same issue when I first saw it), but I don't remember who or where.
