### ISSUE TITLE
Cross compiling is (still) tricky

### ISSUE THREAD

**Issue by aapo** [NetHack/NetHack#1041]
README is missing many architecture which can run NetHack.

I cross compiled nethack 3.7 (`git-97edec62b5218aaeb15e8994a7000e1d51c58b56`) for Linux-MIPS. I realised my old non-smart LG television (https://www.lg.com/au/tvs-soundbars/lg-22LD320H-commercial-tv) runs Linux kernel (`2.6.26 #170 PREEMPT Wed Feb 9 15:37:33 KST 2011 mips GNU/Linux`) and shell access can be obtained with serial console. With crosstool-ng (`gcc-4.3.2`) I compiled ncurses (`6.4-20230527`) and then NetHack. Now I can play NetHack over serial cable with Putty.

![mips_nethack](https://github.com/NetHack/NetHack/assets/132666/870db5cd-465a-4733-a8a5-121deb1235b4)

Cross compiling process has been smoothened but still needs some clarifications, I think. As mips-linux was easy target (no need for any patches) I found it hard to understand how I should use makedefs on host. Here is my whole script which shows my struggling as `make` is constantly overwriting host-binaries (makedefs and dlb) with cross-binaries: 

    #This will be the path in television
    sudo mkdir -p /mnt/usb1/Drive1/
    sudo chown -R user:user /mnt/usb1/Drive1/

    git clone https://github.com/NetHack/NetHack NetHack
    cd NetHack
    cd sys/unix/
    sh setup.sh hints/linux.370 
    cd ../..
    make fetch-lua
    make
    mkdir x86
    cp util/makedefs x86
    cp util/dlb x86
    make clean

    cd sys/unix/
        sed -i -e 's;^GDBPATH=/usr/bin/gdb;\#GDBPATH=/usr/bin/gdb;' sysconf
        sed -i -e 's;PANICTRACE_GDB=1;PANICTRACE_GDB=0;' sysconf

        echo PREFIX=/mnt/usb1/Drive1/ >> hints/linux.370
        echo 'CFLAGS+= -I/home/user/mips/include/ -I/home/user/mips/include/ncursesw' >> hints/linux.370
        echo 'LINK+= -L/home/user/mips/lib' >> hints/linux.370
        sh setup.sh hints/linux.370
    cd ../..

    export PATH=/home/user/x-tools/mipsel-unknown-linux-gnu/bin:$PATH

    CC=mipsel-unknown-linux-gnu-gcc make
    cp x86/makedefs util
    CC=mipsel-unknown-linux-gnu-gcc make
    cp x86/dlb util
    CC=mipsel-unknown-linux-gnu-gcc make

    CC=mipsel-unknown-linux-gnu-gcc make install

And starting the game:

    TERM=xterm-256color LD_LIBRARY_PATH=/mnt/usb1/Drive1/ncurses /mnt/usb1/Drive1/games/nethack

**Comment by nhmall** [comment]
You indicate that you are using the hints files ending in .370. Those are designed to help make cross-compiling go smoothly and keep things separated. The key with those is to insert the needed additional "recipe" steps into sys/unix/hints/include/cross-pre.370 and sys/unix/hints/include/cross-post.370.

This gist in the comment that follows this one contains a small patch for those two hints include files for carrying out a mips cross-compile:

Obtain the mips cross-compiler itself:
```
sudo apt-get update
sudo apt -y install gcc-mipsel-linux.gnu g++-mipsel-linux.gnu
```

See revised comment that follows this one.

**Comment by nhmall** [comment]
I put an updated patch into this new gist:
https://gist.github.com/nhmall/a494dc56dd98a534a0e6418b5328587b

That updated patch for NetHack-3.7 can be applied to update the cross-pre.370 and cross-post.370 hints include files to add support for a mips cross-compile. The updated patch can be saved as mips2.diff and applied to your NetHack source tree with:
`patch -p1 -l -i mips2.diff`

As in the previous comment, I obtained a mips cross-compiler for ubuntu as follows,
```
sudo apt-get update
sudo apt -y install gcc-mipsel-linux.gnu g++-mipsel-linux.gnu
```
Since the ncurses library needs to be built from scratch for the target mips platform, autoconf is required if you don't already have it installed:
```
sudo apt-get install autoconf
```

After the application of the updated patch, the MIPS cross-compile should now consist of the following three steps:
```
sh sys/unix/setup.sh sys/unix/hints/linux.370
make CROSS_TO_MIPS=1 fetch-ncurses
make CROSS_TO_MIPS=1 all
```
