### ISSUE TITLE
Monster's name starting with non-ascii character is messed if row starts with it

### ISSUE THREAD

**Issue by aapo** [NetHack/NetHack#1042]
git-97edec62b5218aaeb15e8994a7000e1d51c58b56 on Ubuntu using ncurse (libncursesw.so.6.3).

Steps to reproduce:
*name pet so that first (or only) character is non-ascii: example Ä or emoji.
Most of the time the name is correctly shown.
If new row starts with pet's name then character is not printed correctly.

![working_emoji1](https://github.com/NetHack/NetHack/assets/132666/d8cadea5-57d1-453e-bf85-1c0bb5edad0d)
![working_skandi](https://github.com/NetHack/NetHack/assets/132666/23641871-c20b-45c1-b603-9f05e4e212b9)

![broken_emoji](https://github.com/NetHack/NetHack/assets/132666/c1b007e5-1196-4b43-99eb-535fd68c1ced)
![broken_skandi](https://github.com/NetHack/NetHack/assets/132666/95f53b72-bdc3-4dd0-9010-c3a3d3f3c64e)

Happens with monster also
![broken_skandi2](https://github.com/NetHack/NetHack/assets/132666/da2a1548-cbd2-4606-9c96-f326a746b6fc)

Item name seems to work when in middle of the sentence.
![working_emoji2](https://github.com/NetHack/NetHack/assets/132666/7fc8c9a3-39a1-4242-be15-55de7e615f44)

**Comment by nhmall** [comment]
What NetHack windowtype option setting are you reporting this for: tty or curses?
[edit] I can see your screenshots now and it looks like tty.
