### ISSUE TITLE
Monster reading scroll can leak scroll identities based on trycall prompt's absence

### ISSUE THREAD

**Issue by copperwater** [NetHack/NetHack#1045]
Reporting this on behalf of Muad. A monster out-of-sight read a scroll labeled THARR and they were prompted to call it. Then another monster read ABRA KA DABRA and they were not prompted to call it. By looking at muse.c, one can see that the only `MUSE_SCR_*` block that is capable of calling `trycall()` is create monster, so it's possible to deduce that THARR is create monster and ABRA KA DABRA is teleportation.

In general, it's useful information to the player that a particular scroll type will be read by monsters, so if the hero hears a monster reading a scroll and its type doesn't become fully identified in the process, they should always be given the trycall prompt.

**Comment by pat-rankin** [comment]
Fix checked in with typo for issue number, #1046; commit 7e4be52a6cc51c22831fc00543c12ce0081be4e0
