### ISSUE TITLE
Infinite fast-travel loop

### ISSUE THREAD

**Issue by pellsson** [NetHack/NetHack#105]
So I was trying to fast travel _ to the stairs < in the room at the bottom.

Can't recall what the trap diagonally above me was, but I am assuming hole trap. I had dug an alternate entrance to the > (on which I am stood in the picture) as indicated by the pile of rocks below the trap. When fast travelling, the guy would run diagonally down (n), then back up again (y). He would continue to do so until interrupted, oftentimes by hunger.

I am still in the game and can give further information when I (hopefully) return with the amulet.

EDIT: NAO 3.6.1

                           --------
                          #^......|
                       ####*.@(...|
                      ##   |*.....|
                      #    |0(.....#######
                      ##   |.0....|      #
                      #    --+-.---     0##########
                     ##                    #     -.---
         -------     #                     #    |...(|
         |......+#  ##                     ##   .^...|
         |......|# ##                       #   |....|
         |.......# ######                   ####.....|
         |......|##     #    # ---+-            ------
         |......-##############.<..|
         --------       ###### |..(|
                             ##+...|
                               |...+
                               -----

**Comment by AndrioCelos** [comment]
As a workaround for these loops, could it be worth remembering where the character just stepped from, and interrupting the command if it tries to move back to that space?

**Comment by davidssmith** [comment]
Why does the program logic have the player go in a direction that can't possibly reach the destination? Is it too costly to run a quick internal search?

**Comment by nhmall** [comment]
Fixed in 3.7 work-in-progress

e57c631ef91baf30726126945015cb7090d8c19d 
7523623d9504b9f2fc35c14960c844b5fe59ae36 
60bf399f91cac34e8ebf127889b38475441a5d52
1d78d3c3f27d986e24b925a709a6c6d8afc1a2e0
c763e26aa72c0a00bdcc690e7f5daa16bc51c3d3 
476e47b2cd3f0cb71ebdb3bbd5c70e069f673c2b 
6977aef436bc338c82e28f66364f6dcad499bdfa
e260c9ded5d2349421e8ee159a3fec98054ca267
ec4fafcf53c9aabb6bb973aed9b637cef3caa554
