### ISSUE TITLE
Dipping a bag into unidentified water describes the liquid as water 

### ISSUE THREAD

**Issue by loggersviii** [NetHack/NetHack#1061]
When dipping a bag into a non-cursed unidentified potion of water, you are given the message "some water gets into your <bag>!" However, you're then immediately prompted for identification of the liquid... which has already been revealed to be water, somehow. A simple thing but weird nonetheless.

**Comment by copperwater** [comment]
This would be a good opportunity to make water (which is always the only clear potion in the game) known by default. It's a minor interface annoyance for players who are well aware what a clear potion is to get prompted to type-name it the first time every game they interact with it.
