### ISSUE TITLE
enhanced symset on windows console

### ISSUE THREAD

**Issue by duwling** [NetHack/NetHack#1066]
NetHack crashes without a message before it could clear screen when selecting the Enhanced symset, on Windows 11.

**Comment by chasonr** [comment]
I have tried to replicate this bug, and could not.

What did you use to build NetHack? Visual Studio, or MinGW? And what version?
Did you set any options at compile time?
How is your .nethackrc set up? Curses or TTY? Do you get this bug when setting Enhanced1 at startup, or when choosing it afterwards?

**Comment by duwling** [comment]
62eacb11c482b18917b60b32b08634d9d23794ba built with [w64devkit](https://www.mingw-w64.org/downloads/#w64devkit)-1.19.0 (gcc-13.1 _mingw_-11)
I had a few glyph options, but chrashes also without.
No matter if set-in-config or set-in-game.
Only _plain tty_ interface crashes, PDCurses displays utf8 symbols.

**Comment by chasonr** [comment]
52dcd10 looks like it was meant to fix this issue. You might try building the current version. The EDITLEVEL has changed, so this will invalidate any bones or save files.

**Comment by duwling** [comment]
Yeah, that's it.
Sadly the font looks terrible compared to what i am used to, installed that only for testing.
