### ISSUE TITLE
Windows 3.6.2 beta versions:

### ISSUE THREAD

**Issue by Roetschreck** [NetHack/NetHack#107]
Windows 3.6.2 beta-01, console-port: Performance is good, but the status-line (only ST:xx Dx:xx Co:xx In:xx Wi:xx Ch:xx) disapears randomly (?) for some reason. In that case it can only be updated by redrawing the screen manually. I use Windows 10 (not the legacy console), but i guess this happens on any Windows-Console. Often this will happen when using ">" (down) an "<" (up).

**Comment by Roetschreck** [comment]
after further testing i think this will ONLY appear when going down and/or up (">" / "<")….. but not always...

**Comment by Roetschreck** [comment]
… seems to be fixed !

**Comment by nhmall** [comment]
fixed in 0b32735ff85a5d1d166b9635e563db62fe459509

**Comment by nhmall** [comment]
There's a new beta02 for Windows available with this fix and others included at https://www.nethack.org/
https://www.nethack.org/download/3.6.2/nethack-362-BETA02-win-x86.zip
Built from 878823ad8aa7b76e8ec8052378b2856e41cad68c ,branch:NetHack-3.6.2-beta01

**Comment by Roetschreck** [comment]
Thanks – i started testing.

Gesendet von Mail für Windows 10

Von: nhmall
Gesendet: Mittwoch, 5. September 2018 13:56
An: NetHack/NetHack
Cc: Roetschreck; Author
Betreff: Re: [NetHack/NetHack] Windows 3.6.2 beta-01: status-line disapearsrandomly (#107)

There's a new beta for Windows available with this fix and others included at https://www.nethack.org/
https://www.nethack.org/download/3.6.2/nethack-362-BETA02-win-x86.zip

**Comment by Roetschreck** [comment]
BETA02 works fine to me!

**Comment by Roetschreck** [comment]
Nethack**W**.exe from Windows Beta2 (Nethack Homepage) crashes after character-selection. I can´t play it (tty-version works fine). System: Windows 10

**Comment by nhmall** [comment]
Roetschreck, please provide more information.
- Is there an error message or pop-up?
- Full contents of your defaults.nh file, if one is being used.
- command line options used to start the game, if any.
- player selections chosen.
- is there a paniclog file left in the directory or any other new file?
Anything that might help reproduce your issue with an aim towards fixing it.

**Comment by Roetschreck** [comment]
- it´s the "standard-defaults.nh" right out of the .zip
- no command-line options choosen
- it chrashes for any player-selections, even when you choose "random"

**Comment by Roetschreck** [comment]
The game crashes a few seconds after the character-selection.

**Comment by nhmall** [comment]
I was able to reproduce this in nethack-362-BETA02-win-x86.zip
Windows NetHack Version 3.6.2-0 Beta - last build Mon Sep  3 09:35:39 2018.
(x86,878823ad8aa7b76e8ec8052378b2856e41cad68c,branch:NetHack-3.6.2-beta01)

That was actually fixed in 4be2467cc9a972958efbbfff37ecaf1c9fcee966 so we just need to get a new nethackw.exe windows beta up there.

**Comment by Roetschreck** [comment]
Crash is fixed in Windows-Beta3.
