### ISSUE TITLE
Lua source needs to point to https address, not http

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#1074]
~ make fetch-lua
( mkdir -p lib && cd lib && \
  curl -R -O http://www.lua.org/ftp/lua-5.4.6.tar.gz && \
  tar zxf lua-5.4.6.tar.gz && \
  rm -f lua-5.4.6.tar.gz )
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
make: *** [Makefile:1712: fetch-Lua] Error 56

If you change http to https, the link works and the tar.gz file will download.

**Comment by nhmall** [comment]
I'm not able to reproduce this. http and https both work.
Does 
`curl --verbose -R -O http://www.lua.org/ftp/lua-5.4.6.tar.gz`
provide any further insights on why you are encountering this from your system?

Here's what I see:
```
curl --verbose -R -O http://www.lua.org/ftp/lua-5.4.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 88.99.213.221:80...
* Connected to www.lua.org (88.99.213.221) port 80 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0> GET /ftp/lua-5.4.6.tar.gz HTTP/1.1
> Host: www.lua.org
> User-Agent: curl/8.0.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Wed, 05 Jul 2023 15:57:50 GMT
< Content-Type: application/gzip
< Content-Length: 363329
< Connection: keep-alive
< Last-Modified: Tue, 02 May 2023 20:12:04 GMT
<
{ [12377 bytes data]
100  354k  100  354k    0     0   452k      0 --:--:-- --:--:-- --:--:--  452k
* Connection #0 to host www.lua.org left intact
```

Please also note that the curl command matches that suggested by lua.org:
https://www.lua.org/download.html

**Comment by k21971** [comment]
I discovered the issue - the firewall I am behind does not allow access to unsecured addresses (http) unless an exception is made for a particular address. I can make an exception for lua.org no problem.

I understand what's presented on the download page from lua, but other people trying to compile 3.7 will run into this issue. More and more, firewall rules will default to disallowing access over http. If https is available, I'd recommend using it.
