### ISSUE TITLE
Can't wish for 'a small mimic corpse' or 'a large mimic corpse'.

### ISSUE THREAD

**Issue by AndrioCelos** [NetHack/NetHack#108]
```
For what do you wish? a small mimic corpse
Nothing fitting that description exists in the game.
For what do you wish? a corpse of a small mimic
h - a small mimic corpse.
```
'`a giant mimic corpse`' works, though. The same quirk occurs when wishing for a tin. Presumably the wish parser is interpreting 'small' as a modifier for globs instead of as part of a monster species name.
```
Unix NetHack Version 3.6.1 - last build Mon May  7 00:45:44 2018.
```

**Comment by Xaleth** [comment]
https://github.com/NetHack/NetHack/commit/3c979cb0a5748538e02e63fe42eaa670b68e5195
