### ISSUE TITLE
build system: same file name

### ISSUE THREAD

**Issue by duwling** [NetHack/NetHack#1084]
PDCurses already has a file named color.c so I named mine colors.c

Perhaps the Makefiles can be altered to allow nethack have the same file name as some lib.

**Comment by nhmall** [comment]
What platform and Makefile are you using?

There shouldn’t be an issue with source file names in different folders being the same but an issue could arise if the object files resulting from compilation of those source files are being placed in the same destination folder.

**Comment by duwling** [comment]
That happend with on microsoft, using w64devkit (mingw)

**Comment by duwling** [comment]
who cares

**Comment by duwling** [comment]
Windows mingw.. sorry, my fault. Now it works, I had forgotten (in Makefile.nmake)
<pre>
# sys/windows dependencies

$(OTTY)color.o: $(WSHR)\color.c $(WINDHDR) $(HACK_H)
</pre>
