### ISSUE TITLE
Building with FMOD currently produces no sound

### ISSUE THREAD

**Issue by MrEveryDay98** [NetHack/NetHack#1095]
Currently the FMOD sound system doesn't provide any sound playback, it worked during previous test builds but with the current implementation it does not work (but it does build).

**Comment by MrEveryDay98** [comment]
The issue may be with `sound_procs` or `sound_init_nhsound`, because I have `printf`'s set up to say SOMETHING in the output window in any case, and then nothing is shown

```c
result = FMOD_System_Init(systemvar, 32, FMOD_INIT_NORMAL, 0);
if (result != FMOD_OK) {
    printf("FMOD ERROR! %d\n", result);
    exit(-1);
} else {
    printf("No FMOD error occurred.\n");
}
```

**Comment by nhmall** [comment]
In the game, what does the soundlib entry in the mO  menu show?

How are you building NetHack (nmake, visual studio IDE, mingw)?
If it is with nmake or mingw, could we please take a look at the Makefile you are using?

Do you have a sample of your SOUNDDIR and SOUND entries in your config file?

**Comment by MrEveryDay98** [comment]
If the mO menu is supposed to be this, here it is:
![image](https://github.com/NetHack/NetHack/assets/98854338/7293569a-2deb-48e2-8d85-ee263ba74153)


Here are my sound entries in my config (works when I play 3.6.6 which uses the same config):
```
SOUNDDIR=C:\Users\tridu\NetHack\sounds
OPTIONS=soundlib:fmod

#MUSIC, prefix .wav files with 'music_' to play on loop
SOUND=MESG "to NetHack"                				"music_df.wav"   100

#SOUND EFFECTS
SOUND=MESG "This door is locked."                   "lock.wav"       100
SOUND=MESG "The door resists!"                      "door1.wav"      100
SOUND=MESG "The door opens."                        "door2.wav"      100
SOUND=MESG "You hear a door open."                  "door2.wav"      50
SOUND=MESG "The door closes."                       "door3.wav"      100
SOUND=MESG "it crashes open"                      "crack.wav"      100
SOUND=MESG "The door crashes open"                 "crack.wav"      100
SOUND=MESG "The door splinters!"                  "crack.wav"      100
SOUND=MESG "door  shatters"                      "crack.wav"      100
SOUND=MESG "WHAMMM!!!"                              "whammm.wav"     100
```

**Comment by MrEveryDay98** [comment]
I am building with Visual Studio

**Comment by nhmall** [comment]
You showed the ‘O’ menu, which does not show the soundlib entry. 

You need to prefix with ‘m’ to get the full listing. 

‘m’ followed immediately by ‘O’

**Comment by MrEveryDay98** [comment]
`soundlib` is set to `[nosound]`

**Comment by MrEveryDay98** [comment]
DLL is loaded properly
`08:15:53:481	'NetHackW.exe' (Win32): Loaded 'C:\Windows\System32\fmod.dll'. `

No panics/errors saying there is an issue with the soundlib

**Comment by nhmall** [comment]
Some changes will be required in the visual studio projects to include the fmod pieces. Only the nmake Makefiles have been modified at this point.

I (or someone) may be able to take a look at that later this weekend.

**Comment by MrEveryDay98** [comment]
Speaking of that, the MakeFile has `fmod_vc.dll` when it should be `fmod.dll`

**Comment by nhmall** [comment]
> Speaking of that, the MakeFile has `fmod_vc.dll` when it should be `fmod.dll`

That's in the pipeline.

**Comment by MrEveryDay98** [comment]
@nhmall thanks for the commit, she builds and she has sound! :)

**Comment by MrEveryDay98** [comment]
https://github.com/NetHack/NetHack/assets/98854338/e6bdb7eb-6fd5-4de6-81a7-d9005f4dd113
