### ISSUE TITLE
[3.7.0-89 hdf] strange output from /O

### ISSUE THREAD

**Issue by jeremyhetzler** [NetHack/NetHack#1098]
/O outputs strange strings like "\G01490DCA" where the object symbol should be.

Unix NetHack Version 3.7.0-89 Work-in-progress - last build Sep  7 2023 10:55:44
(8494bff02b67719303c47e298deaa89034127798,branch:master).

![hdf](https://github.com/NetHack/NetHack/assets/4957082/330b394b-b4b2-4f3d-ace8-61b188579ab3)

**Comment by nhmall** [comment]
@jeremyhetzler Does the following change correct it?

```
diff --git a/win/curses/cursmain.c b/win/curses/cursmain.c
index 6c9aee69e..19a52d3f4 100644
--- a/win/curses/cursmain.c
+++ b/win/curses/cursmain.c
@@ -587,9 +587,15 @@ curses_putmixed(winid window, int attr, const char *str)
     if (window == WIN_MESSAGE) {
         str = mixed_to_glyphinfo(str, &mesg_gi);
         mesg_mixed = 1;
+        /* now send it to the normal putstr */
+        curses_putstr(window, attr, str);
+    } else {
+       char buf[BUFSZ];
+
+       decode_mixed(buf, str);
+        /* now send it to the normal putstr */
+        curses_putstr(window, attr, buf);
     }
-    /* now send it to the normal putstr */
-    curses_putstr(window, attr, str);
     if (window == WIN_MESSAGE)
         mesg_mixed = 0;
 }
```

**Comment by nhmall** [comment]
A fix is in the pipeline.

**Comment by jeremyhetzler** [comment]
Thanks!

Sorry that I can't confirm on my end; I am playing on the hardfought
service rather than my own binary.

Thanks,
Jeremy

**Comment by k21971** [comment]
This update is live on the Hardfought servers.
