### ISSUE TITLE
Build looks for directory that doesn't exist

### ISSUE THREAD

**Issue by MrEveryDay98** [NetHack/NetHack#1104]
_Using Visual Studio 2022_

When building with PDcurses, it looks for the directory `\submodules\pdcurses\wingui\` which does not exist (but it does in `\submodules\pdcursesmod\`), either this is an issue with the actual submodule or with the build process.

**Comment by nhmall** [comment]
I'm unable to reproduce this issue with the current sources.
pdcursesmod is required for the wingui support (https://github.com/NetHack/NetHack/pull/1028)
How are you carrying out the build?

**Comment by MrEveryDay98** [comment]
Built by following the guide `sys/windows/Install.windows`
I made sure to do 
```
    git submodule init
    git submodule update --remote
```
This started happening when I did a fetch to update my local repo
![image](https://github.com/NetHack/NetHack/assets/98854338/9d17f1c2-a596-4839-af91-d6bd579e4675)
