### ISSUE TITLE
Build is creating a tile-less version of NetHackW

### ISSUE THREAD

**Issue by MrEveryDay98** [NetHack/NetHack#1105]
Build by default now creates a tile-less and featureless version of NetHackW that lacks all the normal options menus. If this is intentional and if the build process requires further options to be set to enable the tiled version of NetHackW, I will close the ticket.

Preprocessor Definitions:
`TILES;_WINDOWS;DLB;MSWIN_GRAPHICS;SAFEPROCS;NOTTYGRAPHICS;SND_LIB_WINDSOUND;USER_SOUNDS;HAS_STDINT_H;PDC_WIDE;%(PreprocessorDefinitions)`

![image](https://github.com/NetHack/NetHack/assets/98854338/6a188b95-8173-45ce-a8f8-9c66a6066672)

**Comment by nhmall** [comment]
I couldn't reproduce this issue.

If I had to guess, from the limited information provided, it looks to me like your %USERPROFILE%\\nethack\\.nethackrc might be selecting the curses interface. Do you perhaps have something similar to the following in there?
```
OPTIONS=windowtype:curses
OPTIONS=symset:curses
```

A recent change, is that the graphical version now has curses support (contributed by @chasonr ), and an even more recent change includes that curses support in the visual studio project build.

What does Alt-v in the game show you for **Supported windowing systems:**?
This is what I see:
```
Supported windowing systems:
"curses" (terminal-based graphics) and "mswin" (Windows GUI), with a
default of "mswin".
```

**Comment by nhmall** [comment]
No response from OP. Closing #1105.
