### ISSUE TITLE
Emit "ready for input" control character to facilitate bots

### ISSUE THREAD

**Issue by sartak** [NetHack/NetHack#1111]
Writing a bot to play NetHack certainly involves a lot of essential complexity ([my](https://github.com/TAEB/TAEB) [bots](https://github.com/TAEB/TAEB-AI-Magus) have made it to the Castle a few times, there's the [NetHack Learning Environment](https://github.com/facebookresearch/nle) initiative, etc). But botting NetHack unfortunately also involves a lot of incidental complexity. Just knowing when NetHack is done emitting output and is ready for the next command is a surprisingly hard problem that involves subtle heuristics, flakey telnet sidechannels, and esoteric job control patterns that trigger latent kernel bugs. And the consequence of getting it wrong even just for one single turn would cause the bot to entirely misread the UI, perhaps spelling the end for that particular adventure, or worse disrupt some deep learning model weights. Or at the very least, befuddling the poor human debugging that game session. There's lots more background on this problem in a blog post titled [Synchronizing with NetHack](https://taeb.github.io/2009/06/12/synchronizing-with-nethack.html), it's mentioned as a blocker in [the first ascending bot's docs](https://github.com/krajj7/BotHack#milestones-reached), and is generally a large, early nuisance for anyone interested in this pursuit.

What if, instead, NetHack just told us when it's our turn? Immediately before calling `getc` or similar to read user input, NetHack could emit an escape sequence to signal that it is done emitting output and is now awaiting input. Synchronization would then become a trivial matter of responding to NetHack's requests for input, kinda like a single-threaded HTTP server. Using an escape sequence (instead of, say, a Unix signal) offers a few virtues for free: it works for both local and network play, it would be saved in ttyrecs, it works with broadcasted streams (IRC Plays NetHack?), and generalizes to other programmatic interactions with the game like [Interhack](https://nethackwiki.com/wiki/Interhack).

I propose using the existing ENQUIRY (`^E`, `0x05`) transmission control character for this, since it is thematically related, and as best I can tell, ignored by terminal emulators. Or perhaps creating a new private escape sequence (as has been done for [bracketed paste](https://en.wikipedia.org/wiki/Bracketed-paste#Description_of_bracketed-paste), [mode 2027 for grapheme clusters](https://mitchellh.com/writing/grapheme-clusters-in-terminals), [cursor shaping](https://vim.fandom.com/wiki/Configuring_the_cursor), etc). I'm not overly fussed about the mechanics, only the outcome.

If preferred for back-compat, I'm fine with this being a user-configurable option. Perhaps as a general multi-option `bot` config (a la `disclose`) to reduce other incidental complexity in the UI… (3.4.3's inconsistent `Things that are here` panels drove me mad). Compile-time opt-in is a little less appealing since then it's less likely to be available for network play.

I'd be happy to put together a patch if there are no objections to this feature.

**Comment by paxed** [comment]
See TTY_TILES_ESCCODES in include/config.h

**Comment by sartak** [comment]
Amazing. `ESC [ 1 ; 3 z` is exactly what I'm looking for! Thanks paxed :)
