### ISSUE TITLE
"The aklys gets stuck in a web!  The aklys returns to your hand!"

### ISSUE THREAD

**Issue by elunna** [NetHack/NetHack#1152]
I found this in Hack'EM after importing the items getting stuck in webs change, but I was also able to reproduce it in 3.7.

Generate a web trap, wield an aklys, and throw it into the web. The aklys shows the message for getting stuck, but still returns to the player's hand.

My fix is here: [2b83c4d34](https://github.com/elunna/hackem/commit/2b83c4d34dba3d258f02bffa3f7e1bb85a69f50e)

**Comment by nhmall** [comment]
A fix is in the pipeline, thanks.
