### ISSUE TITLE
Initializing the struct console_t

### ISSUE THREAD

**Issue by Meklon2007** [NetHack/NetHack#1169]
Hello, it looks like there is an error when initializing the struct console_t structure (in last version NH on the github).
in consoletty.c when not defined VIRTUAL_TERMINAL_SEQUENCES fields are not initialized correctly.
Examples of obvious field mismatch are shown in the picture below:
![struct](https://github.com/NetHack/NetHack/assets/12417354/16e397ac-d533-445e-8b3b-0e5e0d4fa69a)

There is also minor warning with const:
in sndprocs.h:
struct sound_procs {.....
void (*sound_play_usersound)(**char** *filename, int32_t volume, int32_t idx);
.....}
in fmod.c:
static void fmod_play_usersound(**const char** *, int32_t, int32_t);

**Comment by nhmall** [comment]
A fix is in the pipeline.
