### ISSUE TITLE
Force-fighting webs with artifacts

### ISSUE THREAD

**Issue by Umbire** [NetHack/NetHack#1201]
Now that cutting down webs has been implemented, it feels like Sting's mechanical flavor should be adapted to make it a reliable web-cutter for force-fighting - similarly, Fire Brand (and whatever other fiery artifacts should happen to appear in the future) should also be able to instantly remove a web this way.

**Comment by copperwater** [comment]
Isn't this already the case? 

https://github.com/NetHack/NetHack/blob/NetHack-3.7/src/hack.c#L1918-L1922

**Comment by Umbire** [comment]
It was for Sting, as I was told after opening the issue, but not Fire Brand.
