### ISSUE TITLE
The syntax of the command is incorrect

### ISSUE THREAD

**Issue by shootmeinthehead** [NetHack/NetHack#1206]
In the original Makefile.mingw32 on line 1131 i get error for wrong syntax when i try to compile it. I havent edited the file so idk what is happening
![image](https://github.com/NetHack/NetHack/assets/111381039/6082832b-23fb-42a1-bc4e-48a69adc175c)
Im newbie in gcc and batches. But i know quite well asmbly and other things.

**Comment by nhmall** [comment]
The Makefile.mingw32 is set up for GNU make using a shell that is provided by the mingw32-x64 distribution, such as that provided by [MSYS2](https://www.msys2.org/).  If I understand the image above, it may be complaining about `mkdir -p`.

If you aren't using such a shell, you'll have to either:

1.  replace all the parts of the Makefile that rely on those shell commands with alternative commands that work in your environment to accomplish the same thing.
or
2. figure out a way to have  a shell available that matches the syntax already in the Makefile.

If there's an appropriate shell available somewhere in your path, you might be able to place something similar to this at the top of the Makefile, although I haven't tried that.
`
SHELL = /bin/bash
`
Reference:
[Choosing the Shell](https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html)

**Comment by nhmall** [comment]
Some other thoughts: 
you could try going into `bash` before you start the process, if it is available in your path.
or
if the `@mkdir -p $@` is the only issue, you could try changing those to `-mkdir $@`
to see if that gets you past that particular issue.

**Comment by shootmeinthehead** [comment]
Its the same i tried all of these and its the same error.

**Comment by shootmeinthehead** [comment]
What if i just remove it anyway its gonna be cleared right?

**Comment by shootmeinthehead** [comment]
Ok wait when i did this it worked
![image](https://github.com/NetHack/NetHack/assets/111381039/8c590252-57c3-4d8d-89ff-5ed3bfa4140c)
When i renamed it to "o" it got alright i guess it cant create a folder in a folder at once. mkdir $@ is = mkdir o/nethack. and now it works but is it supposed to create 2 separate folders o and nethack or is it supposed to make folder o and inside it folder nethack
But now its saying there isnt type names like lua_State, lua_Intiger, lua_getglobal, nhl_pcall_handle and others
![image](https://github.com/NetHack/NetHack/assets/111381039/dfbe826e-fc6c-4ead-a26b-d3040af16015)
