### ISSUE TITLE
Player can cast spells while in a form with no arms

### ISSUE THREAD

**Issue by loggersviii** [NetHack/NetHack#1210]
When the player has a cursed two-handed weapon welded to their hands, they cannot cast spells. The reason given by the game for this is “Your arms are not free to cast!”. This would imply that you need arms to cast spells. However, if you polymorph into, say, a garter snake, you will be able to violently remove your enemies from this mortal coil using magic just fine despite your lack of the appropriate extremities. While this is really funny, it’s probably incorrect :( 

(Also, how do golden nagas cast spells?)

**Comment by nhmall** [comment]
> When the player has a cursed two-handed weapon welded to their hands, they cannot cast spells. The reason given by the game for this is “Your arms are not free to cast!”. This would imply that you need arms to cast spells.

The implication is actually that humanoids, and other limbed creatures, have an innate dependence on their limbs for propulsion and other gestures/movements.

**Comment by loggersviii** [comment]
> The implication is actually that humanoids, and other limbed creatures, have an innate dependence on their limbs for propulsion and other gestures/movements.

This explanation is so silly and roundabout that I’m kind of impressed. No one, when seeing the message “your arms are not free to cast!”, has thought ‘ah yes of course, it is because of humans’ unconscious dependency on their limbs that they must wave their arms around when casting magic spells, even though such a maneuver is not actually necessary’. 

In what world does this make more sense than magic just needing hand signs to cast?

**Comment by nhmall** [comment]
@loggersviii wrote:
> a maneuver is not actually necessary

That wasn't stated anywhere.

What I was trying to say, is that humanoids use their arms and hands for somatic gestures because that's how humanoids do things. Humanoids also use limbs (legs and feet) for locomotion. 

A garter snake (your example) does not.  If some sort of somatic gesture is meant to accompany a spell, it's conceivable that those can be done in other ways, for limbless creatures, as well.

Edit: _its -> it's_ correction

**Comment by loggersviii** [comment]
That’s fair. I still think it’s weird but it’s basically headcanon vs headcanon so I’ll close this.
