### ISSUE TITLE
Curses Colors?

### ISSUE THREAD

**Issue by JPRuehmann** [NetHack/NetHack#1221]
Anyone knows a Way to make Curses Colors working (windowcolors)?
Thanks.

I am using Kubuntu 18.04 LTE (32Bit)
Updated Curses from theyr Github repository.

**Comment by paxed** [comment]
As the Guidebook says: "Windows GUI only."

**Comment by paxed** [comment]
Although it wouldn't be too hard to make it work...
![1709894951](https://github.com/NetHack/NetHack/assets/13092/e359147f-a14d-402c-9df2-9ae592b3019f)

**Comment by JPRuehmann** [comment]
since the Problem seems to be the Library, since the Problem goes for all Apps that are using curses in Linux.
But there seems to be no way to get in Contact with the developpers.

**Comment by paxed** [comment]
This has been implemented
