### ISSUE TITLE
Extra space in priest quest message

### ISSUE THREAD

**Issue by sobjornstad** [NetHack/NetHack#124]
One of the Arch Priest's encouragement messages:

    Acquire and wear the Mitre of Holiness if you can.  It will aid you  against Nalzok.
                                                                       ^^

**Comment by ostrosablin** [comment]
There also seems to be an extra space after period:

```
Acquire and wear the Mitre of Holiness if you can.  It will aid you  against Nalzok.
                                                  ^^
```

**Comment by sobjornstad** [comment]
@tmp6154: NetHack often follows the old “two spaces after a period” rule, so I wouldn't mark that one as an error.

**Comment by nhmall** [comment]
Commit for f1d0636ba081c1f8052eaa87e9ca4ff85ad59ac9 had typo referencing #124, but should have specified #128

**Comment by AndrioCelos** [comment]
There is one of these in the Wizard quest, too. I think it has to do with the text in the script breaking across lines.

https://github.com/NetHack/NetHack/blob/672e28d294518139129e602f0db1808bc91b503c/dat/quest.txt#L1448-L1449
https://github.com/NetHack/NetHack/blob/672e28d294518139129e602f0db1808bc91b503c/dat/quest.txt#L3107-L3108

**Comment by paxed** [comment]
No longer relevant.
