### ISSUE TITLE
3.7: shops not listed in #overview

### ISSUE THREAD

**Issue by mark-mcknight-oncorps** [NetHack/NetHack#1241]
I've noticed that recently in 3.7 my shops are no longer listed in the level description for #overview.

We still see fountains, temples, altars, etc but notes like "general store" are not displayed.

**Comment by disperse** [comment]
In my 2nd game started this weekend the first general store shows up in the #overview but no other shops are listed, I've annotated shops so you can see the mismatch:
<img width="686" alt="Screenshot 2024-05-06 at 10 27 53 AM" src="https://github.com/NetHack/NetHack/assets/999619/4e5800c8-22d9-479c-85a1-29e820c5734c">

**Comment by disperse** [comment]
This PR fixes the issue: https://github.com/NetHack/NetHack/pull/1243
