### ISSUE TITLE
Cannot remove traps on non-dig levels

### ISSUE THREAD

**Issue by fstd** [NetHack/NetHack#1245]
If there's a trap on a no-dig level, the floor beneath it will always be "too hard to dig into", making it impossible to remove the trap.

As you can still dig pits in these levels (just not holes), the floor under the trap itself resisting to become a pit seems inconsistent.

Steps to reproduce:
1. Go to no-dig level like Mine's End
2. Make a trap
3. Dig a pit next to it -> works
4. Dig on the trap -> does not work

**Comment by nhmall** [comment]
d5785f28
