### ISSUE TITLE
NH_abort (why=0x7ffff492de60 "current hero health (30) better than maximum? (21)") at end.c:1930

### ISSUE THREAD

**Issue by mkuoppal** [NetHack/NetHack#1252]
HEAD:
commit d8aa4c0b1fdbe447c82fc9afc3de0d4f00d038ae
Author: PatR <rankin@nethack.org>
Date:   Sat Jun 1 02:08:06 2024 -0700

produced with debugfuzzer:

NH_abort (why=0x7ffff492de60 "current hero health (30) better than maximum? (21)") at end.c:1930

Full backtrace:

#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff6c4526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff6c288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555556c877cf in NH_abort (why=0x7ffff492de60 "current hero health (30) better than maximum? (21)") at end.c:1930
#6  0x0000555556c7304f in panic (str=0x555557a6cd40 "%s") at end.c:465
#7  0x00005555571a2914 in impossible (s=0x555557bcfca0 "current hero health (%d) better than maximum? (%d)") at pline.c:579
#8  0x000055555760e435 in you_sanity_check () at wizcmds.c:1407
#9  0x000055555760eb1f in sanity_check () at wizcmds.c:1438
#10 0x000055555690363f in moveloop_core () at allmain.c:183
#11 0x0000555556907e54 in moveloop (resuming=0 '\000') at allmain.c:558
#12 0x00005555576a9870 in main (argc=<error reading variable: Cannot access memory at address 0xffffffffffffff90>,
    argv=<error reading variable: Cannot access memory at address 0xffffffffffffffc0>) at ../sys/unix/unixmain.c:323

(gdb) print u
$6 = {ux = 10, uy = 7, dx = 1, dy = -1, dz = 0, tx = 9, ty = 8, ux0 = 9, uy0 = 8, uz = {dnum = 1, dlevel = 14}, uz0 = {dnum = 1, dlevel = 14}, utolev = {dnum = 1, dlevel = 14},
  utotype = 0 '\000', ucamefrom = {dnum = 1, dlevel = 16}, umoved = 1 '\001', last_str_turn = 0, ulevel = 12, ulevelmax = 12, ulevelpeak = 30, utrap = 0, utraptype = 0,
  urooms = "\000\000\000\000", urooms0 = "\000\000\000\000", uentered = "\000\000\000\000", ushops = "\000\000\000\000", ushops0 = "\000\000\000\000", ushops_entered = "\000\000\000\000",
  ushops_left = "\000\000\000\000", uhunger = 802, uhs = 1, uprops = {{extrinsic = 0, blocked = 0, intrinsic = 0}, {extrinsic = 0, blocked = 0, intrinsic = 268435456}, {extrinsic = 0,
      blocked = 0, intrinsic = 0} <repeats 12 times>, {extrinsic = 0, blocked = 0, intrinsic = 7}, {extrinsic = 0, blocked = 0, intrinsic = 1}, {extrinsic = 0, blocked = 0, intrinsic = 0}, {
      extrinsic = 0, blocked = 0, intrinsic = 1}, {extrinsic = 0, blocked = 0, intrinsic = 0} <repeats 11 times>, {extrinsic = 0, blocked = 0, intrinsic = 268435456}, {extrinsic = 0,
      blocked = 0, intrinsic = 0} <repeats 18 times>, {extrinsic = 0, blocked = 0, intrinsic = 268435456}, {extrinsic = 0, blocked = 0, intrinsic = 0} <repeats 19 times>}, umconf = 0,
  usick_type = 1, nv_range = 1, xray_range = -1, unblind_telepat_range = -1, bglyph = 3988, cglyph = 3988, bc_order = 0, bc_felt = 0, umonster = 333, umonnum = 144, mh = 8, mhmax = 98,
  mtimedone = 442, macurr = {a = "\027\003\022\016\017\a"}, mamax = {a = "\027\003\022\016\017\a"}, ulycn = -1, ucreamed = 0, uswldtim = 0, uswallow = 0, uinwater = 0, uundetected = 0,
  mfemale = 0, uinvulnerable = 0, uburied = 0, uedibility = 0, usaving_grace = 1, uhandedness = 0, udg_cnt = 0, uevent = {minor_oracle = 0, major_oracle = 0, read_tribute = 0, qcalled = 0,
    qexpelled = 0, qcompleted = 0, uheard_tune = 0, uopened_dbridge = 0, invoked = 0, gehennom_entered = 1, uhand_of_elbereth = 0, udemigod = 0, uvibrated = 0, ascended = 0}, uhave = {
    amulet = 0, bell = 0, book = 0, menorah = 0, questart = 0, unused = 0}, uconduct = {unvegetarian = 69, unvegan = 83, food = 155, gnostic = 62, weaphit = 40157, killer = 5160, literate = 782,
    polypiles = 0, polyselfs = 1876, wishes = 1340, wisharti = 0, sokocheat = 1350, pets = 4}, uroleplay = {blind = 0 '\000', nudist = 0 '\000', deaf = 0 '\000', numbones = 0}, acurr = {
    a = "v\003\022\v\016\a"}, aexe = {a = "\335\000\316\360", <incomplete sequence \357>}, abon = {a = "\000\000\000\000\000"}, amax = {a = "v\003\022\016\017\a"}, atemp = {
    a = "\000\000\000\000\000"}, atime = {a = "\000\000\000\000\000"}, ualign = {type = 1 '\001', record = 2186, abuse = 939}, ualignbase = "\001\001", uluck = -6 '\372', moreluck = 0 '\000',
  uhitinc = 0 '\000', udaminc = 0 '\000', uac = -1 '\377', uspellprot = 0 '\000', usptime = 0 '\000', uspmtime = 0 '\000', uhp = 30, uhpmax = 21, uhppeak = 1004, uen = 71, uenmax = 81,
  uenpeak = 1123, uhpinc = {16, 8, 8, 10, 4, 10, 7, 11, 4, 6, 4, 4, 3, 6, 6, 5, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 3, 4, 4}, ueninc = {2, 11, 6, 5, 5, 6, 5, 3, 8, 6, 10, 2, 10, 11, 10, 7, 8, 11,
    10, 4, 5, 7, 6, 5, 6, 4, 8, 6, 2, 6}, ugangr = 0, ugifts = 0, ublessed = 0, ublesscnt = 113, umoney0 = 0, uspare1 = 0, uexp = 28675, urexp = 2756290, ucleansed = 0, usleep = 0, uinvault = 0,
  ustuck = 0x0, usteed = 0x0, ustuck_mid = 0, usteed_mid = 0, ugallop = 0, urideturns = 0, umortality = 0, ugrave_arise = -1, weapon_slots = -8, skills_advanced = 14, skill_record = {3, 34, 1,
    4, 17, 25, 10, 3, 21, 15, 27, 28, 34, 10, 28, 28, 28, 0 <repeats 43 times>}, weapon_skills = {{skill = 0, max_skill = 0, advance = 0}, {skill = 2, max_skill = 2, advance = 3724}, {skill = 1,
      max_skill = 3, advance = 26}, {skill = 3, max_skill = 3, advance = 61}, {skill = 2, max_skill = 2, advance = 237}, {skill = 0, max_skill = 0, advance = 0}, {skill = 0, max_skill = 0,
      advance = 0}, {skill = 0, max_skill = 0, advance = 0}, {skill = 0, max_skill = 0, advance = 0}, {skill = 0, max_skill = 0, advance = 0}, {skill = 4, max_skill = 4, advance = 48}, {
      skill = 1, max_skill = 4, advance = 14}, {skill = 1, max_skill = 2, advance = 0}, {skill = 1, max_skill = 3, advance = 1}, {skill = 1, max_skill = 3, advance = 0}, {skill = 2,
      max_skill = 4, advance = 0}, {skill = 1, max_skill = 3, advance = 7}, {skill = 2, max_skill = 4, advance = 2019}, {skill = 1, max_skill = 3, advance = 0}, {skill = 0, max_skill = 0,
      advance = 0}, {skill = 1, max_skill = 3, advance = 5}, {skill = 3, max_skill = 4, advance = 20}, {skill = 0, max_skill = 0, advance = 0}, {skill = 0, max_skill = 0, advance = 0}, {
      skill = 0, max_skill = 0, advance = 0}, {skill = 2, max_skill = 4, advance = 1}, {skill = 0, max_skill = 0, advance = 0}, {skill = 2, max_skill = 2, advance = 14}, {skill = 2,
      max_skill = 2, advance = 0}, {skill = 0, max_skill = 0, advance = 0}, {skill = 0, max_skill = 0, advance = 0}, {skill = 0, max_skill = 0, advance = 0}, {skill = 0, max_skill = 0,
      advance = 0}, {skill = 0, max_skill = 0, advance = 0}, {skill = 3, max_skill = 3, advance = 2}, {skill = 2, max_skill = 5, advance = 57092}, {skill = 0, max_skill = 0, advance = 0}, {
      skill = 0, max_skill = 0, advance = 0}}, twoweap = 0 '\000', mcham = -1, umovement = 18,
  uachieved = "\025\002\351\350\017\020\021\347\026\032\033\034\035\036\022\v", '\000' <repeats 15 times>}

**Comment by elunna** [comment]
I also ran into this and saw a clue, "You dream that you feel weaker" from gt.toplines. Which led me to think it has something to do with poison damage.

I think there might be a mismatch between hp and maxhp loss here: https://github.com/NetHack/NetHack/blob/8085d038980a133fe76d609e486475538be46976/src/attrib.c#L366.

Maybe after losehp, check if hp is still higher than the max?

**Comment by elunna** [comment]
Here: https://github.com/NetHack/NetHack/blob/4415fc21544c00996c065501c4261c0d79c1f2b9/src/mcastu.c#L395, we might also need a call to setuhpmax.  u.uhpmax is directly modified and the hp is handled separately right after.
