### ISSUE TITLE
stdio.h not found by cstd.h

### ISSUE THREAD

**Issue by shootmeinthehead** [NetHack/NetHack#1255]
![image](https://github.com/NetHack/NetHack/assets/111381039/79cd1a09-686f-4cf4-86c1-b620119c8b9c)

**Comment by nhmall** [comment]
How did you start the command prompt that you are using?

The simplest way to set things up is to use one of the shortcuts that Visual Studio provides from Start, All Apps, which sets things up for the compiler.

![starting-visual-studio-command-prompt](https://github.com/NetHack/NetHack/assets/9643004/daca2eaa-6742-4e15-99e6-0b3139dfb305)

**Comment by shootmeinthehead** [comment]
In VS 2022, original, the x64_x86 and the Shell Bash (used nmake clean if something interfears)

**Comment by shootmeinthehead** [comment]
@nhmall idk, but i have reinstalled my windows cuz of some bugged things in the Regestry Editor and was messed up, i did it like 1 month ago and havent messed that much with programming since cuz i got back i have more time (anyway not trying to flex, but i got like big knowage in the IT sphere, but still aint sure if i got the default stdio.h, it could go very bad in later versions of the game) So i have installed again my VS, libs, Unix Subsystem and all that. I Just wanted to ask if something i havent installed right now, couldve made the problem (why idk?, cuz i dont know how the game is coded :D but i love it) sorry for wasting your time a 2nd time. Probably you remember this https://github.com/NetHack/NetHack/issues/1208 . Thank you, overall!

**Comment by nhmall** [comment]
If you're using powershell, does doing this prior to starting your build help?
```
& 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\Launch-VsDevShell.ps1'
```

**Comment by shootmeinthehead** [comment]
and the string to the end right? i will give feedback tomorow i have to sleep right now. Thank you solution!

**Comment by shootmeinthehead** [comment]
intresting i dont have the Microsoft Visual Studio folder in Program Files is have one in the x86 but there are different things anyway i found the pat at D:\VS\Commo7\Tools\Launch-VsDevShell.ps1 but how do i put it in the bash. Just run with powershell or add to nmake package & ...

**Comment by nhmall** [comment]
Despite your custom folder that you've installed Visual Studio in, do you still have vswhere.exe located at this location?
"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"

For instance, does this work?
`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath`
