### ISSUE TITLE
SIGSEGV generated when checking mindless() during sensemon() call

### ISSUE THREAD

**Issue by sacroall** [NetHack/NetHack#1265]
NetHack Version 3.7.0-106 (built July 30th)

Monster data is null causing exception when checking mindless.  Core file is available.

Program received signal SIGSEGV, Segmentation fault.
0x000a5478 in sensemon (mon=0xb82c98) at display.c:175
175         return _sensemon(mon);
(gdb) where
#0  0x000a5478 in sensemon (mon=0xb82c98) at display.c:175
#1  0x001bf668 in decide_to_shapeshift (mon=0xb82c98) at mon.c:4726
#2  0x001b2634 in m_calcdistress (mtmp=0xb82c98) at mon.c:1154
#3  0x001be064 in iter_mons (vfunc=0x1b25ac <m_calcdistress>) at mon.c:4376
#4  0x001b25a0 in mcalcdistress () at mon.c:1133
#5  0x000460a0 in moveloop_core () at allmain.c:205
#6  0x0004708c in moveloop (resuming=1 '\001') at allmain.c:558
#7  0x0035c2f8 in main (argc=1, argv=0xffdd0ad4) at ../sys/unix/unixmain.c:323

(gdb) print mon
$1 = (struct monst *) 0xb82c98
(gdb) print *mon
$2 = {nmon = 0xb74d48, data = 0x0, m_id = 1073, mnum = 258, cham = 327, movement = 0, m_lev = 15 '\017',
  malign = 5 '\005', mx = 44, my = 12, mux = 72, muy = 16, mtrack = {{x = 43, y = 13}, {x = 42, y = 14}, {x = 42,
      y = 15}, {x = 41, y = 15}}, mhp = 80, mhpmax = 80, mappearance = 0, m_ap_type = 0 '\000', mtame = 0 '\000',
  mintrinsics = 0, mextrinsics = 0, seen_resistance = 0, mspec_used = 0, female = 0, minvis = 0, invis_blkd = 0,
  perminvis = 0, mcan = 0, mburied = 0, mundetected = 0, mcansee = 1, mspeed = 0, permspeed = 0, mrevived = 0,
  mcloned = 0, mavenge = 0, mflee = 0, mfleetim = 0, msleeping = 0, mblinded = 0, mstun = 0, mfrozen = 0,
  mcanmove = 1, mconf = 0, mpeaceful = 0, mtrapped = 0, mleashed = 0, isshk = 0, isminion = 0, isgd = 0, ispriest = 0,
  iswiz = 0, wormno = 0, mtemplit = 0, meverseen = 0, mspotted = 0, mstrategy = 0, mtrapseen = 0, mlstmv = 0,
  mstate = 0, migflags = 0, mspare1 = 0, minvent = 0x0, mw = 0x0, misc_worn_check = 0, weapon_check = 0, meating = 0,
  mextra = 0x0}

From code I see: `#define mindless(ptr) (((ptr)->mflags1 & M1_MINDLESS) != 0L)`

Which is called from:
`
#define _tp_sensemon(mon) \
    (/* The hero can always sense a monster IF:        */  \
     /* 1. the monster has a brain to sense            */  \
     (!mindless(mon->data))                                \
`

mon->data is null causing SIGSEGV:

(gdb) print mon->data
$7 = (struct permonst *) 0x0

(gdb) print *mon->data
Cannot access memory at address 0x0

(gdb) print ((mon->data)->mflags1 & 0x00010000L)
Cannot access memory at address 0x38

**Comment by paxed** [comment]
This has already been fixed in commit e5504367550ecb906f6f06f8479c2b78b1ad6190
