### ISSUE TITLE
Look for .nethackrc in multiple locations?

### ISSUE THREAD

**Issue by syswraith** [NetHack/NetHack#1297]
Can we have nethack look in `$XDG_CONFIG_HOME/nethack/nethackrc` and `$HOME/.config/nethack/nethackrc` for its default configurations, in addition to $HOME/.nethackrc? That will make running version control on dotfiles much easier.

**Comment by paxed** [comment]
Put the config file location in `$NETHACKOPTIONS`

**Comment by syswraith** [comment]
Oh alright, that's good too. Thank you.
