### ISSUE TITLE
All engravings show up on the map while blind

### ISSUE THREAD

**Issue by ars3niy** [NetHack/NetHack#1303]
Stepping on a square with a dust or "graffiti" engraving while blind produces no message because presumably you can't read them by swiping the floor with your hands, however the engraving glyph still shows up on the map afterwards. While this helps zen players, it looks like a bug.

**Comment by ville-v** [comment]
Searching while blind also reveals the engravings. Here is a save file demonstrating the issue.

[bug with engraving while blind 1000Marie.gz](https://github.com/user-attachments/files/18162285/bug.with.engraving.while.blind.1000Marie.gz)
