### ISSUE TITLE
player can move out of a doorway on a diagonal when failing an untrap attempt

### ISSUE THREAD

**Issue by loggersviii** [NetHack/NetHack#1305]
reproducing this is easy. all you need is a doorway and the humble beartrap (or any trap of your choice). Place the trap on a diagonal from the doorway, stand in the doorway, and attempt to untrap it. If you fail, you'll be placed on top of the trap, even though diagonal movement out of a doorway is supposed to be impossible.

**Comment by elunna** [comment]
You can also be hurtled diagonally out of a doorway by a giant monster that gets the new clobber attack on you.
