### ISSUE TITLE
Monsters with ranged attacks don't approach if you resist their damage type.

### ISSUE THREAD

**Issue by elunna** [NetHack/NetHack#1307]
A good example of this is the winter wolf. If you start combat with a winter wolf which has a ranged cold breath attack and you have cold resistance, it will shoot one blast at you, it will see you resist the cold (triggering monstseesu(M_SEEN_COLD)), and then it will stop firing cold rays. However, it will not approach and just keep out of range. Unless you purposely approach it, it won't engage with you. This applies to many other monsters (dragons, nagas, hell hounds, etc).

I think this is a bug because once the monster recognizes it can't use its ranged attack it should pursue an alternative attack, which usually would just be approaching and attacking directly.

On testing the iron golem, I noticed it would continue to keep firing poison breaths at us if we had poison res or reflection, and it would eventually approach us, but the winter wolf would not.

**Comment by nhmall** [comment]
Does this test patch make a difference?
https://gist.github.com/nhmall/2f8c0b3c8285aa1bbd78a4690b9e1181

**Comment by elunna** [comment]
Yes - I was able to test a few monsters (winter wolf and red dragon) again
and the monster immediately approaches after it sees the resistance. I also
tested the iron golem, that is working fine too. Thanks for coding up a fix
for this!
