### ISSUE TITLE
Official WASM Release?

### ISSUE THREAD

**Issue by apowers313** [NetHack/NetHack#1332]
Would it be possible to get an [official release](https://www.nethack.org/v367/downloads.html) for WASM? It might help facilitating the spread of NetHack to other platforms, including the web and mobile. It would probably help ensure that the WASM build doesn't [fall into disrepair](https://github.com/NetHack/NetHack/pull/1331) either.

**Comment by paxed** [comment]
It's in the development version, which is not yet released. 3.6 does not have WASM.
