### ISSUE TITLE
 [3.7 editlevel 110] #Enhance did not trigger for polearm-wielding Healer

### ISSUE THREAD

**Issue by chappg** [NetHack/NetHack#1335]
TITLE: [3.7 editlevel 110] #Enhance did not trigger for polearm-wielding Healer

STEPS TO REPRO:
1. Play as healer
2. In the early game, pickup a polearm
3. Hit for >20 hits

RESULTS: 
Polearm is still Unskilled 

EXPECTED:
An enhance notice given to the player allowing the skill to be upgraded to Basic via the #enhance command

NOTES:
*Here's an example game where this happened to me: https://hardfought.org/userdata/a/a1/nethack/dumplog/1733373357.nh.html. I spent most of the game wielding a glaive (polearm), and very certainly exceeded 20 hits to achieve Basic skill, but was unable to enhance my skill.
* the threshold for hits to upgrade from Unskilled should be 20: https://nethackwiki.com/wiki/Skill
* Healers can reach Basic skill in polearm: https://nethackwiki.com/wiki/Healer

**Comment by entrez** [comment]
From the ttyrec for that game, it appears you are hitting monsters with the polearm by moving into them. That works in a pinch, sort of, but it's not the right way to use a polearm, which works differently from a normal melee weapon. It has a longer range than a normal weapon, and can't effectively hit monsters adjacent to you. You have to apply it with 'a' and select a location. Using it properly that way is the only thing that trains the skill.

From the Wiki, https://nethackwiki.com/wiki/Polearm: 

> Applying polearms to pound monsters will not trigger passive attacks against the wielder, but will scuff engravings on their square and cause Elbereth to fade, and the polearm itself is still subject to the effects of passive attacks (e.g. erosion, disenchantment, etc.) as normal.[4] Polearms can only be properly used in melee by a hero that is riding, and will otherwise only deal d2 damage by bashing them with the pole, which does not train the skill.

**Comment by chappg** [comment]
> onsters will not trigger passive attacks against the wielder, but will scuff engravings on their square and cause Elbereth to fade, and

thank you, this the root cause and it's by design.
