### ISSUE TITLE
Program in disorder when buying many items at once

### ISSUE THREAD

**Issue by ars3niy** [NetHack/NetHack#1339]
Steps to reproduce:
* Enter a shop with at least 9 items (none of which stack) with lots of gold and a bag
* Pick up 6 items and put them in the bag
* Pick up 3 more
* Pay for everything

Result: lots of "program in disorder" messages.

Sometimes (and I don't know what the conditions for that are) I also get a "Please pay for the other X before buying this one" amongst all the disorder messages and then end up with "X (unpaid, 0 zorkmids)" in my inventory which causes disorder message each time inventory is redrawn. When then trying to pay, the payment menu shows I owe money for a completely different item which in my inventory is not shown as unpaid. I can then pay for that, leave the shop and walk around still in possession of "X (unpaid, 0 zorkmids)".

**Comment by nhmall** [comment]
There’s a specific message, that accompanies the “program in disorder” message, that usually helps identify the code line involved. You haven’t included it.

There are 607 calls to impossible() in the code in the src directory, and the "program in disorder" part results from all of them. It's the accompanying message that provides potentially helpful information to help track down the issue. That's particularly useful if the developer is having difficulty reproducing it.

**Comment by ars3niy** [comment]
This problem is very straightforward to reproduce though, it just takes several tries. One needs to keep bless-genociding mimics and diving to minetown until one gets a variant with shops big enough.

Here is the whole sequence of messages:

You bought the contents of your bag for 370 gold pieces.
You bought a pink potion for 11 gold pieces.
unpaid_cost: object wasn't on any bill.
Program in disorder!  (Saving and reloading may fix this problem.)
Please report these messages to devteam@nethack.org.
unpaid_cost: object wasn't on any bill.
Program in disorder!  (Saving and reloading may fix this problem.)
Please report these messages to devteam@nethack.org.
You bought a dark green potion for 67 gold pieces.
unpaid_cost: object wasn't on any bill.
Program in disorder!  (Saving and reloading may fix this problem.)
Please report these messages to devteam@nethack.org.
unpaid_cost: object wasn't on any bill.
Program in disorder!  (Saving and reloading may fix this problem.)
Please report these messages to devteam@nethack.org.
You bought a pair of jungle boots for 133 gold pieces.
"Thank you for shopping in Chibougamau's general store!"

**Comment by ars3niy** [comment]
As a software developer myself, I know from experience that there is nothing more important when working on a bug than being able to reproduce it at will if at all possible. This is why for every bug I have reported so far, including this one, I've done my absolute best to try and find the exact steps, even if it took several days (which for this one it thankfully took only half an hour).

**Comment by ars3niy** [comment]
I'm still getting the same problem. I am attaching a save file (where all that remains to trigger the error messages is to pay for everything) and my config.
[unpaid_stuff.gz](https://github.com/user-attachments/files/18278297/unpaid_stuff.gz)
[nethackrc.txt](https://github.com/user-attachments/files/18278300/nethackrc.txt)

Here is more information about what's happening. Please take time to read the wall of text below because it not only explains the issue at hand but also demonstrates the technique that should be used for investigating bugs in general. I've used gdb and step-by-step debugging but same can be achieved by inserting code to print (to stderr or to a file) everything that I used "print" command in gdb for.

Inventory:
```
 a) +1 long sword (weapon in right hand)
 b) +1 lance (alternate weapon; not wielded)
 c) uncursed +1 ring mail (being worn)
 d) uncursed +0 helmet (being worn)
 e) uncursed +0 small shield (being worn)
 f) uncursed +0 pair of leather gloves (being worn)
 g) 11 uncursed apples
 h) 12 uncursed carrots
 s) scroll labeled PRATYAVAYAH (unpaid, 13 zorkmids)
 q) clear potion (unpaid, 3 zorkmids)
 r) golden potion (unpaid, 67 zorkmids)
 t) bag containing 6 items (contents, 297 zorkmids)
```

In the bag is:
```
 a) a mace (unpaid, 3 zorkmids)                 
 b) a pair of low boots (unpaid, 5 zorkmids)    
 c) a food ration (unpaid, 30 zorkmids)
 d) a tripe ration (unpaid, 10 zorkmids)        
 e) a scroll labeled KO BATE (unpaid, 71 zorkmids)
 f) a parchment spellbook (unpaid, 178 zorkmids)
```

Shopkeeper bill:
```
(gdb) print eshkp->billct
$95 = 9
(gdb) print eshkp->bill
$96 = {{bo_id = 644, useup = 0 '\000', price = 71, bquan = 1},
 {bo_id = 648, useup = 0 '\000', price = 178, bquan = 1},
 {bo_id = 646, useup = 0 '\000', price = 30, bquan = 1},
 {bo_id = 649, useup = 0 '\000', price = 5, bquan = 1},
 {bo_id = 650, useup = 0 '\000', price = 3, bquan = 1},
 {bo_id = 652, useup = 0 '\000', price = 10, bquan = 1},
 {bo_id = 651, useup = 0 '\000', price = 3, bquan = 1},
 {bo_id = 655, useup = 0 '\000', price = 67, bquan = 1},
 {bo_id = 654, useup = 0 '\000', price = 13, bquan = 1},
 {bo_id = 0, useup = 0 '\000', price = 0, bquan = 0} <repeats 191 times>}
```

Itemised bill:
```
(gdb) print ibillct
$99 = 4
(gdb) print (Bill [4])*ibill
$106 = {{obj = 0x90a500, cost = 297, quan = 1, bidx = 0, usedup = 5 '\005', queuedpay = 1 '\001'},
 {obj = 0x8cb820, cost = 67, quan = 1, bidx = 7, usedup = 4 '\004', queuedpay = 1 '\001'},
 {obj = 0x8bc740, cost = 13, quan = 1, bidx = 8, usedup = 4 '\004', queuedpay = 1 '\001'},
 {obj = 0x8c0450, cost = 3, quan = 1, bidx = 6, usedup = 4 '\004', queuedpay = 1 '\001'}}
```

For the 1st item on itemised bill pay_billed_items calls buy_container which selects these objects from shopkeeper bill:
```
(gdb) print boidsct
$107 = 6
(gdb) print boids
$108 = {644, 648, 646, 649, 650, 652, junk...
```

buy_container calls update_bill for the 1st item on container bill (scroll KO BATE). Now ibill[0].cost is 226 (itemised bill otherwise unchanged) and shopkeeper bill becomes
```
(gdb) print eshkp->billct
$112 = 8
(gdb) print (struct bill_x[8])*eshkp->bill_p
$114 = {{bo_id = 654, useup = 0 '\000', price = 13, bquan = 1},
 {bo_id = 648, useup = 0 '\000', price = 178, bquan = 1},
 {bo_id = 646, useup = 0 '\000', price = 30, bquan = 1},
 {bo_id = 649, useup = 0 '\000', price = 5, bquan = 1},
 {bo_id = 650, useup = 0 '\000', price = 3, bquan = 1},
 {bo_id = 652, useup = 0 '\000', price = 10, bquan = 1},
 {bo_id = 651, useup = 0 '\000', price = 3, bquan = 1},
 {bo_id = 655, useup = 0 '\000', price = 67, bquan = 1}}
```

buy_container calls update_bill for the 2nd item on container bill (parchment spellbook). Now ibill[0].cost is 48 and shopkeeper bill is

```
(gdb) print (struct bill_x[7])*eshkp->bill_p
$123 = {{bo_id = 654, useup = 0 '\000', price = 13, bquan = 1},
 {bo_id = 655, useup = 0 '\000', price = 67, bquan = 1},
 {bo_id = 646, useup = 0 '\000', price = 30, bquan = 1},
 {bo_id = 649, useup = 0 '\000', price = 5, bquan = 1},
 {bo_id = 650, useup = 0 '\000', price = 3, bquan = 1},
 {bo_id = 652, useup = 0 '\000', price = 10, bquan = 1},
 {bo_id = 651, useup = 0 '\000', price = 3, bquan = 1}}
```

buy_container calls update_bill for the 3rd item on container bill (food ration). Now ibill[0].cost is 18 and shopkeeper bill is
```
(gdb) print (struct bill_x[6])*eshkp->bill_p
$126 = {{bo_id = 654, useup = 0 '\000', price = 13, bquan = 1},
 {bo_id = 655, useup = 0 '\000', price = 67, bquan = 1},
 {bo_id = 651, useup = 0 '\000', price = 3, bquan = 1},
 {bo_id = 649, useup = 0 '\000', price = 5, bquan = 1},
 {bo_id = 650, useup = 0 '\000', price = 3, bquan = 1},
 {bo_id = 652, useup = 0 '\000', price = 10, bquan = 1}}
```

buy_container calls update_bill for the 4th item on container bill (low boots). Now ibill[0].cost is 13 and shopkeeper bill is
```
(gdb) print (struct bill_x[5])*eshkp->bill_p
$129 = {{bo_id = 654, useup = 0 '\000', price = 13, bquan = 1},
 {bo_id = 655, useup = 0 '\000', price = 67, bquan = 1},
 {bo_id = 651, useup = 0 '\000', price = 3, bquan = 1},
 {bo_id = 652, useup = 0 '\000', price = 10, bquan = 1},
 {bo_id = 650, useup = 0 '\000', price = 3, bquan = 1}}
```

buy_container calls update_bill for the 5th item on container bill (mace, which happens to be cursed -4). Now ibill[0].cost is 10 and shopkeeper bill is
```
(gdb) print (struct bill_x[4])*eshkp->bill_p
$134 = {{bo_id = 654, useup = 0 '\000', price = 13, bquan = 1},
 {bo_id = 655, useup = 0 '\000', price = 67, bquan = 1},
 {bo_id = 651, useup = 0 '\000', price = 3, bquan = 1},
 {bo_id = 652, useup = 0 '\000', price = 10, bquan = 1}}
```

buy_container calls update_bill for the 6th item on container bill (tripe ration). Now ibill[0].cost is 0 and shopkeeper bill is
```
(gdb) print (struct bill_x[3])*eshkp->bill_p
$138 = {{bo_id = 654, useup = 0 '\000', price = 13, bquan = 1},
 {bo_id = 655, useup = 0 '\000', price = 67, bquan = 1},
 {bo_id = 651, useup = 0 '\000', price = 3, bquan = 1}}
```

and that is buy_container done.

For the 2nd item on itemised bill (golden potion) pay_billed_items has bidx=7 which is greater than eshkp->billct (the latter is 3) but eshkp->bill_p[7] is still correct: {bo_id = 655, useup = 0 '\000', price = 67, bquan = 1}. This somewhat-out-of-bounds entry will always have the correct content because the only entries that are being overwritten are those that contain objects that are being paid for.

pay_billed_items calls dopayobj (You bought a golden potion for 67 gold pieces.). pay_billed_items calls update_bill. Itemised bill is unchanged and shopkeeper bill is now
```
(gdb) print (struct bill_x[2])*eshkp->bill_p
$235 = {{bo_id = 654, useup = 0 '\000', price = 13, bquan = 1},
 {bo_id = 655, useup = 0 '\000', price = 67, bquan = 1}}
```
which is wrong: bill_p[2] (clear potion) has been copied to bill_p[7] and effectively removed from the bill, while bill_p[1] still contains the now-paid golden potion.

And now update_inventory immediately runs into trouble when rendering the clear potion (I use curses with permanent inventory on) because it is unpaid but no longer on the shopkeeper bill.
```
(gdb) bt
#0  unpaid_cost (unp_obj=0x8c0450, cost_type=1 '\001') at shk.c:3222
#1  0x00000000005af2b7 in doname_base (obj=0x8c0450, doname_flags=0) at objnam.c:1638
#2  0x00000000005af711 in doname (obj=0x8c0450) at objnam.c:1729
#3  0x00000000005297dc in display_pickinv (lets=0x0, xtra_choice=0x0, query=0x0, allowxtra=0 '\000', want_reply=0 '\000', out_cnt=0x0)
    at invent.c:3873
#4  0x0000000000529cb1 in display_inventory (lets=0x0, want_reply=0 '\000') at invent.c:4002
#5  0x00000000006dad5f in curs_update_invt (arg=0) at ../win/curses/cursinvt.c:99
#6  0x00000000006ce1fc in curses_update_inventory (arg=0) at ../win/curses/cursmain.c:801
#7  0x00000000005256b9 in update_inventory () at invent.c:2703
#8  0x000000000062547e in pay_billed_items (shkp=0x8c0230, ibillct=4, ibill=0x8ed0a0, stashed_gold=0 '\000', 
    paid_p=0x7fffffffd7a7 "\001\240Ў") at shk.c:2074
```

**Comment by ars3niy** [comment]
So what was happening prior to https://github.com/NetHack/NetHack/commit/ecbb7cff4dfe414d5be73a3740a55b4604528445? I will show printf-debugging this time. Attached is a patch that prints all the same things that the previous comment lists, as well as the resulting messages, making it clear what goes wrong.

Now, you seem to have reproduced the other variant of the bug I originally mentioned, one where inventory stays corrupted after payment is complete. That is indeed somewhat rare and I do not have a save for that right now, but running such save with same or similar debug log should provide answers there as well.

[0001-shk-debug.txt](https://github.com/user-attachments/files/18281014/0001-shk-debug.txt)
[shk.log](https://github.com/user-attachments/files/18281015/shk.log)
