### ISSUE TITLE
Windows Message: 'windowcolors for unrecognized window type' on MSYS2 Build

### ISSUE THREAD

**Issue by rlaa54** [NetHack/NetHack#1345]
Hello,
I would like to report an issue regarding a Windows message that appears when building and running NetHack in an MSYS2 environment on Windows 10. The message is as follows:

OPTIONS=windowcolors:status white #000000 message white/#000000 text white/#000000 menu white/#000000 menutext white/#000000  
* Line 137: windowcolors for unrecognized window type: menutext.  
1 error in C:\Users\____\NetHack\.nethackrc

my hardware:
processor: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
amount of memory: 16GB
amount of disk space: 593.72GB

my software:
operating system: windows 10 pro
operating system version: 22H2
compiler (including version): gcc.exe (Rev2, Built by MSYS2 project) 14.2.0
which NetHack binary you are running: NetHackW.exe 
windows NetHack Version 3.7.0-112 Work-in-progress

Thank you.

**Comment by paxed** [comment]
You already have "menu" and "text" windows defined there. "menutext" is not a window, it's a special color available when using NetHackW.exe
