### ISSUE TITLE
Alignment change can leave characters on the screen

### ISSUE THREAD

**Issue by copperwater** [NetHack/NetHack#143]
When I, as a chaotic character, put on a helm of opposite alignment, the alignment string in the status bar changes to "Lawfulc" - the c being the seventh letter of "Chaotic" that didn't get cleared. I think this also happens with Neutral->Lawful as well, and any other change doesn't matter because the full string would be overwritten.

Using ^R to redraw the screen clears off the trailing character.

**Comment by nhmall** [comment]
Resolved upstream; it will show up here within about 4 hours.
56395395683a31800bfede504c007ff7035ccf82
bdc9a6b98e16b654d7ee210e33bfa20030f53dd1
