### ISSUE TITLE
Life saving while being digested causes instadeath on the next hit.

### ISSUE THREAD

**Issue by AndrioCelos** [NetHack/NetHack#148]
The following is one of the several things that happen when your life is saved by an amulet of life saving:
https://github.com/NetHack/NetHack/blob/d4ebae12f1a709d1833cf466dd0c553fb97518d2/src/end.c#L854
This means you die on the next hit, possibly unintentionally caused.
### Steps to reproduce

1. Start a game in wizard mode.
2. Wish for an amulet of life saving and a wand of death, and put on the amulet.
3. Use `Ctrl`+`G` to summon a purple worm and let it swallow you.
4. Though it's generally considered to be a bad move, zap yourself with the wand of death. This doesn't cause you to be regurgitated as hit point loss would.

**Comment by nhmall** [comment]
Fixed in 858e9ce00d3fda6fbee3263972591d742ea7e861
