### ISSUE TITLE
Moving with 'm' into an unseen pet gives the 'Pardon me' message.

### ISSUE THREAD

**Issue by AndrioCelos** [NetHack/NetHack#149]
If the pet is on a space marked with the `I`, you get the '`Pardon me, Aja`' message, even though you can't tell what monster is there. (Otherwise you get '`Wait! There's something there you can't see!`'.) This seems odd; it should probably give '`You move right into it.`' instead.

**Comment by Xaleth** [comment]
I think that's intentional as the comment says:
                /* m_monnam(): "dog" or "Fido", no "invisible dog" or "it" */

*hack.c line 1553
