### ISSUE TITLE
Genociding peaceful watchmen does not trigger murder

### ISSUE THREAD

**Issue by Xaleth** [NetHack/NetHack#152]
The title says it all. Genociding means mass killing, and watchmen are generated peaceful so it should be considered murder.

**Comment by AndrioCelos** [comment]
There's also no penalty for genociding pets... it may be intentional.

**Comment by Xaleth** [comment]
@AndrioCelos but it makes no sense that killing a single watchman or killing a pet triggers penalties while genociding them doesn't...

**Comment by AffanIndo** [comment]
I think it because when you genociding something, you are not the one killing them. Genocide doesn't break the pacifist conduct. I think this is intentional. As the wiki said:

> Genocide does not break the pacifist conduct. There is no penalty for genociding a species including pets or peaceful monsters, except the usual slight alignment hit for lawful non-demons or chaotic demons.

**Comment by Xaleth** [comment]
Oh ok, didn't read that.
