### ISSUE TITLE
Shopkeeper still gives welcome messages even though hero is deaf

### ISSUE THREAD

**Issue by Xaleth** [NetHack/NetHack#157]
Title says it all. Being deaf means you can't hear anything at all, but when entering a shop, you still get a welcome message from the shopkeeper.

**Comment by Xaleth** [comment]
It should be something like "You see <shopkeeper> welcoming you." or something like that instead.

In some cases when you're bringing a pickaxe in, I'm not sure...

**Comment by Rhialto** [comment]
"You see" won't work if you're blind. But in any case, the shopkeeper probably runs an accessible shop, taking into account its customers' needs...

**Comment by nhmall** [comment]
Actually, the title doesn't say it all. It doesn't say what version/build/commit you are playing. Commit 5bb3e01424 from 2016 was meant to address that very issue? Do you have any more details about the circumstances if you are playing a current build?
