### ISSUE TITLE
Treasure zoos can generate extra awake monsters

### ISSUE THREAD

**Issue by Tomsod** [NetHack/NetHack#166]
Sometimes, when generating a treasure zoo, a monster can be created that appears in small/large groups normally (e.g. an orc).  Often in the process several other monsters of the same type will be created, but those extra monsters will not be generated asleep.

Why is this happening?  Unlike other special rooms, for treasure zoos `fill_zoo()` calls `makemon()` with 0 as the monster type: (treasure zoo is the last case)
https://github.com/NetHack/NetHack/blob/a9e8ad923646e5614f373f62990f278eaacf07b7/src/mkroom.c#L327-L344
And `makemon()` thus considers it acceptable to attempt creating monster groups:
https://github.com/NetHack/NetHack/blob/a9e8ad923646e5614f373f62990f278eaacf07b7/src/makemon.c#L1109
https://github.com/NetHack/NetHack/blob/a9e8ad923646e5614f373f62990f278eaacf07b7/src/makemon.c#L1367-L1375
Normally, any monster created in a special room is made asleep:
https://github.com/NetHack/NetHack/blob/a9e8ad923646e5614f373f62990f278eaacf07b7/src/mkroom.c#L345-L346
But, since `makemon()` only returns the first generated monster, the extra monsters are not reached by this code and usually remain awake.

This does not happen for any other special rooms because they explicitly specify monster type to `makemon()`.

**Comment by nhmall** [comment]
Resolved as of 150d01a9651e0f0c0f26aa8ecf40c553ce0d5ebe

Thanks for reporting it and for the analysis.
