### ISSUE TITLE
I can't cast spells when polymorphed into certain monsters with no explaination as to why

### ISSUE THREAD

**Issue by Labtop-215** [NetHack/NetHack#171]
In particular, I can't cast spells as a wraith, as a zruty, or as a minotaur.

But I can cast spells when polymorphed into a skeleton, or a disenchanter just fine.

What is it with the above forms that prevents me from being able to cast spells while I'm, polymorphed into them?

Edit:  I used to be able to cast spells as these forms in previous versions of nethack, which is why I'm confused that I can't do it now.

**Comment by Tomsod** [comment]
Yes, one of 3.6.1 changes prevents you from casting if you cannot pronounce words.  All three of those monsters are `MS_SILENT`, which presumably means they can't talk, and thus, cast.

**Comment by Labtop-215** [comment]
Good to know.  It makes sense that a monster that can't speak, can't cast spells.

That's curious though.  Why are those three tagged as monsters that cannot speak?  Especially wraiths, didn't they shriek like every time something happened to or around them?

**Comment by AndrioCelos** [comment]
Not in this game. Shriekers do, though.
