### ISSUE TITLE
Unable to open SYSCF_FILE

### ISSUE THREAD

**Issue by vichoca9** [NetHack/NetHack#173]
I compiled and copied Nethack3.6.1(*) linux version to an USB stick, so I that way I would play anywhere on any pc, but there was this error related to syscf.

I changed the nethack script to match the HACKDIR (Ex: /home/mars), but the error was still there.

So, I've found to possible ways to solve this:
1) Edit in binary mode the /nethackdir/nethack executable (with vi) and rename some symbols or stuff to the new HACKDIR
2) Undefinde or disable SYSCF.

The first option keeps the usage of syscf, but I've tried to rename the  "/home/mars" strings inside it and it gives a dl-version error.
`Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion 'needed != NULL' failed!`

The 2nd option worked when I commented out CFLAGS -DSYSCF* in the hints/linux file and in the config.h *(it didnt work if config.h only was edited)*, so this way the other makefiles in /doc and other directories dont have this CFLAG that defines the symbol.

Hope this helps.
(sorry bad English)

PD:There has to be a way to make nethack non-dependant with /home/* folder. Yes, there it is /usr, but I have no admin privs. Maybe something like the Win32 or MSDOS versions....

**Comment by ostrosablin** [comment]
Linux is not very good, when it comes to software portability (in a way you'd expect on Win32 system). There have been attempts to make portable apps, similar to Win32 counterpart, but it's still clunky. There are several solutions, though.

For HACKDIR, you could use relative home path, e.g. ~/nethackdir - that would automatically point it to appropriate home dir on any PC (e.g. /home/mars/nethackdir).

But dl-version error suggests that you compiled NetHack on a PC with different libraries and binary is incompatible with libraries on other PC. This is a more difficult issue to deal with, but still could be solved. You could build a statically-linked binary, which includes all libraries inside of an executable.

Or you could have NetHack source on USB stick. Doesn't require admin privileges, but requires to have GCC and headers on a machine.

Alternative options would be to use dockerized NetHack (requires that Docker is available on all PCs).

Finally, as a last resort, you can take a MS-DOS version + portable DOSBox, e.g. flatpak (this has advantage that you could play same executable everywhere, and if you have a portable Win32 DOSBox on the stick, then you could also play same save on different Linux and Windows machines).

Personally, my solution for "portable" NetHack is to have it at home on a Raspberry Pi and to play it from any computer through SSH. But this requires to have an Internet connection on all PCs and SSH client available.

**Comment by ghost** [comment]
Hi team.
No need to change the code.
After successfully compiled and installed, just create "sysconf" folder next to your nethack binary. Just it.
see doc/nethack.txt:

```
       sysconf                     System-wide options.  Required if
                                   program is built with 'SYSCF' option
                                   enabled, ignored if not.
       
       The  location  of  'sysconf'  is  specified  at build time and can't be
       changed except by updating source file "config.h"  and  rebuilding  the
       program.
```

**Comment by aaron-michaux** [comment]
This is still an issue.

With the "hints" system, VARFILEPERM should be 0644, instead of 0600. Users do need to read this file.

Also in `files.c` we have this error message:
```
raw_printf("Unable to open SYSCF_FILE.\n")
```

This is opaque unless you're already familiar with building nethack. Better would be:

```
raw_printf("Unable to open SYSCF_FILE '%s'.\n", SYSCF_FILE);
```

At least a unix knowledgable person knows which file to check.

Better still is to check read-permissions for the file, and report the actual error that's preventing the program from opening:

```
const char* reason = "";
   if(errno == EACCES) reason = ": permission denied";
   raw_printf("Unable to open SYSCF_FILE '%s'%s\n", SYSCF_FILE, reason);
   ```

**Comment by treatmesubj** [comment]
On Ubuntu, I ...
1. downloaded 3.6.6 source
2. changed `PREFIX=/usr` in `<$top>/sys/unix/hints/linux`
3. ran `sh <$top>/sys/unix/setup.sh <$top>/sys/unix/hints/linux`
4. `sudo -i`
5. `cd <$top>`
6. `make all`
7. `make install`

which nicely installed nethack to `/usr/games` however I was getting the below error when trying to run `sh /usr/games/nethack` as non-root
```
Warning: cannot write scoreboard file 'record'

Unable to open SYSCF_FILE.
```

see file permissions below
```
$ ls -l /usr/games/lib/nethackdir/
-rw-r--r-- 1 root root     4875 Feb 17 16:50 license
-rw------- 1 root root        0 Feb 17 16:50 logfile
-rwxr-xr-x 1 root root 11456856 Feb 17 16:50 nethack
-rw-r--r-- 1 root root  1383064 Feb 17 16:50 nhdat
-rw------- 1 root root        0 Feb 17 16:50 perm
-rw------- 1 root root        0 Feb 17 16:50 record
-rwxr-xr-x 1 root root    34112 Feb 17 16:50 recover
drwxr-xr-x 2 root root     4096 Feb 17 16:50 save
-rw-r--r-- 1 root root    16756 Feb 17 16:50 symbols
-rw------- 1 root root     5718 Feb 17 16:50 sysconf
-rw------- 1 root root        0 Feb 17 16:50 xlogfile
```

I'm no expert, so I ran ...
```
$ sudo chmod 660 record #600
$ sudo chmod 644 sysconf #600
$ sudo chmod 666 perm #600
```

But still getting `cannot creat lock file (alock.0).` issue. 
I'm not clever enough to figure it out, so I guess I'll just change the file permissions back and run nethack as sudo
From looking at https://nethackwiki.com/wiki/Compiling seems like I'm supposed to change `CHOWN=true` or `CHGRP=true` in `<$top>/sys/unix/hints/linux`
