### ISSUE TITLE
The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found.

### ISSUE THREAD

**Issue by alysdexia** [NetHack/NetHack#181]
To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

(In Visual Studio 2019) retargetting (Upgrade to v142, No upgrade), rebuilding, and building don't work.  I already spent hours downloadan/installan the newest 1.7GB version; do I really need to instal the 2017?  It wants 3.2 GB.

**Comment by paulwinner** [comment]
Aside from any other considerations, the license information on MSDN makes
it pretty clear that we are not allowed to distribute the build tools. We
don't generally supply and specific non-game required compiler related
files.

Paul

**Comment by nhmall** [comment]
You can use the projects and solution files from vs2017 in win\win32\vs2017\NetHack.sln with Visual Studio 2019, but you may have to retarget the projects as follows:
    Windows SDK Version: 10.0.17763.0  [ There have been some reports of 
                                         difficulties if you instead choose 
                                         "10.0 (latest installed version)" ]
    Platform Toolset: Upgrade to v142

**Comment by alysdexia** [comment]
@nhmall I already tried that!

@paulwinner I didn't ask for that.

**Comment by paxed** [comment]
Hard to help without knowing the error message you get, but are you sure you have the compiler, cl.exe, installed? Visual Studio 2015 and above doesn't install it by default, you have to explicitly install the C++ programming language in the setup.

**Comment by alysdexia** [comment]
Why the fuck is everyone here so retarded?!  My subject line and first block of the comment _are_ the error message!

I gave the file sizes of the package with C++ included.

After my first comment I downloaded 2017 and compiled NH anyway.

**Comment by paxed** [comment]
So you fixed the "problem" yourself few hours later after reporting the "issue" by doing exactly what the "error" message said, and then get pissy when people who don't even use Visual Studio try to help? Perhaps the issue here isn't what you wrote in your issue.

**Comment by alysdexia** [comment]
How can they help if they don't use Visual Studio?

This is the output from nhmall's suggestion:
```1>------ Build started: Project: recover, Configuration: Debug x64 ------
2>------ Build started: Project: NetHackW, Configuration: Debug x64 ------
1>recover.obj : error LNK2019: unresolved external symbol setgid referenced in function main
1>recover.obj : error LNK2019: unresolved external symbol getgid referenced in function main
1>recover.obj : error LNK2019: unresolved external symbol setuid referenced in function main
1>C:\Users\move\games\roguelikes\NetHack-NetHack-3.6.2-beta01\win\win32\vs2017\..\..\..\bin\Debug\x64\recover.exe : fatal error LNK1120: 3 unresolved externals
1>Done building project "recover.vcxproj" -- FAILED.
3>------ Build started: Project: NetHack, Configuration: Debug x64 ------
2>options.obj : error LNK2019: unresolved external symbol curses_read_attrs referenced in function parseoptions
2>options.obj : error LNK2019: unresolved external symbol curses_fmt_attrs referenced in function get_compopt_value
2>windows.obj : error LNK2001: unresolved external symbol chainin_procs_init
2>windows.obj : error LNK2001: unresolved external symbol chainin_procs_chain
2>windows.obj : error LNK2001: unresolved external symbol chainout_procs_init
2>windows.obj : error LNK2001: unresolved external symbol chainout_procs_chain
2>windows.obj : error LNK2001: unresolved external symbol trace_procs_init
2>windows.obj : error LNK2001: unresolved external symbol trace_procs_chain
2>windows.obj : error LNK2001: unresolved external symbol curses_procs
2>windows.obj : error LNK2001: unresolved external symbol chainin_procs
2>windows.obj : error LNK2001: unresolved external symbol chainout_procs
2>windows.obj : error LNK2001: unresolved external symbol trace_procs
2>C:\Users\move\games\roguelikes\NetHack-NetHack-3.6.2-beta01\win\win32\vs2017\..\..\..\bin\Debug\x64\NetHackW.exe : fatal error LNK1120: 12 unresolved externals
2>Done building project "NetHackW.vcxproj" -- FAILED.
3>options.obj : error LNK2019: unresolved external symbol curses_read_attrs referenced in function parseoptions
3>options.obj : error LNK2019: unresolved external symbol curses_fmt_attrs referenced in function get_compopt_value
3>vision.obj : error LNK2019: unresolved external symbol vis_tab_init referenced in function vision_init
3>vision.obj : error LNK2001: unresolved external symbol close_table
3>vision.obj : error LNK2001: unresolved external symbol far_table
3>windows.obj : error LNK2001: unresolved external symbol chainin_procs_init
3>windows.obj : error LNK2001: unresolved external symbol chainin_procs_chain
3>windows.obj : error LNK2001: unresolved external symbol chainout_procs_init
3>windows.obj : error LNK2001: unresolved external symbol chainout_procs_chain
3>windows.obj : error LNK2001: unresolved external symbol trace_procs_init
3>windows.obj : error LNK2001: unresolved external symbol trace_procs_chain
3>windows.obj : error LNK2001: unresolved external symbol curses_procs
3>windows.obj : error LNK2001: unresolved external symbol chainin_procs
3>windows.obj : error LNK2001: unresolved external symbol chainout_procs
3>windows.obj : error LNK2001: unresolved external symbol trace_procs
3>C:\Users\move\games\roguelikes\NetHack-NetHack-3.6.2-beta01\win\win32\vs2017\..\..\..\bin\Debug\x64\NetHack.exe : fatal error LNK1120: 15 unresolved externals
3>Done building project "NetHack.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 11 up-to-date, 0 skipped ==========
```

**Comment by nhmall** [comment]
NetHack-3.6.2-beta01  commit 7088247883bcc3483ad45d97cba43e47604c1699 builds fine under vs2019  (when no edits are done to any distributed NetHack source files anyway).

The output from the post above would seem to indicate that, at the very least, SECURE and WINCHAIN and CURSES_GRAPHICS got defined somehow. Maybe that was done via edits to include/config.h or through some other user action, but many of those should not be defined under a Windows build.

Here's a log of a successful project retarget and NetHack build using vs2019.

Upgrading project 'NetHackW'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'dgncomp'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'dlb'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'levcomp'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'makedefs'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'recover'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'tile2bmp'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'tilemap'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'uudecode'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'NetHack'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'nhdefkey'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'nh340key'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'nhraykey'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Upgrading project 'PDCurses'...
	Configuration 'Debug|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Debug|x64': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|Win32': changing Platform Toolset to 'v142' (was 'v141').
	Configuration 'Release|x64': changing Platform Toolset to 'v142' (was 'v141').
Retargeting End: 14 completed, 0 failed, 0 skipped

1>------ Build started: Project: makedefs, Configuration: Debug Win32 ------
2>------ Build started: Project: recover, Configuration: Debug Win32 ------
3>------ Build started: Project: PDCurses, Configuration: Debug Win32 ------
1>makedefs.c
1>monst.c
2>recover.c
1>objects.c
1>Generating Code...
2>recover.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\bin\Debug\Win32\recover.exe
1>makedefs.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\makedefs.exe
4>------ Build started: Project: levcomp, Configuration: Debug Win32 ------
5>------ Build started: Project: uudecode, Configuration: Debug Win32 ------
6>------ Build started: Project: nhdefkey, Configuration: Debug Win32 ------
7>------ Build started: Project: nh340key, Configuration: Debug Win32 ------
4>No Lex using pre-built files
4>No Yacc using pre-built files
5>uudecode.c
6>nhdefkey.c
4>alloc.c
4>decl.c
4>drawing.c
4>lev_lex.c
7>nh340key.c
4>lev_main.c
4>lev_yacc.c
4>monst.c
6>   Creating library C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\nhdefkey.lib and object C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\nhdefkey.exp
4>objects.c
4>panic.c
4>Generating Code...
5>uudecode.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\uudecode.exe
7>   Creating library C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\nh340key.lib and object C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\nh340key.exp
6>nhdefkey.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\bin\Debug\Win32\nhdefkey.dll
8>------ Build started: Project: nhraykey, Configuration: Debug Win32 ------
8>nhraykey.c
7>nh340key.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\bin\Debug\Win32\nh340key.dll
8>   Creating library C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\nhraykey.lib and object C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\nhraykey.exp
8>nhraykey.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\bin\Debug\Win32\nhraykey.dll
4>levcomp.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\levcomp.exe
9>------ Build started: Project: tile2bmp, Configuration: Debug Win32 ------
9>decl.c
9>drawing.c
9>monst.c
9>objects.c
9>tile2bmp.c
9>tiletext.c
9>Generating Code...
9>tilemap.c
9>tile2bmp.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\tile2bmp.exe
9>Total of 1476 tiles written to tiles.bmp.
10>------ Build started: Project: dgncomp, Configuration: Debug Win32 ------
10>No Lex using pre-built files
10>No Yacc using pre-built files
10>alloc.c
10>dgn_lex.c
10>dgn_main.c
10>dgn_yacc.c
10>panic.c
10>Generating Code...
10>dgncomp.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\dgncomp.exe
11>------ Build started: Project: dlb, Configuration: Debug Win32 ------
12>------ Build started: Project: tilemap, Configuration: Debug Win32 ------
11>alloc.c
11>dlb.c
11>dlb_main.c
12>tilemap.c
11>panic.c
11>Generating Code...
12>tilemap.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\tilemap.exe
11>dlb.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\tools\Debug\Win32\dlb.exe
13>------ Build started: Project: NetHackW, Configuration: Debug Win32 ------
14>------ Build started: Project: NetHack, Configuration: Debug Win32 ------
13>allmain.c
14>allmain.c
13>alloc.c
14>alloc.c
14>apply.c
13>apply.c
13>artifact.c
14>artifact.c
14>attrib.c
13>attrib.c
14>ball.c
13>ball.c
14>bones.c
13>bones.c
13>botl.c
14>botl.c
14>cmd.c
13>cmd.c
14>dbridge.c
13>dbridge.c
14>decl.c
13>decl.c
14>detect.c
13>detect.c
13>dig.c
14>dig.c
13>display.c
14>display.c
13>dlb.c
14>dlb.c
13>do.c
14>do.c
13>dog.c
14>dog.c
14>dogmove.c
13>dogmove.c
13>dokick.c
14>dokick.c
14>dothrow.c
13>dothrow.c
14>Generating Code...
13>Generating Code...
14>Compiling...
13>Compiling...
13>do_name.c
14>do_name.c
14>do_wear.c
13>do_wear.c
14>drawing.c
13>drawing.c
14>dungeon.c
13>dungeon.c
14>eat.c
13>eat.c
13>end.c
14>end.c
14>engrave.c
13>engrave.c
14>exper.c
13>exper.c
13>explode.c
14>explode.c
13>extralev.c
14>extralev.c
13>files.c
14>files.c
13>fountain.c
14>fountain.c
13>hack.c
14>hack.c
13>hacklib.c
14>hacklib.c
13>invent.c
14>invent.c
13>isaac64.c
13>light.c
14>isaac64.c
14>light.c
13>lock.c
14>lock.c
13>mail.c
13>makemon.c
14>mail.c
14>makemon.c
13>Generating Code...
14>Generating Code...
13>Compiling...
13>mapglyph.c
13>mcastu.c
14>Compiling...
14>mapglyph.c
14>mcastu.c
13>mhitm.c
14>mhitm.c
13>mhitu.c
14>mhitu.c
13>minion.c
14>minion.c
13>mklev.c
14>mklev.c
13>mkmap.c
13>mkmaze.c
14>mkmap.c
14>mkmaze.c
13>mkobj.c
14>mkobj.c
13>mkroom.c
13>mon.c
14>mkroom.c
14>mon.c
13>mondata.c
13>monmove.c
14>mondata.c
14>monmove.c
13>monst.c
13>mplayer.c
14>monst.c
13>mthrowu.c
14>mplayer.c
13>muse.c
14>mthrowu.c
14>muse.c
13>music.c
13>objects.c
14>music.c
13>objnam.c
14>objects.c
14>objnam.c
13>Generating Code...
14>Generating Code...
13>Compiling...
13>options.c
14>Compiling...
14>options.c
13>o_init.c
13>pager.c
14>o_init.c
13>pickup.c
14>pager.c
13>pline.c
14>pickup.c
13>polyself.c
14>pline.c
14>polyself.c
13>potion.c
14>potion.c
13>pray.c
14>pray.c
13>priest.c
14>priest.c
13>quest.c
14>quest.c
13>questpgr.c
14>questpgr.c
13>read.c
14>read.c
13>rect.c
13>region.c
14>rect.c
13>restore.c
14>region.c
14>restore.c
13>rip.c
13>rnd.c
13>role.c
14>rip.c
14>rnd.c
13>rumors.c
14>role.c
13>save.c
14>rumors.c
13>Generating Code...
14>save.c
14>Generating Code...
13>Compiling...
13>shk.c
13>shknam.c
14>Compiling...
14>shk.c
13>sit.c
14>shknam.c
13>sounds.c
14>sit.c
13>spell.c
14>sounds.c
13>sp_lev.c
14>spell.c
13>steal.c
14>sp_lev.c
13>steed.c
13>sys.c
14>steal.c
13>teleport.c
14>steed.c
14>sys.c
13>tile.c
14>teleport.c
13>timeout.c
14>tile.c
13>topten.c
14>timeout.c
13>track.c
13>trap.c
14>topten.c
14>track.c
13>uhitm.c
14>trap.c
13>u_init.c
14>uhitm.c
13>vault.c
14>u_init.c
13>version.c
13>vision.c
14>vault.c
14>version.c
13>Generating Code...
14>vision.c
14>Generating Code...
13>Compiling...
13>vis_tab.c
13>weapon.c
13>were.c
14>Compiling...
14>weapon.c
13>wield.c
14>were.c
13>windows.c
14>wield.c
13>wizard.c
14>windows.c
13>worm.c
14>wizard.c
13>worn.c
14>worm.c
13>write.c
14>worn.c
13>zap.c
14>write.c
13>nhlan.c
14>zap.c
13>random.c
14>nhlan.c
13>ntsound.c
14>random.c
14>ntsound.c
13>windmain.c
14>nttty.c
13>winnt.c
14>windmain.c
13>win10.c
14>winnt.c
13>safeproc.c
14>safeproc.c
13>mhaskyn.c
14>getline.c
14>topl.c
14>wintty.c
14>Generating Code...
13>mhdlg.c
13>mhfont.c
13>Generating Code...
13>Compiling...
13>mhinput.c
13>mhmain.c
14>cppregex.cpp
13>mhmap.c
13>mhmenu.c
13>mhmsgwnd.c
13>mhrip.c
14>stubs.c
13>mhsplash.c
13>mhstatus.c
13>mhtext.c
13>mswproc.c
13>winhack.c
13>Generating Code...
14>NetHack.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\bin\Debug\Win32\NetHack.exe
13>cppregex.cpp
13>stubs.c
13>NetHackW.vcxproj -> C:\nethack-362\win\win32\vs2017\..\..\..\bin\Debug\Win32\NetHackW.exe
========== Build: 14 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by paulwinner** [comment]
We try to help based on experience with other compilers, and email
exchanges with other users who we interact with. Every single one of us is
a completely unpaid volunteer. People volunteer with coding to keep the
game going for over 25 year. People volunteer to test. People volunteer to
assist users who are having difficulties.I'm sorry that in the case of your
issue we weren't up to your expectations.

**Comment by bsimser** [comment]
Not re-opening this but re-targeting didn't seem to be working for me. Even after re-targeting individual projects or the entire solution (and multiple load/reload/reset of the solution) I found that changing V141 to V142 manually in the following files to work and produce a clean build under VS2019: default.props, default_dll.props, default_lib.props. Hope that helps.
