### ISSUE TITLE
Wand of Digging in Shop

### ISSUE THREAD

**Issue by ab5ni** [NetHack/NetHack#189]
Was in a shop, playing an Archeologist, an orc walks in, and he's standing just past the door; that is, on the spot where u can pick stuff up for free. Well, now that I think about it, he might have been standing on the door. Not really sure and don't remember exactly..

Anywho, I hit him twice with a pickaxe, he zaps the wand downward and falls through. I walk over the hole, and the game crashes straight to the desktop. All this was done running 3.6.2 (latest beta) under Winblows 10. Hope this helps.

**Comment by ab5ni** [comment]
Actually, I started to play a new game, and the program asked me if I wanted to restore my previous game, which is the one that crashed to the desktop. I said yes, and the orc actually dug the hole right on top of the door.

**Comment by paxed** [comment]
Does paniclog show anything? It should be in the same folder as the nethack exe.

**Comment by ab5ni** [comment]
Yeah. Here's what it said:
    3.6.2-0 20190503 134159 1 -: impossible obfree: not on bill??

After I restored the game and moved around a bit in the shop (mine town), the game restored the door, and then I could finally get out of that damn place :D. OTOH, while that dug hole remained at the door location, it was crash straight to the desktop.

**Comment by nhmall** [comment]
Do you still have a copy of the saved game from before you went through the hole?
If you do, could you drag and drop a zipped copy of it here?

**Comment by ab5ni** [comment]
Sorry, but I no longer have a copy of the saved file :/.
    On Friday, May 10, 2019, 9:42:06 AM CDT, nhmall <notifications@github.com> wrote:  
 
 
Do you still have a copy of the saved game from before you went through the hole?
If you do, could you drag and drop a zipped copy of it here?

**Comment by ab5ni** [comment]
I'm not familiar with the codebase (at all), but if I was to guess what's going on here (from the paniclog file), it might have something to do with the door being replaced by a hole, and when u fall through, it's trying to free up some memory that was initially allocated for the door, but that pointer(?) has been stomped on by the hole code. (Shrug.)

**Comment by nhmall** [comment]
3.6.2 report, no reports to date in current release code 3.6.6
