### ISSUE TITLE
Floppy Disk Support

### ISSUE THREAD

**Issue by aryker** [NetHack/NetHack#207]
It states in the [release notes for 3.6.2](https://www.nethack.org/v362/release.html) that floppy disk support for all platforms will be dropped from the next major release unless someone offers to maintain it. I might be willing to do that. What would the dev team need from me in that case?

**Comment by Xaleth** [comment]
Since no one has responded yet, @aryker you should read the README for the current dev source and go from there for cross-compilation. You could also go through the code and optimize it for size to fit in the tiny 1.44 MB window of floppy disks. 

Go for it. :)

**Comment by aryker** [comment]
Thanks @Xaleth . If anyone wants to assign this issue to me, feel free.
