### ISSUE TITLE
Missing articles from curses perm_invent 

### ISSUE THREAD

**Issue by Luxidream** [NetHack/NetHack#212]
The missing articles in perm_invent are inconsistent with the inventory screen. Default menucolors on many public servers no longer work in perm_invent and players need a separate set of menucolors to use for specifically for it. The missing articles should be an option or removed because it’s a hindrance for most players and removing the articles doesn’t free up much space anyway.

**Comment by nhmall** [comment]
Is this adequately fixed by this commit?
https://github.com/NetHack/NetHack/commit/e9aac25922226dccc87da6652b998edbe33b2d1d
