### ISSUE TITLE
Travis builds for QT5 and X11 appear to be broken.

### ISSUE THREAD

**Issue by ostrosablin** [NetHack/NetHack#214]
Pull Request #213 has failed two checks, but they both seem to be an environment misconfig.

X11 has failed due to missing headers (X11/Xaw/Cardinals.h), which should come from libxaw-dev package.

QT5 has failed because of missing tools (bdftopcf), which should be available for Ubuntu from xfonts-utils package.

So it appears that some packages are missing from Travis build config, and this is not a problem with pull request.

**Comment by ostrosablin** [comment]
nhmall fixed this in d1bc65b75bc6d421e45935e253851a97650cbb10

**Comment by nhmall** [comment]
This was related to Travis CI change to use Ubuntu Xenial 16.04 as the default Travis CI build environment.
