### ISSUE TITLE
'That seemed remarkably uneventful' message can appear at odd times.

### ISSUE THREAD

**Issue by AndrioCelos** [NetHack/NetHack#244]
This was discovered by kcostell during TNNT, when a hell hound breathed fire over some water, confusing the player. It seems like the message was supposed to be related to player actions only...
https://github.com/NetHack/NetHack/blob/2170b9946b9d3281bc425dc892cb881c92c66e8f/src/zap.c#L4446

**Comment by nhmall** [comment]
Quite right. This should be fixed in 
https://github.com/NetHack/NetHack/commit/c2bbbebd8eddc544207fce6e62118568ad254f82
