### ISSUE TITLE
Build fail on Gentoo

### ISSUE THREAD

**Issue by lucasmr** [NetHack/NetHack#258]
$ sh sys/unix/setup.sh sys/unix/hints/linux
$ make

During linking:

Linking nethack.
cc -rdynamic -o nethack monst.o objects.o allmain.o alloc.o apply.o artifact.o attrib.o ball.o bones.o botl.o cmd.o dbridge.o decl.o detect.o dig.o display.o dlb.o do.o do_name.o do_wear.o dog.o dogmove.o dokick.o dothrow.o drawing.o dungeon.o eat.o end.o engrave.o exper.o explode.o extralev.o files.o fountain.o hack.o hacklib.o invent.o isaac64.o light.o lock.o mail.o makemon.o mapglyph.o mcastu.o mhitm.o mhitu.o minion.o mklev.o mkmap.o mkmaze.o mkobj.o mkroom.o mon.o mondata.o monmove.o mplayer.o mthrowu.o muse.o music.o o_init.o objnam.o options.o pager.o pickup.o pline.o polyself.o potion.o pray.o priest.o quest.o questpgr.o read.o rect.o region.o restore.o rip.o rnd.o role.o rumors.o save.o shk.o shknam.o sit.o sounds.o sp_lev.o spell.o sys.o steal.o steed.o teleport.o timeout.o topten.o track.o trap.o u_init.o uhitm.o vault.o vision.o vis_tab.o weapon.o were.o wield.o windows.o wizard.o worm.o worn.o write.o zap.o posixregex.o  ioctl.o unixmain.o unixtty.o unixunix.o unixres.o getline.o termcap.o topl.o wintty.o cursmain.o curswins.o cursmisc.o cursdial.o cursstat.o cursinit.o cursmesg.o cursinvt.o  version.o -lcurses -lncurses 
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: cursmain.o: undefined reference to symbol 'keypad'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /lib64/libtinfo.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

ncurses-6.1_p20181020 is installed.

**Comment by ostrosablin** [comment]
I believe, under Gentoo, libtinfo is splitted from libncurses, so you should you should link with -ltinfo.

Try setting

`WINTTYLIB = -ltinfo`

Or

`WINTTYLIB = -lncurses`

Should help.

**Comment by lucasmr** [comment]
-ltinfo solved it, thanks.

**Comment by winny-** [comment]
I recommend dropping in a  `pkg-config --libs ncurses` in your local patchset. This is what the official Gentoo ebuild does as well. https://github.com/gentoo/gentoo/blob/master/games-roguelike/nethack/nethack-3.6.1.ebuild#L52
