### ISSUE TITLE
Stormbringer heals you when wielded by pets

### ISSUE THREAD

**Issue by Tomsod** [NetHack/NetHack#275]
Something I noticed while source-diving: life-draining artifacts are not handled correctly in inter-monster combat.  The defending monster will lose HP from life drain, but the attacking monster will not be healed by this; instead, player's health will be restored.

The problem lies in `artifact_hit()`:
https://github.com/NetHack/NetHack/blob/d7e3331129221377e5eb17f4f1b797c5c11053ab/src/artifact.c#L1358-L1363
The quoted code is reached when a non-player monster is drained.  It calls `healup()` (which heals the player) without checking who is the attacking monster.

One way to experience this bug is to give your chaotic pet (e.g. a balrog) the Stormbringer, damage yourself a bit, and notice as your HP spikes when the pet hits anything.  The Staff of Aesculapius is also subject to this bug, but most monsters won't wield it, so the most likely scenario is a pacifist Healer having their per fight Cyclops.

**Comment by AmyBSOD** [comment]
Since basically all variants are affected by this, I made a fix for mine: https://github.com/SLASHEM-Extended/SLASHEM-Extended/commit/e0b97af1d3 - should be easy to port over :) With this fix, monsters who wield level-draining artifacts will properly fill up their own health upon landing a hit.
