### ISSUE TITLE
You slip the leash around your Bill's gnome mummy

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#297]
When applying a leash to a named pet mummy or zombie, you receive feedback similar to _'You slip the leash around your Bill's gnome mummy'._ I tested a few other monsters, such as vampires and regular gnomes, the feedback was normal (You slip the leash around your vampire lord called Phil).

**Comment by nhmall** [comment]
tested and got "You slip the leash around your gnome mummy called Bill."

That was with the following steps in c234f5a97d1d88712a71e8fa1a9714960838bd13:
1. ^G wiz-creating a gnome mummy.
2. (C)alled the gnome mummy "Bill" without the quotes.
3. ^W wiz-wished for a blessed scroll of taming.
4. Read the scroll of taming beside Bill.
5. ^W wiz-wished for a leash.
6. (a)pplying the leash towards Bill.

Do you have steps to reproduce the result you are reporting?

**Comment by k21971** [comment]
My apologies, this isn't a vanilla issue. Closing this issue.
