### ISSUE TITLE
Condition aliases (condition_aliases) needs updating for new statuses

### ISSUE THREAD

**Issue by ostrosablin** [NetHack/NetHack#299]
const struct condmap condition_aliases[]

Obviously, warrants update. For instance, new Submerged status could be classified as Major trouble for status hiliting purposes, as it could kill player's hero in 1 turn.

**Comment by nhmall** [comment]
Yes, there are further updates to follow for aliases.
Although submerged, specifically, is currently set to opt_in and didn't have a status marker in the past.

**Comment by ostrosablin** [comment]
{ "opt_in",         BL_MASK_BAREH | BL_MASK_BLIND | BL_MASK_BUSY

This line (botl.c:535) seems wrong. **BL_MASK_BLIND** is not opt_in, there's 13 opt-in statuses, but 14 in opt_in alias. Probably a copy-paste mistake.

**Comment by nhmall** [comment]
fixed in https://github.com/NetHack/NetHack/commit/7421c989e592c4bf09306266d35b2eacc20c7c98 which should be pushed in a short while.
