### ISSUE TITLE
Can't levelport down from quest home in wizard mode

### ISSUE THREAD

**Issue by copperwater** [NetHack/NetHack#301]
Attempting to levelport down gives "A mysterious force prevents you from descending. You materialize on a different level!"

After receiving the quest, the wizard-mode character can levelport down normally.

**Comment by AndrioCelos** [comment]
Commit 158ea1a23f96097548c345baf45193f8aff5c104 fixes the message issue. In wizard mode, you can override the restrictions on starting the quest: you can set your alignment record to 20 by talking to the leader, and use `#levelchange` to raise your level to at least 14,

**Comment by copperwater** [comment]
Was indeed fixed.
