### ISSUE TITLE
Paranoid pray prompt not paranoid enough

### ISSUE THREAD

**Issue by Anerag** [NetHack/NetHack#303]
I would like to have the option to make `paranoid_confirmation:pray` require the player to type `yes` rather than just `y`. Out of all the paranoid prompts, why is prayer the only one that doesn't require an explicit `yes`?

In a recent game, I was repeatedly sacrificing corpses and praying for favors, something like
`#offer y #offer y #offer y ... #pray y #offer y #offer y ...`
Then, by mistake I prayed twice in a row and lost over 30 points of intrinsic protection. Since sacrifice asks for confirmation as well it's very easy to accidentally pray instead.

The quick and easy solution would of course be
```
diff --git a/src/pray.c b/src/pray.c
index b098311d4..9c8c41188 100644
--- a/src/pray.c
+++ b/src/pray.c
@@ -1846,7 +1846,7 @@ int
 dopray()
 {
     /* Confirm accidental slips of Alt-P */
-    if (ParanoidPray && yn("Are you sure you want to pray?") != 'y')
+    if (!paranoid_query(ParanoidPray, "Are you sure you want to pray?"))
         return 0;
 
     u.uconduct.gnostic++;
```
However that would likely annoy most people who are used to just hitting `y`.

**Comment by paranoidtimes** [comment]
Pray stands out among the paranoid options. Where most of them allow a 'yes' vs 'no' or fall back to y/n. Praying gives a y/n or no confirmation. #371 should get it in line with the other paranoid options, though are there any thoughts on why it is different to begin with?
