### ISSUE TITLE
Minuscule typo

### ISSUE THREAD

**Issue by ghost** [NetHack/NetHack#315]
> [the whole baroque edifice or wizardry](https://github.com/NetHack/NetHack/blob/e81f761969b4fbb649932a63499ea6ced0d25b7f/dat/tribute#L2383)

Shouldn't it say "the whole baroque edifice of wizardry"?

**Comment by nhmall** [comment]
fixed in https://github.com/NetHack/NetHack/commit/ade91fd1192d31a97925d5cd3aa2d7a2b6c3634c

**Comment by ghost** [comment]
https://github.com/NetHack/NetHack/blob/e81f761969b4fbb649932a63499ea6ced0d25b7f/dat/tribute#L5587

Change "starts" to "stars"?
