### ISSUE TITLE
Use #save displayed cannot open save file.

### ISSUE THREAD

**Issue by zixijian** [NetHack/NetHack#327]
The environment is:
Android Termux nethack 3.6.6.

**Comment by paxed** [comment]
Android is not a system we support - If you're using GurrHack's NetHack-Android, please file an issue with https://github.com/gurrhack/NetHack-Android/ If you've compiled NetHack on Android yourself, please try to debug it yourself.

**Comment by zixijian** [comment]
Termux is an advanced terminal emulator on Android. I don't know who sent the nethack to the software warehouse.
In fact, I have also tried to compile it myself, but I am not very good at C language. But I know that part of the environment path of termux is not the same with Complete unix system. If I can know what #save did when saving, I might solve this problem.
```
[~]$ apt show nethack
Package: nethack
Version: 3.6.6
Maintainer: Leonid Plyushch <leonid.plyushch@gmail.com> @xeffyr
Installed-Size: 7664 kB
Depends: gzip, ncurses
Homepage: http://www.nethack.org/
Download-Size: 2262 kB
APT-Manual-Installed: yes
APT-Sources: https://dl.bintray.com/grimler/game-packages-24 games/stable aarch64 Packages
Description: Dungeon crawl game
```

**Comment by paxed** [comment]
Well, there's the package maintainer email, so you should file a bug with them?

**Comment by zixijian** [comment]
> Well, there's the package maintainer email, so you should file a bug with them?

oh,i forgot this,thank you.

And i found a way to compile nethack in termux,now save being normal.
but termux using flex and bison,and flex replace lex.
