### ISSUE TITLE
Compatibility with MAC OS 10.11.6 is broken

### ISSUE THREAD

**Issue by jrfnl** [NetHack/NetHack#33]
Hi all,

Reporting this for a friend of mine. If you have any questions regarding the report, I'll pass them on & report back.

> I have been addicted to this game for the past thirty years. Love it!
> Unfortunately, while it does run on MAC OS 10.11.6, it no longer allows me to save the game.
> Anyone know of a solution other than buying a second old laptop ?

**Comment by dom96** [comment]
Here is a simple solution:

```
ssh nethack@alt.org
```

**Comment by jrfnl** [comment]
Hi @dom96, thank you for your quick response! My friend tried it and I then found out he was actually using a fork of the game (Nethack-cacao) :confused: 

I'll see if I can find the code base for that version to ask there.

Sorry for the confusion.
