### ISSUE TITLE
Giant ants sometimes appear in barracks

### ISSUE THREAD

**Issue by Tomsod** [NetHack/NetHack#335]
Something I noticed: in addition to mercenaries, barracks are often populated with one or two giant ants, especially in the Castle.  I used to think they were replacing extinct soldiers, but there's actually a subtle bug at work.

The bug was introduced in 3.6.0; while before the Yendorian Army definitions in `monst.c` were contiguous, now nurses are placed between sergeants and lieutenants:
https://github.com/NetHack/NetHack/blob/ca4e72921602c8756e30e27da632c677e73dce2a/src/monst.c#L2245-L2278
This breaks some of the barracks code in `mkroom.c`, which assumes that mercenaries are contiguous:
https://github.com/NetHack/NetHack/blob/ca4e72921602c8756e30e27da632c677e73dce2a/src/mkroom.c#L783-L791
Since `PM_CAPTAIN - PM_SOLDIER + 1` no longer equals the number of soldier types, `squadprob` quietly acquires one extra zero-initialized element.  As monster number zero is the giant ant, this sometimes leads to giant ants being chosen as barracks monsters.  This only happens on deeper dungeon levels, as ants have a probability of 0, and can only be chosen through this fallback code:
https://github.com/NetHack/NetHack/blob/ca4e72921602c8756e30e27da632c677e73dce2a/src/mkroom.c#L809
Thus, the Castle is the best place to view this bug in action.

**Comment by copperwater** [comment]
The nurse's placement also appears to break the assumption in makemon.c that monsters within a class are presented in ascending order of difficulty. Nurse (13) is placed before lieutenant (12). From what I can tell, this might mean that all nurse-or-stronger monsters have a bias against being randomly generated (at least for mkclass(S_HUMAN)) when the current difficulty cap is 12 or under.

Of note, there's a comment right below the captain's definition that states this exact thing - "some of the mkroom code assumes that all the soldiers are contiguous".

I'm not sure how exactly to reconcile the fact that certain groups of S_HUMAN monsters need to be kept together logically with the assumption in mkclass that they follow a strict difficulty order. To fix this particular problem, NSTYPES can just be defined to 4, probably, but that doesn't address the larger issue.
