### ISSUE TITLE
Ring/amulet hunger is double-counted when attacking monsters in melee on certain turns

### ISSUE THREAD

**Issue by copperwater** [NetHack/NetHack#336]
Melee combat is intended to incur additional hunger loss, where attack() calls overexertion() which calls gethungry(). However, gethungry() applies ring and amulet hunger penalties no matter where it's called from. This means that if the player attacks a monster on a turn that would normally incur these penalties, they are penalized for it twice: once when the turn ticks up normally, and once when they make the attack.

If the player has extra speed giving them multiple actions per turn, this can incur triple or quadruple penalties as well if they choose to use those extra actions attacking.

This can be tested easily by inspecting the value of u.uhunger before and after making an attack when the displayed turn is one that would cause additional jewelry hunger (e.g. making an attack on turn 44 while wearing a ring on the left hand).

**Comment by AndrioCelos** [comment]
Wouldn't this still consume 1 extra nutrition point per ring and amulet per 20 attacks on average?
