### ISSUE TITLE
Suppress giant spiders in early spider rooms.

### ISSUE THREAD

**Issue by AndrioCelos** [NetHack/NetHack#356]
The spider room was imported from UnNetHack, along with several other features. Commits https://github.com/UnNetHack/UnNetHack/commit/2a97cbfff59c66b0428bf9505d9a3c74e26d712f and https://github.com/UnNetHack/UnNetHack/commit/d00a0a656e2821796f72833b667e38e67728de3c has since changed them so that cave spiders generate in these rooms instead of giant spiders if they occur before webs can normally be generated. I propose making a similar change to vanilla spider rooms so that early adventurers won't get mauled by a large pack of out-of-depth giant spiders.

Either make the same change as UnNetHack, or replace the giant spider generated on a web with a cave spider if giant spiders are out of depth, similar to the change to shriekers summoning purple worms. It may be worth allowing cave spiders to occasionally generate on webs at any depth, also.

**Comment by copperwater** [comment]
See also pull request #344, which would allow the DevTeam to specify that a spider room cannot generate above a certain dungeon level. Even a single cave spider (difficulty 3) is above normal difficulty for dungeon level 1, and a swarm of them will be even tougher.

**Comment by RojjaCebolla** [comment]
feels like public alpha content!

**Comment by copperwater** [comment]
> feels like public alpha content!

I don't know what you mean by this. Do you think it should be left as-is for now and only fixed late into the development cycle for... reasons? This is a really unpopular element of the game right now and 3.7's getting a bad rap from it. Why not fix it now?

Thought of another reason not to apply UnNetHack's approach, as Andrio described it, directly: it ties the spider room difficulty cutoff (the level at which all the cave spiders in a room can suddenly generate as giant spiders) to the magic number in mktrap.c that decides when web traps (and therefore a single giant spider) can generate, currently 7. The difficulty threshold for generating one giant spider should not do double duty as the threshold for generating a room full of giant spiders.

**Comment by RojjaCebolla** [comment]
oh, i mean the super OOD rooms (without your patch) feels like public alpha

**Comment by AndrioCelos** [comment]
To be fair, it kind of _is_ public alpha content.

**Comment by copperwater** [comment]
As of commit 999222a spider rooms no longer generate above level difficulty 10 (and still create giant spiders on every web, not doing anything with cave spiders). This issue can probably be closed.

**Comment by AndrioCelos** [comment]
The commit message says:

> This doesn't do anything to address the "Mausoleum" room problem, in
> which a master or arch-lich can generate and immediately warp out and
> attack the player. Even with a high difficulty threshold, it won't fix
> the problem of these liches generating out of their normal difficulty
> and Gehennom constraints.

That was already fixed in c29ffe1d823b338956de2517057b7e87ef64795e. `mkclass` no longer generates liches with the `G_HELL` flag (purple ones) outside Gehennom.
