### ISSUE TITLE
Sounds instead of messages

### ISSUE THREAD

**Issue by bramtayl** [NetHack/NetHack#361]
I'd like to be able to do something like this:

```
SOUND=MESG "You hear a gurgling noise\.|You hear a slow drip\." "sink.mp3" 100
MSGTYPE=hide "You hear a gurgling noise\.|You hear a slow drip\."
```

Unfortunately, it seems that hidden messages can't trigger sounds.

My general motivation is to try to remove as much of the text messages as possible and replace them with sounds. I think it would be a more convenient user experience. I've been downloading sounds from `freesound.org` and it seems like many of the sounds are permissively licensed. It might be nice to package sounds together with the gui versions? I could try to track them a bunch of sounds and check on the permissions if it would be helpful.

**Comment by nhmall** [comment]
Which platform are you currently using: Qt, Windows console, or Windows GUI?

**Comment by bramtayl** [comment]
I built Qt from source on master

**Comment by nhmall** [comment]
I can't test on Qt myself at the moment, but you could give this a shot...

[sound.txt](https://github.com/NetHack/NetHack/files/4860681/sound.txt)

**Comment by bramtayl** [comment]
Could you make a branch or PR that I could check out?

**Comment by bramtayl** [comment]
Also, thanks!

**Comment by nhmall** [comment]
try out the branch travis_test

**Comment by bramtayl** [comment]
Yes it worked! Thanks!
