### ISSUE TITLE
ALTMETA no longer recognized

### ISSUE THREAD

**Issue by entrez** [NetHack/NetHack#366]
The current NetHack 3.7 build doesn't seem to recognize `altmeta` as an option (at least on Unix systems), even if `ALTMETA` is explicitly `#define`d (as the in-game documentation still suggests: \`\`Boolean option for Amiga, or for others if ALTMETA was set at compile time''). 

Based on the results of `git bisect` the option seems to have been removed in commit 5a437b3, which I guess was intended to scrap some outdated `SYSFLAGS` code -- so maybe it was deliberate, but I wanted to bring it to your attention just in case!

**Comment by entrez** [comment]
This seems to be caused by the removal of these lines from [include/optlist.h](https://github.com/NetHack/NetHack/blob/5a437b336ae9957975ca4347446af702f3794406/include/optlist.h):
https://github.com/NetHack/NetHack/blob/e4b18f054587a329b0404927e60517bbb1321e64/include/optlist.h#L90-L96

Adding them back in to the current build re-enables `altmeta` as a recognized option.

**Comment by nhmall** [comment]
Thanks. It will be fixed later today.

**Comment by nhmall** [comment]
Closed in 2c571dcfe7208b7f1d0f48e21dda3ab9429b7a0e
