### ISSUE TITLE
Dungeon Creation Parameters?

### ISSUE THREAD

**Issue by apowers313** [NetHack/NetHack#381]
Are there parameters controlling random aspects of dungeons? (number of doors, door locked frequency, likelihood of hidden doors, frequency of traps, etc.)

If they aren’t already config options, where would I look to control those sorts of things?

**Comment by copperwater** [comment]
No, there are no configure options or even #define'd constants for these things. It's all just raw C and magic numbers. For random room-and-corridor level generation, most of the code lives in mklev.c. For door stuff specifically, look at `dosdoor()` and places where it's called from.

**Comment by apowers313** [comment]
Perfect! Thanks for the help :)
