### ISSUE TITLE
Famine mysteriously teleported to me

### ISSUE THREAD

**Issue by jillest** [NetHack/NetHack#423]
### Environment

eu.hardfought.org

### Description

On the Astral Plane, I went to the middle altar first, guarded by Death. The left altar was guarded by Pestilence and the right altar was guarded by Famine. I killed a few monsters at the second door, then teleported three monsters away at T:34271. After this, Famine suddenly appeared next to me, as if I tried to teleport Famine's corpse away (but that is not possible, since I had not killed Famine before).

I had quaffed a blessed potion of monster detection.

The full ttyrec is at https://eu.hardfought.org/userdata/j/jt/nethack/ttyrec/2020-12-12.23:51:17.ttyrec.gz .

This is the same game as where #422 happened; a server admin restored the game to a checkpoint after the crash.

**Comment by FredrIQ** [comment]
If a Rider is somehow teleported in any way, either by the player, or crossfire (an extreme edge case, since monsters basically never zap teleport at others), it will (almost) always teleport next to the player.

**Comment by amateurhourrrr** [comment]
this happened on a stream in a modified 3.7 (with setseed patch)
https://www.twitch.tv/videos/905001824?t=04h08m39s

**Comment by amateurhourrrr** [comment]
Previous link is broken, here's where it occurred in the archived link: https://youtu.be/dggAJiZM1Kc?t=14939

zapped teleport wand downwards, teleporting a player monster away, Death teleported from west to next to the player

setseed branch is based on vanilla commit 9e550ccb0

**Comment by entrez** [comment]
Spent some time today figuring this out after a character splatted on astral thanks to it...

`bhit` uses `g.bhitpos` to track the current 'tip' of the 'beam' sent out by the wand.  If it hits an object on the floor, the object gets teleported to another location and eventually `flooreffects` gets called on the object at its new spot.  `flooreffects` ALSO uses `g.bhitpos`, for a different reason, so it updates `g.bhitpos` to point to the new location that the object was teleported to.  Once control returns to `bhit`, the beam continues from there without being reset back to the old position.  If the teleported object lands in the right position near one of the riders, the beam will hit the rider and teleport them next to you.
