### ISSUE TITLE
Wizgenesis can cause segfault

### ISSUE THREAD

**Issue by entrez** [NetHack/NetHack#433]
When a specific monster class is specified for creation in `#wizgenesis` (^G), but all monsters of that class have been genocided or are extinct, a segfault will occur.

This happens in `create_particular_creation(read.c)`, because `whichpm` is defined as the result of `mkclass(d->monclass, 0)`. `mkclass(makemon.c)` can return `(struct permonst *) 0` if every monster in the class is deemed an invalid target by `mk_gen_ok`, but this isn't accounted for in `create_particular_condition`, which unconditionally inserts `whichpm` into the `is_male` and `is_female` macros. These macros attempt to deference the null pointer which causes the segfault.

https://github.com/NetHack/NetHack/blob/f30bb8aaa49d6338b9e076c6e1c30d972a9bbbcf/src/read.c#L2587-L2596

**Comment by nhmall** [comment]
fix is in the pipeline for later today, thanks.

**Comment by entrez** [comment]
Any thanks should be directed to the fuzzer; it seems to really enjoy entering `0t` into the `#wizgenesis` prompt. :^)
