### ISSUE TITLE
Orctown "aligned priest" corpse causes level file to be unusable

### ISSUE THREAD

**Issue by entrez** [NetHack/NetHack#434]
Because minetn-1.lua calls for a corpse of an 'aligned priest', but the male monster name is now 'priest' and the neuter monster name is now 'aligned cleric', the level fails to load and is replaced with a random maze. If the `montype` is changed to 'aligned cleric' (or 'priest' or 'priestess') this will be resolved.

https://github.com/NetHack/NetHack/blob/ef4efdb1256b8ef68d3009ac144817e46ef75ecd/dat/minetn-1.lua#L77-L78

**Comment by k21971** [comment]
I was just typing up a report to devteam. Beat me to it ;)

**Comment by k21971** [comment]
FYI this also affects Pri-loca.lua and astral.lua.

**Comment by nhmall** [comment]
fix is in the pipeline for later today
