### ISSUE TITLE
crashed 3.6.1 on NAO

### ISSUE THREAD

**Issue by kazcw** [NetHack/NetHack#44]
I was just playing 3.6.1-beta on NAO and I got the message "dmonsfree: 1 removed doesn't match 0 pending  Program in disorder - perhaps you'd better #quit.". I saved the game and tried to restart it, but got a message that the savefile was empty (and the prompt to start a new game) -- so I don't have much data on the conditions at the time of the error. It happened the first time I attacked something after polymorphing into a vampire lord (I drained a cross-aligned unicorn).

**Comment by FredrIQ** [comment]
Perhaps 263bd05fa0e0029eaa9d1e12ab49fd6d4e83faeb fixed this?

**Comment by kazcw** [comment]
Oh yes, I see they received my patch.
