### ISSUE TITLE
Expert fireball with telepathy (or not) while blind unable to select self

### ISSUE THREAD

**Issue by enetics-secker** [NetHack/NetHack#447]
When casting fireball at expert level a player is unable to select themselves as the target when blind whether they have telepathy or not.  They can, however, select another sentient target via telepathy within 10-squares.  

The message is "Your mind fails to lock onto that location!" which is the same as the message when you target an unoccupied location with telepathy or a location outside your field of view.

Since the player is sentient they should be able to target themselves when blind (or otherwise)

**Comment by bryceco** [comment]
Is this for slime removal?

**Comment by enetics-secker** [comment]
Yes, slime removal.
