### ISSUE TITLE
Monk player monsters will never spawn as female gender

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#466]
Noticed that the monk monster template in monst.c has the M2_MALE flag, there's no good reason for this is there? Easy fix, just remove the flag from the template.

**Comment by copperwater** [comment]
Out of curiosity I went to find where the M2_MALE flag was added. Turns out it's present in 3.3.0, when the Monk was first added!

Kudos K2 for discovering a bug that flew under the radar for 22 years!
