### ISSUE TITLE
What's the replacement for mapglyph?

### ISSUE THREAD

**Issue by apowers313** [NetHack/NetHack#474]
I just noticed that commit 1d94e65e4558ade510b10b1f61c2aab4873805ce removed `mapglyph`. I was using that function in libnethack to convert glyphs to printable characters. What's the replacement or new best practice for what `mapglyph` used to do?

**Comment by copperwater** [comment]
It is `map_glyphinfo`:

https://github.com/NetHack/NetHack/blob/d28952507a726552de73f5495faa585e99f2e697/src/display.c#L2106-L2109
