### ISSUE TITLE
menu_headings option does not work in curses perm_invent 

### ISSUE THREAD

**Issue by Luxidream** [NetHack/NetHack#499]
Screenshot from hardfought. You can see that the inventory displays the correct formatting for menu_headings while the curses window does not.

![image](https://user-images.githubusercontent.com/35581102/116769464-ecd4f280-aa01-11eb-9120-77b2a7e3a48c.png)

**Comment by ostrosablin** [comment]
I believe it might've been broken since fixing of #480.
