### ISSUE TITLE
Segfault when globby prices are updated

### ISSUE THREAD

**Issue by amateurhourrrr** [NetHack/NetHack#509]
When globby_bill_fixup is called due to globs merging (in my case a glob of gray ooze) it immediately calls set_cost with a null shopkeeper 

If either dknown isn't true or oc_name_known isn't true, then it attempts to read the shopkeeper's m_id to determine if the shopkeeper would charge extra, triggering the segfault

backtrace found during fuzzing:

```
#0  0x0000555555c1ccf1 in set_cost (obj=0x60b000346fb0, shkp=0x0) at shk.c:2279
#1  0x0000555555c35a1f in globby_bill_fixup (obj_absorber=0x60b0003306c0, obj_absorbed=0x60b000346fb0) at shk.c:4743
#2  0x0000555555a1ef55 in obj_absorb (obj1=0x7fffffffdb90, obj2=0x7fffffffdbb0) at mkobj.c:2791
#3  0x00005555559499d2 in merged (potmp=0x7fffffffdb90, pobj=0x7fffffffdbb0) at invent.c:770
#4  0x000055555594a806 in addinv_core0 (obj=0x60b000346fb0, other_obj=0x0, update_perm_invent=1 '\001') at invent.c:907
#5  0x000055555594ae32 in addinv (obj=0x60b000346fb0) at invent.c:947
#6  0x0000555555b4e715 in pick_obj (otmp=0x60b000346fb0) at pickup.c:1670
#7  0x0000555555b4e180 in pickup_object (obj=0x60b000346fb0, count=1, telekinesis=0 '\000') at pickup.c:1619
#8  0x0000555555b46d86 in pickup (what=1) at pickup.c:646
#9  0x000055555591c059 in spoteffects (pick=1 '\001') at hack.c:2295
#10 0x000055555591885f in domove_core () at hack.c:2002
#11 0x000055555590b620 in domove () at hack.c:1381
#12 0x000055555578ee97 in rhack (cmd=0x55555619b49c <g+6396> "l") at cmd.c:3511
#13 0x00005555556fcedf in moveloop (resuming=0 '\000') at allmain.c:449
#14 0x0000555555e10cf2 in main (argc=2, argv=0x7fffffffe758) at ../sys/unix/unixmain.c:335
```

**Comment by pat-rankin** [comment]
I haven't been able to reproduce that but now I see the reason....

The oc_name_known flag is always set for food, including globs.  Until a few days ago, dknown was always set for globs.  The recent change to make the hero forget details of an item when an unseen monster picks it up has unintentionally changed the latter.

So the Null shopkeeper bug has been there for a while but until quite recently there had been no way to trigger it.  That will be fixed shortly but it is also going to become impossible to trigger again.
