### ISSUE TITLE
Vomiting on the altar does not anger the Priest

### ISSUE THREAD

**Issue by davidssmith** [NetHack/NetHack#510]
I was eating my lunch on a cross-aligned altar during a break in an arduous BUC testing session.

An expired tin of dog meat made me predictably sick and confused and eventually I wolfed all over the altar. I quietly slinked out, and the priest did nothing. 

Seems like soiling or defiling the altar should anger the Priest.

**Comment by NullCGT** [comment]
[Thank you for the inspiration.](https://github.com/NetHack/NetHack/pull/519)
