### ISSUE TITLE
Fuzzing in wizard mode switches to exploremode

### ISSUE THREAD

**Issue by amateurhourrrr** [NetHack/NetHack#512]
After a short while of fuzzing, I noticed that wiztele and wizmakemap were no longer firing

It appears that the command #exploremode gets issued at some point and switches the fuzzing session over to explore mode, where the wizard extended commands no longer function

**Comment by copperwater** [comment]
xNetHack has fixed this: https://github.com/copperwater/xnethack/commit/c5aec60

(It's a 2 line fix so I figure it probably isn't worth making a pull request.)
