### ISSUE TITLE
Support for XDG base directory

### ISSUE THREAD

**Issue by danisztls** [NetHack/NetHack#518]
Besides `~/.nethackrc` also reading options from:
 
- `$XDG_CONFIG_HOME/nethack/config`
- `~/.config/nethack/config`

[XDG Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by paxed** [comment]
See the Guidebook: It's already possible to set NETHACKOPTIONS env variable to point to a file, so maybe set it in your shell rc file.

**Comment by danisztls** [comment]
@paxed Thanks!

Haven't tested because there's (apparently) an issue with packaging on Arch Linux but as I understood just have to move the RC file to the desired place and set `.profile` as an example:

```shell
export NETHACKOPTIONS="$XDG_CONFIG_HOME/nethack/config
```
