### ISSUE TITLE
Curses windowport overwrites terminal color settings

### ISSUE THREAD

**Issue by entrez** [NetHack/NetHack#522]
This is something I and at least a few other people have noticed while spectating NetHack games using the curses windowport: often after watching someone's game for a while, some colors will have changed from ones I set to something else.  I haven't yet noticed it happen "in the moment" or even shortly thereafter as far as I know, so I'm not sure of exactly what triggers the change.

I was prompted to open this issue by [this recent Reddit post](https://www.reddit.com/r/nethack/comments/nmmymo/xnethack_curses_interface_overwrites_the_colors/), which talks about xNetHack specifically (playing, not spectating) -- but it's a problem that I have experienced with NetHack as well.

Edit: I have done some quick testing, since I know the original issue was somewhat vague.  Terminal colors change in-game when I play with curses (e.g. the "blue" and "yellow" used are different shades than those I had set myself), but when I save normally they don't seem to persist the way that they do when I spectate a game.  However, killing the game using an external signal does cause the changes to persist.  When playing the change seems to happen on startup rather than at some point "midstream".

**Comment by bhaak** [comment]
Yes that is something I noticed as well somewhen earlier this year. The surprising thing is, this was already in the original curses port patch and in all these years, nobody noticed? Speaks somewhat to the palette Karl has chosen? :)

I almost nuked the code already but there is some interaction with dark gray.

A workaround is to set the TERM variable to a value that wouldn't allow to change colors. For example with TERM=xterm the curses port should not change colors anymore. But this won't help you when watching somebody else.

**Comment by copperwater** [comment]
What is the darkgray issue?

**Comment by ostrosablin** [comment]
> What is the darkgray issue?

I believe, something related to what I mentioned in #482 - some colors, despite being technically different (notoriously dark gray) in most terminal color schemes appear either identical or almost indistiguishable from background color.

This, effectively, renders OPTIONS=dark_room useless, if used e.g. with Solarized theme (because "dark gray" will effectively be same color as background). Of course, you can customize color scheme to work around this issue, but if you don't - then you have to fallback to default Linux terminal color scheme.

**Comment by bhaak** [comment]
> What is the darkgray issue?

I wanted to outright delete every code block that is wrapped in an `if (can_change_color())` but then I noticed that there are also `#ifdef USE_DARK_GRAY` blocks in there. At first glance I couldn't say what those are doing there and if that would change any intended behavior (where colors changing is of course not intended behavior).

I'll tackle it again after Junethack has started.

**Comment by bhaak** [comment]
> Edit: I have done some quick testing, since I know the original issue was somewhat vague. Terminal colors change in-game when I play with curses [...], but when I save normally they don't seem to persist the way that they do when I spectate a game. However, killing the game using an external signal does cause the changes to persist. When playing the change seems to happen on startup rather than at some point "midstream".

Yes, the colors are changed when starting/loading a game and restored to the previous settings if you stop playing in a controlled manner.

Of course when you watch somebody playing on a public server, you don't get that. Worse even you could get the original colors of the player instead of your own colors when they stop playing.

**Comment by entrez** [comment]
I thought it might be happening somewhere else in addition to startup because I have noticed it after spectating a game that was already in-progress, but maybe that's just an artifact of the way spectating works...

**Comment by pat-rankin** [comment]
If PANICTRACE is defined at build time (and NO_SIGNAL isn't defined), the development version resets the terminal if it catches a signal.  So "if you stop playing in a controlled manner" shouldn't be a requirement any more.  However, doing anything substantial from within a signal handler is inherently risky and that could conceivably end up causing other problems.

It's relatively new; cc855d697364e2abbd07247b91b33d3c79099269 in early March.

**Comment by bhaak** [comment]
Yeah, I would be cautious as well to do too much stuff in a panic handler. But this wouldn't help with the people watching on a public server.

With 6e7f1bc1f0bb602334a023dd2039d2ff339fd03e and 5c15ca100278581a10967336390302b492a75498 the curses code does not change any colors anymore.
