### ISSUE TITLE
Compile error (for Windows)

### ISSUE THREAD

**Issue by Meklon2007** [NetHack/NetHack#528]
Hello, the last version of NH don't want comile for Windows:

![compile](https://user-images.githubusercontent.com/12417354/120862767-244f3580-c592-11eb-9635-5b4be4dbd5dd.png)

when i make small change, the game was compiled:

  makefile.gcc for windows:
    line 355 : windsyso -> windsys.o
    line 1327: windsyso -> windsys.o
    line 1327: windsysc -> windsys.c
    line 1328: windsysc -> windsys.c

**Comment by nhmall** [comment]
Thanks. That should be resolved in 0305a14a2704b0ca5d12c5393b11659ee8905535.
