### ISSUE TITLE
Anti-magic field instakill

### ISSUE THREAD

**Issue by CorentinDeBoisset** [NetHack/NetHack#533]
Since https://github.com/NetHack/NetHack/commit/5ad45fc696448422b1daeda76d3f8b62361d9392#diff-7082a9350bde90bd8e3daddae93a3d3e461c326ed51767fb26b9d62bb1a7fc2cR1977 anti-magic fields remove as many HP as they would have PW in case the player has magic resistance. However, for high-level Wizards, it's quite common to have 400PW and only 150HP, meaning stepping on an anti-magic field can quite easily instakill.

**Comment by stenno** [comment]
Same for priests which usually have higher Pw than HP.

**Comment by actual-nh** [comment]
Perhaps multiply drain if being used for HP by maxHP/max(1,maxPW)?

**Comment by actual-nh** [comment]
@copperwater: Perhaps consider this fix for xNetHack?

**Comment by copperwater** [comment]
Added to the xnethack backlog but this is one of those things I think will get fixed upstream before I get to it.

**Comment by actual-nh** [comment]
> Added to the xnethack backlog but this is one of those things I think will get fixed upstream before I get to it.

I can submit a PR if you like; not sure when, of course...

**Comment by dolio** [comment]
Is something going to be done about this? I actually lost this way the other day. Just instant death in the mines with 40+/50 HP (I believe) on a level 8 wizard. And it sounds like the chance of instant death actually increases as you gain levels? I can't really imagine enjoying the style of gameplay required to deal with this (searching every square multiple times for the entire game, I assume).

**Comment by k21971** [comment]
Devteam, please address this, or at the very least state your intentions so we're not left wondering. The anti-magic field damage change is ridiculous. I field several complaints about it every week, either on IRC or via email - having to repeatedly reply with 'there's nothing I can do' is starting to get old.

**Comment by NullCGT** [comment]
Just adding my voice here to say that this definitely needs some sort of fix. Apart from being an extremely unfair way to die, this punishes Wizards and Priests an inordinate amount.

**Comment by ostrosablin** [comment]
I suppose 1:1 tradeoff of HP to Pw wouldn't be fair even if it wouldn't kill you outright. Simply because losing all HP means DYWYPI, but if you lost almost all Pw, it's still possible to deal with it somehow (e.g. fallback to non-magic gear).

I mean, if you'll lose 95% HP during fighting, it would be still very unfair, especially if you're surrounded.

**Comment by copperwater** [comment]
As of this morning, xNetHack addresses it with [this approach](https://github.com/copperwater/xNetHack/commit/74591804518d9cb07fe35b3821fa48609ddf4562): anti-magic fields don't deal HP damage at all. Instead, if you have anti-magic gear on you, the gear amplifies the effect of the anti-magic trap, causing a greater magic drain and a guaranteed loss of 1 max Pw point.

I'm not sure why the HP damage when magic resistant was considered "useful for play balance". If the intended balance was to have a trap with a greater punishment for people who have a good extrinsic, then the xNetHack approach still accomplishes that.

**Comment by Moult** [comment]
Another one bites the dust :( https://au.hardfought.org/userdata/M/Moult/nethack/dumplog/1657362154.nh.html

**Comment by k21971** [comment]
[CorentinDeBoisset](https://github.com/CorentinDeBoisset) you can close this issue, see commit 5c7c9d10ae7984667b533bb7038616dc81346a0f
