### ISSUE TITLE
Question about mummy corpse

### ISSUE THREAD

**Issue by Meklon2007** [NetHack/NetHack#535]
Hello, i don't know, may be this is new feature in NH 3.7, but in nethack 3.6.6 when i killed, in example, gnome mummy it generates "a gnome corpse", in current version it generates "a gnome mummy corpse":

![killed gnome mummy](https://user-images.githubusercontent.com/12417354/122297258-ff4cb200-cf03-11eb-9933-f552034c41b1.png)

When i don't know this is corpse of mummy or not, this moment brought different problems to the game (eat, sacrifice)

Question: should i know that this is the corpse exactly of a mummy?

**Comment by nhmall** [comment]
This issue was just some temporary fallout from gender preservation work in progress and was fixed in 0aaafd19beab302120da9912aaeda877640d88a8 prior to this posting. It should get pushed to GitHub in a while.
