### ISSUE TITLE
"monarch" is incorrectly pluralized as "monarches"

### ISSUE THREAD

**Issue by vultur-cadens** [NetHack/NetHack#536]
The correct plural of "monarch" is "monarchs".  This will need a special case in objnam.c, because regular words ending "ch" are pluralized by adding "es": https://github.com/NetHack/NetHack/blob/0b5a112b0cee0172e3b7ca32df7e9c4a2273f58b/src/objnam.c#L2460

This is noticeable in the dumplog when you have vanquished "elven monarches".

**Comment by nhmall** [comment]
close issue
429b665379702b2a1d66766c90018400be166f66
b28e914bc3f40e66062a493aa97b54cdd20b5c3c
3af1cc79e6bcc55184f798594a64a3e895d74321
