### ISSUE TITLE
Can clone shop credit by kicking gold

### ISSUE THREAD

**Issue by Tomsod** [NetHack/NetHack#538]
In 3.6, kicked gold usually scatters around the place:
https://github.com/NetHack/NetHack/blob/183e31ef142acb992975fb00fef11acfa80281fa/src/dokick.c#L639-L649
But the `scatter()` function (from `explode.c`) doesn't really have any special logic for items being relocated into or out of shops, so if you drop some gold in a shop to gain credit, then manage to scatter some of it on the entrance square or the door square, then pick that gold up, the shopkeeper won't reduce your credit.

This allows gaining free credit very easily.  Sure, there are other ways to clone credit, but they all require some specific resources and/or effort, while for this method the player only needs some starting gold and a working pair of legs, and it's even reasonably fast (provided an amply sized gold pile).

**Comment by moon-chilled** [comment]
Here's a much more fun solution than losing your credit outright: track who scattered the coins, and make the shk get angry when a player-kicked object hits (or misses) them.
