### ISSUE TITLE
#tipping contents of one container into another

### ISSUE THREAD

**Issue by Umbire** [NetHack/NetHack#539]
Submitting the issue at request of paxed, based on conversations in #nethack - I understand this is a popular quality-of-life request, but it also seems like a logical one. According to FIQ: "GnollHack allows you to take items out of a container and put them on the floor rather than the inventory, and the reverse (picking items off the floor and put in a container). This allows you to trivially move items between containers: drop everything from one bag, then pick everything up into another."

I'm inclined to agree - an improved container-to-container menu would make transferring objects from a bag in inventory to a stashed chest much more efficient. It would also remove the complications of burdening oneself in cases involving a bag of holding (as well as the other puzzling middleman of having to have both containers on the floor).

**Comment by copperwater** [comment]
Commenting to add that I think that the behavior @FredrIQ describes in GnollHack is not as complete as it ought to be, as the mechanics of putting items on the floor and then taking them back off has some odd ramifications (scrolls of scare monster disintegrate, artifacts blast you, etc) and it cannot be done if you are levitating or flying over non-solid ground.

In the ideal system, you are able to pick and choose items to transfer from one container (which could be either in your inventory or on the floor) to another container (also could be either in inventory or floor), without using any middlemen. Slightly less ideal, but simpler and still good, is the ability to tip the entire contents of one container into another container.

**Comment by paxed** [comment]
Feature implemented in commit 0f132470c7eaaabce0c9ff8eb53b5e9685f9d57e
