### ISSUE TITLE
Swamp tile generation assumes the room is square.

### ISSUE THREAD

**Issue by ciraben** [NetHack/NetHack#546]
Swamp tile generation assumes the room is square. As seen below, swamp tiles overwrite wall tiles when a swamp is generated in the circular medium theme room type - likely also occurs for other shaped theme rooms.

![Image of swamp tiles overwriting wall tiles in a circular medium theme room which is also a swamp](https://user-images.githubusercontent.com/69187905/125097290-d5ae2300-e08a-11eb-9477-51bc856b0e11.png)

ps - as this is currently the 69th open issue, please never resolve another github issue and please no one post any more. thanks

**Comment by paxed** [comment]
Nice. Fixed, will show up later.
