### ISSUE TITLE
Duplicate messages if pop-up dialog is set

### ISSUE THREAD

**Issue by bramtayl** [NetHack/NetHack#570]
I built linux-qt5 from the 3.7 source. If I set the option popup_dialog to true, I get a pop-up but also duplicate messages printed to the log

**Comment by pat-rankin** [comment]
That's intentional.  The message window gets preserved across save/restore and also is displayed in the dumplog if that is enabled.  Messages handled via popup aren't.

**Comment by bramtayl** [comment]
Hmm, I guess I still don't understand?

**Comment by ostrosablin** [comment]
If you'll save and resume the game later - you could see bunch of last messages that were displayed in previous game session. If popup_dialog disabled "duplicating" messages - you would resume the game with blank log and have hard time remembering, where you've left off.

**Comment by bramtayl** [comment]
That seems...probably ok?
