### ISSUE TITLE
SOUND= should have an option to suppress the corresponding message

### ISSUE THREAD

**Issue by bramtayl** [NetHack/NetHack#571]
Just in case the sound is self-explanatory

**Comment by nhmall** [comment]
What happened to doing it the way discussed in this previous discussion with MSGTYPE=hide in combination with the sound?
https://github.com/NetHack/NetHack/issues/361

That should be possible since e4b18f054587a329b0404927e60517bbb1321e64

**Comment by bramtayl** [comment]
Yes, sorry, I've had a new idea since then. Setting both `SOUND=` and `MSGTYPE=hide` requires duplicating the message in the `.nethackrc` file, but if there was some kind of `suppress = false` keyword argument to `SOUND`, then you wouldn't have to duplicate the message. This would be nice because you could mess around with a regular expression and not have to duplicate your work in another entry.

**Comment by copperwater** [comment]
Sounds like this would be better off as another optional argument to SOUND, which already has one optional argument, than adding a keyword args parser.
