### ISSUE TITLE
Commit 'Disambiguate blunt weapons' breaks saves, patchlevel wasn't incremented

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#587]
Title says it all. Commit in question is 52585b0.

**Comment by nhmall** [comment]
Odd that changing an existing bit from 0 to 1 would break save files ("break" in the sense that they won't load correctly, even if the underlying content's meaning has changed, which is a different matter). Do you have the Bitfield macro configured to not actually use C bitfields on your system? 

The two possible definitions in global.h are:
#define Bitfield(x, n) unsigned x : n
#define Bitfield(x, n) uchar x

I wouldn't have expected that commit to alter the struct size with the first definition for Bitfield(), unless the additional bit specified for the struct pushed the compiler into needing to add a new (additional) unsigned field for it. The "free bits" in the comments are there  to try and alert the developer of that situation.

**Comment by copperwater** [comment]
bhaak reported a savebreak in the sense of not loading correctly but wasn't able to reproduce it. Even assuming it doesn't break saved games, I think it will still disrupt them. 

oc_dir isn't the last bitwise field in the struct, oc_material comes after it. With oc_dir growing by 1 bit, and assuming the compiler packs the bitfields in order and next to one another, the game will load and read a set of 5 bits shifted by 1 from what was saved. So it'd mess up material values for objects.

This is partly on me for not pointing this out in the original commit, so apologies.

Also @nhmall, it looks like there are two different "free bits" comments here (lines 78 and 100), and though they both say 3 now, the first one used to say 4. This should probably be double-checked.

**Comment by nhmall** [comment]
I think the smallest "unsigned int" that we had to deal with in the past was 2 bytes or 16 bits on 16-bit dos real mode. Today, even the remaining viable msdos build under djgpp uses a 32-bit model. That's the likely threshold at which the compiler will devote another unsigned int to the struct for holding the bitfields.

With gcc 11.2, some testing confirmed that the threshold is at 4 bytes or 32-bits (for unsigned) and the struct size won't actually change until the added bitfields exceed increments of that. 
https://godbolt.org/z/T6Wbcascs

**Comment by copperwater** [comment]
Sure the struct size won't change and the game may not detect this at load... but it'll still be interpreting the oc_material fields from a pre-this-commit save file wrong due to using the wrong offset. Yeah, the game's not gonna crash, but you might wind up with all scrolls being made of metal, or elven daggers made of flesh, or even invalid materials with higher values than NUM_MATERIAL_TYPES.

**Comment by entrez** [comment]
> or elven daggers made of flesh

Well, why are they called "elven" if they aren't made of elves? Sounds to me like a solution, not a problem.
