### ISSUE TITLE
Use of (virtually) unassigned variable in do_name.c

### ISSUE THREAD

**Issue by argrath** [NetHack/NetHack#595]
(From Coverty Scan:)

Variable `i` is used in this code, but `i` isn't assigned any value
other than loop counters for fixed-count loops.

I believe this is wrong, but I don't know how to fix...

https://github.com/NetHack/NetHack/blob/e52f38b3a36d1e84655c7836d69d1608c0f8cc64/src/do_name.c#L788-791

**Comment by nhmall** [comment]
It looks like this has already been reported, with a fix, in pull request
https://github.com/NetHack/NetHack/pull/592

**Comment by argrath** [comment]
Oh, sure.

I'll close it when that PR is merged.
