### ISSUE TITLE
Meaningless comparison on ustatusline()

### ISSUE THREAD

**Issue by argrath** [NetHack/NetHack#620]
https://github.com/NetHack/NetHack/blob/0ea7e7aef488417571db74c50906ab9113cabc12/src/insight.c#L2897

Here, `Wounded_legs` means `(HWounded_legs || EWounded_legs)` and gets 0 or 1.
`BOTH_SIDES` is 0x60000L.  So, `(Wounded_legs & BOTH_SIDES)` is
always 0 and this comparison is meaningless.

(from Coverity Scan)

**Comment by nhmall** [comment]
https://github.com/NetHack/NetHack/commit/27fcf8999fe2891892ce3e48f6525130ab4d21d3
