### ISSUE TITLE
How do I edit the sprite for hilite_pet? Also, what about hilite_pile?

### ISSUE THREAD

**Issue by 1to** [NetHack/NetHack#622]
I hope this is not a weird place to ask for this, but
There isn't a hilite_pet sprite in the tileset sheet, and it could be interesting to edit it to stylize the game further. Is it because it is a transparent texture? Can I edit it somehow, even if I can't bundle it with my tileset?

While I'm asking for this, why is there a sprite for hilite_pet but not one for hilite_pile?

**Comment by nhmall** [comment]
Right now, the window ports draw the pet or pile feature when they render the character or tile in the game. TTY highlights with reverse video. Windows, X11, Qt tiled displays place a little heart overlay on the tile for pets, or a little + for a pile (if you have the hilite_pile option enabled). There isn’t a separate set of pet monster tiles or hilite object tiles available. 

The gray-scale statue tiles are produced from the monster tiles during the build process by the tile2bmp utility.

**Comment by entrez** [comment]
It looks like the little icons for the windowports are defined in the source files for that windowport using various different formats, e.g. X11 pet heart ([xbm](https://en.wikipedia.org/wiki/X_BitMap)):

https://github.com/NetHack/NetHack/blob/6b882609ac38977a06b8e309aeb1788289f15dc7/win/X11/pet_mark.xbm#L1-L6

Qt ([xpm](https://en.wikipedia.org/wiki/X_PixMap)):

https://github.com/NetHack/NetHack/blob/6b882609ac38977a06b8e309aeb1788289f15dc7/win/Qt/qt_map.cpp#L28-L56

Win (bmp run through [uuencode](https://en.wikipedia.org/wiki/Uuencoding)):

https://github.com/NetHack/NetHack/blob/6b882609ac38977a06b8e309aeb1788289f15dc7/win/win32/petmark.uu#L1-L9

The pile mark is similar.

So if you wanted to modify those, with the way things work currently I guess you'd have to get your custom image into the appropriate format, edit the file where it's located, and recompile.  How complicated this could get, and the limitations you'd encounter, would depend on the windowport.

**Comment by nhmall** [comment]
The response from @entrez was thorough and there doesn’t seem to be continuing discussion. Closing issue.
