### ISSUE TITLE
[feature request] enable User sound on Mac OS

### ISSUE THREAD

**Issue by deciding** [NetHack/NetHack#629]
Hello, as stated in the title, can help add user sound feature for macos? thanks!

**Comment by deciding** [comment]
I finished the code for adding the sound effect and background music for NetHack on MacOS(should work for Linux also), using library SDL2 mixer. Not sure if nethack 3.7 needs this, tell me if needed so that I can clean the code for a pull request.

**Comment by nhmall** [comment]
I don't think anyone would be opposed to this, but there could be some issues with the implementation, depending on how it was done.  

I think the Qt window port on macOS already implements a USER_SOUNDS variation, and people do build a single binary that supports tty, curses, Qt, and X11 window ports.  It, ideally, needs to be done in a way that one implementation doesn't trample on another or can be selected as a config file option.

That's an area that the "_sound interface_" in NetHack could use improvement. The _window port interface_ is all done through function pointers that can be changed, but the _sound interface_ (if you can even call it that) is not. If the NetHack _sound interface_ is improved to allow support for more than one option based on user preferences, I think it should be done independently of the _window port interface_ which is geared mainly to display and user input, and sound implementations do not need to be tied to that.

**Comment by nhmall** [comment]
@deciding were you still planning on presenting something for this?

**Comment by nhmall** [comment]
> That's an area that the "_sound interface_" in NetHack could use improvement. The _window port interface_ is all done through function pointers that can be changed, but the _sound interface_ (if you can even call it that) is not. If the NetHack _sound interface_ is improved to allow support for more than one option based on user preferences, I think it should be done independently of the _window port interface_ which is geared mainly to display and user input, and sound implementations do not need to be tied to that.

Some work was just done to hopefully improve the sound interface in NetHack-3.7. See commit ea4a81901da631358014ab2f504511a2748b0f1d
