### ISSUE TITLE
Hello, it's *deaf*ness

### ISSUE THREAD

**Issue by AmyBSOD** [NetHack/NetHack#631]
There seems to be a blatant oversight when a character is "deaf". Of course you are still able to chat to things, after all you're deaf, not deaf-and-mute! You just can't hear the response of whatever entity you're chatting to! The oversight where the game doesn't let you chat at all should be fixed ASAP so that players who try the permadeaf conduct don't have to go so far out of their way just to be able to complete the quest ;)

**Comment by nhmall** [comment]
https://github.com/NetHack/NetHack/commit/e8acc185ad254981296966608940960fd5513830

**Comment by AmyBSOD** [comment]
Cool, thanks :+1:
