### ISSUE TITLE
Do there exist any expert demonstrations?

### ISSUE THREAD

**Issue by albertcity** [NetHack/NetHack#641]
I am interested in how to apply imitation learning in such a PCG environment. Do there exist any expert demonstrations? Thanks.

**Comment by PFGimenez** [comment]
You can find recording of previous plays on https://alt.org/nethack/. Here is an example (I took a random one) : https://alt.org/nethack/userdata/M/MaSt/ttyrec/2021-11-30.14:06:27.ttyrec
This website includes the best players.
You can also find games on Youtube. Tone does "let's play" : https://www.youtube.com/c/Tonehack
To apply machine learning on NetHack, you should look at the NetHack learning environment : https://github.com/facebookresearch/nle
Hope it helps.

**Comment by albertcity** [comment]
> You can find recording of previous plays on https://alt.org/nethack/. Here is an example (I took a random one) : https://alt.org/nethack/userdata/M/MaSt/ttyrec/2021-11-30.14:06:27.ttyrec This website includes the best players. You can also find games on Youtube. Tone does "let's play" : https://www.youtube.com/c/Tonehack To apply machine learning on NetHack, you should look at the NetHack learning environment : https://github.com/facebookresearch/nle Hope it helps.

Many thanks.

**Comment by RojjaCebolla** [comment]
Luxidream is the current best player in tournaments. https://nethackscoreboard.org/players/L/Luxidream.all.html

A player named Tariru has not played in some time, but had a playstyle with very few errors, able to "streak" 61 victories in a row without losses. https://nethackscoreboard.org/streaks.all.html
