### ISSUE TITLE
Compilation error in windows

### ISSUE THREAD

**Issue by Meklon2007** [NetHack/NetHack#649]
Hello, in the last NH on the github:
after the latest updates (maybe after "date.c vs MONITOR_HEAP" commits and "switch makedefs from malloc() to alloc()" commit), the game stopped compiling in windows:

![image](https://user-images.githubusercontent.com/12417354/147409983-2b9d8efa-fd5b-4a99-b06d-c49655b83a21.png)

**Comment by pat-rankin** [comment]
WIndows Makefile.* and IDE project files haven't been updated to match the change sys/unix/Makefile.utl.  Linking makedefs needs to add o/alloc.o now.

**Comment by Meklon2007** [comment]
After commit "possible build fix catch-up for Windows Makefile.gcc" where was added alloc.o, the compiler still can't make makedefs.exe in windows:
![compile_NH](https://user-images.githubusercontent.com/12417354/147550709-2c949b81-17ce-42b1-bd0a-4df1cdd0c44e.png)

**Comment by Meklon2007** [comment]
Yes, after commit "more possible build fixes ", NH compiled in windows without errors.
