### ISSUE TITLE
Overwrite prefixhandling on help_dir()

### ISSUE THREAD

**Issue by argrath** [NetHack/NetHack#664]
https://github.com/NetHack/NetHack/blob/260e0150676a1c7caceb56df7dd4592655ea4754/src/cmd.c#L4122-L4130

Here, `prefixhandling` is assigned to `(spkey != NHKF_ESC)` once, then overwritten by `FALSE`.
I think there is something wrong with this.

**Comment by entrez** [comment]
Yeah, none of the 'you can't fight yourself', 'you can't run upward', etc, messages seem to work any more.  It seems like `help_dir` doesn't get called at all under the circumstances it used to, in addition to this issue...

Also, I get the message 'You can't get  there from here...' where it makes no sense, e.g. if I enter the sequence <kbd>g</kbd><kbd>^</kbd><kbd>\></kbd> immediately after starting the game.

<img width="386" alt="Screen Shot 2022-02-02 at 10 17 31 AM" src="https://user-images.githubusercontent.com/40038830/152182336-a18e57c8-734a-44ee-8de6-c324445ac91b.png">


But it seems to stop happening after a while, e.g. after I move for the first time that same sequence no longer produces the message.
