### ISSUE TITLE
Character enters unstoppable loop when travelling

### ISSUE THREAD

**Issue by pescepalla** [NetHack/NetHack#678]
Playing 3.7.0 hardfought, travelling `_` to `>` puts the `@` into an unbreakable loop between the tile it occupies and that immediately NE until a monster comes to attack.
![nethack](https://user-images.githubusercontent.com/46329185/153455768-9972f91f-78c8-4477-bbd6-e3376ffb8530.png)

**Comment by paxed** [comment]
This should be fixed by commit 1d78d3c3f27d986e24b925a709a6c6d8afc1a2e0

**Comment by paxed** [comment]
Actually, there were at least two other cases when the oscillation could happen, so there's a followup commit coming.
