### ISSUE TITLE
Orcs and strength

### ISSUE THREAD

**Issue by eakaye** [NetHack/NetHack#679]
All `o` except for goblins are defined as "strong", which among other things means polymorphing into one sets your base strength to 18/**. However, orcish PCs are limited to 18/50 strength. This has the rather odd ramification that an orcish hero polymorphed into a lowly hill orc becomes stronger than they could ever be as a "real" orc.

I understand that NetHack orcs are imagined as short, gangly creatures in the Tolkein vein, rather than Warhammer-esque brutes, so 18/50 max strength sounds right. Rather, I think the best way to resolve the contradiction is to remove the strong attribute from orcish monsters, other than Uruk-Hai (which were bred for strength).  Hobgoblins can also keep it, since they're a whole different race.

**Comment by vultur-cadens** [comment]
Related to this, all orcish heroes start with poison resistance, suggesting that poison resistance is innate to orcs -- but orcish monsters don't have poison resistance.  For consistency, it seems that orcish monsters should have poison resistance.  This is similar to how all elven monsters have sleep resistance, and elven heroes easily gain sleep resistance at XL 4.

**Comment by entrez** [comment]
Orcish heroes go through a regimen where they are dosed with small amounts of poison over the course of their childhood, leaving them immune to poison but physically weak.  Contradiction resolved :)

**Comment by copperwater** [comment]
> Related to this, all orcish heroes start with poison resistance, suggesting that poison resistance is innate to orcs -- but orcish monsters don't have poison resistance. For consistency, it seems that orcish monsters should have poison resistance. This is similar to how all elven monsters have sleep resistance, and elven heroes easily gain sleep resistance at XL 4.

I agree with this - I implemented this in xNetHack for that reason. Probably not worth linking the commit though, since all it does is add `MR_POISON` to all o monsters :)

**Comment by Umbire** [comment]
Coming back to this, a question occurs: Uruk-hai are bred for strength and thus defy the newly-established standard orcish cap of 18/50 STR for polyforms - they can also grow up into orc-captains, which obey that cap like all other strong monsters. Would it make enough sense for orc-captain polyforms to achieve 18/** STR like Uruk-hai, since the captains are supposed to be the strongest type of non-unique orc in the monster class?

EDIT: I think it'd make more sense on my part to make this its own issue.
