### ISSUE TITLE
Possible error on parse_condition()

### ISSUE THREAD

**Issue by argrath** [NetHack/NetHack#680]
https://github.com/NetHack/NetHack/blob/08da5befcb796f2d4c67a4ee07315160c3d6371f/src/botl.c#L2773

On parse_condition(), `s` is declared as "a pointer of an array of char".

https://github.com/NetHack/NetHack/blob/08da5befcb796f2d4c67a4ee07315160c3d6371f/src/botl.c#L2797

So, `s[sidx]` means "an address of an array of char" and it is always true (non-zero).

**Comment by argrath** [comment]
https://github.com/NetHack/NetHack/blob/08da5befcb796f2d4c67a4ee07315160c3d6371f/src/botl.c#L2413

Line 2413 has similar code.

**Comment by nhmall** [comment]
Thanks, I've put a fix into the pipeline.

Related note:  That particular loop body was functioning correctly, and returning to the caller appropriately, and would have done so even if it had been
    `while(1)`
(which it effectively was).
