### ISSUE TITLE
Monsters should not spawn on scrolls of scare monster

### ISSUE THREAD

**Issue by NetSysFire** [NetHack/NetHack#717]
I have a stash on a level and surrounded it by boulders for safekeeping (therefore only reachable via teleport since it is right at the indestructible edge of the level). Sometimes a monster spawns on the scroll of scare monster (where also my containers with my loot are) which is super annoying, so in order to get rid of it I have to blindly throw projectiles at it or zap a wand of magic missile in order to not damage anything on that square.

```

..0?0..
..000..
.......
```

The only potential edge case I could imagine is someone filling the entire level with scrolls of scare monster, but this is super hard to achieve since it either requires an insane amount of grinding or many wishes.

**Comment by pat-rankin** [comment]
commit f0c73949689ac47db37e1290cd61c94cdf7ef8ba
git issue #717 - avoid putting monsters on scare \
monster and Elbereth unless there's no other choice.

closes #717.
