### ISSUE TITLE
[feature request] Use available tool before force on locked doors or containers

### ISSUE THREAD

**Issue by UnstoppableDrew** [NetHack/NetHack#719]
When you encounter a locked door or container you are prompted to kick it open or force the lock. If you have a key or lockpick in your open inventory it would be nice if you were prompted to use them instead, which would save you from having to decline, apply, pick item letter, direction, confirm.

**Comment by entrez** [comment]
What version of NetHack are you playing that has prompts to kick down doors and force boxes, without prompting you to unlock them if you have a key?  I can't remember ever seeing a prompt to kick down a door before, but 3.7 should prompt you to use a key if you have `autounlock` on.

**Comment by UnstoppableDrew** [comment]
I'm on the Android version, which it just occured to me is probably a ways
behind. Sorry about that & disregard if this is already there.

**Comment by paxed** [comment]
This is android-specific change to 3.6.6
