### ISSUE TITLE
Ctrl + m doesn't act in a same way as Ctrl + j

### ISSUE THREAD

**Issue by ostrosablin** [NetHack/NetHack#72]
NetHack Wiki claims that "Ctrl + m acts in a same way as Ctrl + j". But in actuality, many prompts don't recognize it as an Enter key. This cause an issue with vi-style controls. Pressing Enter while not in prompt, acts as ^J (go south) which is a major annoyance. Reconfiguring a tty to issue ^M on an enter keypress _should_ have solved this problem, but unfortunately, it only works with some --More-- prompts. It doesn't work with Restoring save file --More-- prompt, and doesn't work with other prompts, like ext command or engrave prompt.

**Comment by paxed** [comment]
Fix committed.
