### ISSUE TITLE
add IA_TIP in item_action_actions?

### ISSUE THREAD

**Issue by Meklon2007** [NetHack/NetHack#727]
Hello, in the last NH 3.7 of current version was added function itemactions. When i try tip the bag there was no necessary action.
I don't know, but maybe need add IA_TIP in the item_action_actions for bags (although it is unclear what to do with "bag of tricks")?

**Comment by ostrosablin** [comment]
Bag of tricks can be tipped, too, even though you will probably regret doing so (unless it's already empty).

**Comment by ostrosablin** [comment]
Isn't discharged bag of tricks behave like a sack and could be used to store items? According to NetHackWiki:

_A bag of tricks with no charges can hold items like a regular sack; charging it again will destroy any items inside._

It looks like current itemactions patch doesn't accurately reflect this.

**Comment by paxed** [comment]
@tmp6154 You're looking at a variant information, not NetHack.

**Comment by ostrosablin** [comment]
Oh, sorry, my bad.
