### ISSUE TITLE
Crash upon renaming ring

### ISSUE THREAD

**Issue by ExplodingCabbage** [NetHack/NetHack#74]
I'm not sure precisely what set of circumstances is needed to make this happen, but I *can* provide a save file from 3.6.0 that reproduces it reliably.

[Mark-Karm.zip](https://github.com/NetHack/NetHack/files/1485617/Mark-Karm.zip)

If you open the save file in the zip attached above and try renaming the type of item `t` (*an uncursed ring called jade of adornment or hunger or protection or protection from shape changers or stealth or sustain ability or warning*) to anything else, Nethack crashes with

> Run-Time Check Failure <span>#</span>2 - Stack around the variable 'buf' was corrupted.

The save has gone through a couple of crash/recovery cycles but I haven't manipulated it with anything other than Nethack.

**Comment by nhmall** [comment]
Thanks for providing the save file, that helped. 
Reproduced and now fixed in 
0301420fcbf77c7e2a2d3f75073243b0000f25a9

**Comment by nhmall** [comment]
resolved
