### ISSUE TITLE
Second attack still executed while paralyzed

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#745]
Noticed this while attacking a gelatinous cube as a Samurai twoweaponing:

`You miss the gelatinous cube.  You are frozen by the gelatinous cube!  You miss the gelatinous cube.`
`The gelatinous cube touches you!  You can move again.`
`You miss the gelatinous cube.  You are frozen by the gelatinous cube!  You miss the gelatinous cube.`
`The gelatinous cube touches you!  The gelatinous cube touches you!  You can move again.`
`You miss the gelatinous cube.  You are frozen by the gelatinous cube!  You kill the gelatinous cube!
You can move again.`

Notice the order of events - the second offhand attack is still executed, even though the player is supposedly paralyzed from the passive attack of the gelatinous cube after the first attack.

**Comment by entrez** [comment]
Good one.  You can even get double-frozen in one turn:
`You miss the gelatinous cube.  You are frozen by the gelatinous cube!  You hit the gelatinous cube.  You are frozen by the gelatinous cube!--More--`

I guess it could use a check on g.multi or something similar here:
https://github.com/NetHack/NetHack/blob/933408650632899c4102979ceaa4665e79a766f4/src/uhitm.c#L704-L709

**Comment by k21971** [comment]
Yup, that's where I was looking to see if I could make a PR. I'm not sure how you check for nomul() being greater than 0 though, or if that's even the right way to go about it.
