### ISSUE TITLE
Annotate - allow to add to current annotation?

### ISSUE THREAD

**Issue by ostrosablin** [NetHack/NetHack#75]
I've often add something, when i #annotate a dlvl. For example, if I find out that there's a vault on level. Later, if I find out there's soldier ants around, I want to add that information to annotation, but keep original info. As it stands, you can only completely replace level annotation. But it would be great if you could add to it, like with engraving (do you want to add to current annotation?). That way you won't need to re-type previous annotation if you only want to add new info.

**Comment by AndrioCelos** [comment]
It may also be nice to be able to cancel the prompt. Entering an empty string erases the annotation. This isn't consistent with the `#name` command, which does nothing if you enter an empty string (or hit escape) but erases the name if you enter a single space.

**Comment by ostrosablin** [comment]
@AndrioCelos Yes, this makes a lot of sense. Anyone? @paxed

**Comment by ostrosablin** [comment]
Put together a patch and sent it as pull request.

#83 solves this.

**Comment by ostrosablin** [comment]
Commit 94ad751 from @paxed uses a different approach for the same idea. Now, compile-time option EDIT_GETLIN allows to edit annotations.

@AndrioCelos regarding cancelling the prompt - weird. Looking at the code - it should be cancellable with escape. And it works for me on tty windowport.

**Comment by ostrosablin** [comment]
Fixed a long time ago. Closing.
