### ISSUE TITLE
d(n, x) function comments in rnd.c

### ISSUE THREAD

**Issue by tommyjiang** [NetHack/NetHack#753]
When I read the comments of the `d(n, x)` function, it confuses me.

The `d(n, x)` function uses `RND(x)` which ranges from 0 to x-1 (Line 183), thus the total results ranges from 0 to n(x-1). Correct me if I am wrong, thanks.

https://github.com/NetHack/NetHack/blob/6ccb56638a33d5e03e7989c4c7b581bf0d05ff79/src/rnd.c#L170-L185

**Comment by bhaak** [comment]
You missed the initialization of tmp: "int tmp = n". So tmp is always at least n.

Remember that d(n, x) is a simulation of n x-sided dices.

**Comment by tommyjiang** [comment]
> You missed the initialization of tmp: "int tmp = n". So tmp is always at least n.
> 
> Remember that d(n, x) is a simulation of n x-sided dices.

Thanks for the quick reply. Sorry I forget to look at the init.
