### ISSUE TITLE
[3.7.0-59] monsters leave corpses elsewhere on the level

### ISSUE THREAD

**Issue by jeremyhetzler** [NetHack/NetHack#764]
Playing on Hardfought.

Unix NetHack Version 3.7.0-59 Work-in-progress - last build May 15 2022 09:28:36 (45359342a7f00b0d8e87f223ee30c840807ac9a6,branch:master).

When a monster dies, they often leave their corpse at a random location on the level, instead of where they were standing when killed. Happened in the early levels with gnomish wizard, newt, fire ant. Happened in Sokoban, which is no-teleport.

**Comment by k21971** [comment]
Editlevel 59 (commit 3a0a927) went live just a few hours ago on all of the Hardfought servers - paniclog has several entries in relation to this issue. See https://www.hardfought.org/xlogfiles/nethack/paniclog
