### ISSUE TITLE
runmode on tty doesn't seem to have effect

### ISSUE THREAD

**Issue by ostrosablin** [NetHack/NetHack#766]
Something I've noticed while playing on Hardfought 3.7.0.

runmode works on curses, but setting it on tty has no effect and even with it being set to crawl, all travels and runs are being displayed instantly rather than being displayed frame by frame.

On 3.6.x it used to work on tty, too.

**Comment by entrez** [comment]
Hmm, I just tested and it works fine for me, both locally and on Hardfought.  If you run 3.7 locally do you have the same problem?  Does changing the `timed_delay` setting make any difference?

**Comment by ostrosablin** [comment]
Yeah, that was it. Setting timed_delay seems to fix the problem for me.

But I've done some extra digging, because it didn't reproduce locally. In the end, it seems that problem was with my (pretty convoluted) setup in first place.

I usually connect to Hardfought through my Raspberry Pi in tmux session, while being connected to Raspberry Pi through SSH from some other machine (because Raspberry Pi is an always-on device, running connection to hardfought in tmux there makes it possible to switch e.g. from smartphone to PC or vice versa, or play from smartphone in bad mobile internet conditions without getting disconnected due to loss of signal).

Removing anything from equation (e.g. connecting directly without Raspberry Pi or connecting without tmux on Raspberry Pi side) seems to work without timed_delay. Perhaps, it's a bug in Raspbian's tmux version.
