### ISSUE TITLE
Eating a monster corpse that revives while eating causes a panic

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#769]
I've seen this at least three times now on 370-hdf (editlevel 59, last commit 6af5555). Player is eating the corpse of a reviver, typically a troll corpse. Corpse revives mid-eating, causes the game to crash. No coredump, but the entry in the paniclog shows as `1653075244 rustyspoon: panic revive`.

**Comment by nhmall** [comment]
Hi, can you quickly and easily add the following patch to assist the investigation?
```
diff --git a/src/zap.c b/src/zap.c
index af8c766a4..8ae2d513c 100644
--- a/src/zap.c
+++ b/src/zap.c
@@ -1015,8 +1015,12 @@ revive(struct obj *corpse, boolean by_hero)
             break;
         }
         /*FALLTHRU*/
+    case OBJ_FREE:
+    case OBJ_MIGRATING:
+    case OBJ_ONBILL:
+    case OBJ_LUAFREE:
     default:
-        panic("revive");
+        panic("revive default case %d", (int) corpse->where);
     }
 
     return mtmp;
```

**Comment by k21971** [comment]
'Homework' is live, will keep an eye on the paniclogs.

**Comment by pat-rankin** [comment]
I still haven't figured this out.  It's suspicious that it was happening at about the same time that mon_leaving_level() was zeroing a dead monster's map coordinates when taking it off the map.  make_corpse() tried to put the corpse at <0,0> but for one made by mkcorpstat() that value is used to mean "random location" rather than off the normal map.  So troll corpses would be placed randomly rather than be inaccessible.  I still don't see how their 'where' field could be different at the end of revive() than it was earlier in that same routine.

That situation only lasted a day or two before it got changed back to leaving a dead monster's map coordinates as they were when it was still alive so that make_corpse() could rely on those coordinates.

**Comment by entrez** [comment]
OK, I just encountered this in a real game and was able to reproduce it.  It relies on the eating timeout and corpse revival happening on the same turn.

Here's what happens on the turn, basically:

1.  `run_timers` runs, calls `revive` on the corpse.
2. `revive` calls `makemon` to produce the revived troll, before doing anything special to the corpse (the corpse might not successfully revive, so we want to check whether the monster was successfully created first, before removing the corpse)
3. `makemon` calls `dochugw` (as of f2f2644e30 -- this is why it's a new issue), which calls `stop_occupation`
4. `stop_occupation` calls `maybe_finished_eating`, which sees that this is the turn when you're supposed to be done eating.  So it goes through the whole process of deleting the corpse, telling you that you finish eating, etc.  `g.context.victual.piece->where == OBJ_FREE` now (and the corpse is freed).
5. control returns to `revive`, which continues on its merry way until it discovers that the corpse has been freed/`corpse->where == OBJ_FREE`, and panics.

Edit: one solution might be to have `stop_occupation` always stop the occupation, and not provide any affordances to "oh, well, you'd have finished eating this turn so you get to finish up."  Like the below patch.  I don't know if there's any reason that would be a problem for other places `stop_occupation` is called, but it seems to fix this panic.

```diff
diff --git a/src/allmain.c b/src/allmain.c
index 71a892f23..a2f0f5c53 100644
--- a/src/allmain.c
+++ b/src/allmain.c
@@ -604,8 +604,7 @@ void
 stop_occupation(void)
 {
     if (g.occupation) {
-        if (!maybe_finished_meal(TRUE))
-            You("stop %s.", g.occtxt);
+        You("stop %s.", g.occtxt);
         g.occupation = 0;
         g.context.botl = TRUE; /* in case u.uhs changed */
         nomul(0);
```

**Comment by entrez** [comment]
By the way, in case it is helpful this is the patch I applied to reproduce this consistently.  If you aren't fast, you kill a troll on the square next to you and immediately move onto the square and start eating, it will revive on the same turn you would finish eating and cause the panic:

```diff
diff --git a/src/eat.c b/src/eat.c
index b2e15c76c..fc6420afc 100644
--- a/src/eat.c
+++ b/src/eat.c
@@ -1827,8 +1827,7 @@ eatcorpse(struct obj *otmp)
     }
 
     /* delay is weight dependent */
-    g.context.victual.reqtime
-        = 3 + ((!glob ? mons[mnum].cwt : otmp->owt) >> 6);
+    g.context.victual.reqtime = 3;
 
     if (!tp && !nonrotting_corpse(mnum) && (otmp->orotten || !rn2(7))) {
         if (rottenfood(otmp)) {
diff --git a/src/mkobj.c b/src/mkobj.c
index b56a77856..d3cc958f9 100644
--- a/src/mkobj.c
+++ b/src/mkobj.c
@@ -1260,12 +1260,8 @@ start_corpse_timeout(struct obj *body)
         action = REVIVE_MON;
         when = rider_revival_time(body, FALSE);
     } else if (mons[body->corpsenm].mlet == S_TROLL) {
-        for (age = 2; age <= TAINT_AGE; age++)
-            if (!rn2(TROLL_REVIVE_CHANCE)) { /* troll revives */
-                action = REVIVE_MON;
-                when = age;
-                break;
-            }
+        action = REVIVE_MON;
+        when = 4;
     } else if (g.zombify && zombie_form(&mons[body->corpsenm]) != NON_PM
                && !body->norevive) {
         action = ZOMBIFY_MON;
```

**Comment by pat-rankin** [comment]
Taking out the call to maybe_finished_meal() would bring back a different hard to find bug, where if you got interrupted (by something other than corpse revival) on the last turn of a meal, the partly eaten food would be restored to untouched instead of being used up.

But now that the panic's cause is known, fixing it should be straightforward.  Thanks.
