### ISSUE TITLE
Oil explosion burning a secret door is described as a "spell"

### ISSUE THREAD

**Issue by copperwater** [NetHack/NetHack#771]
To reproduce, wish for an undiscovered secret door, then light a potion of oil and throw it at the door. Then you get:

`A potion of oil (lit) shatters!  Your spell reveals a secret door.  The door is consumed in flames!`

Obviously, there's no magic happening; there seems to be an assumption that all fire explosions caused by the player are the result of the fireball spell. (When a flaming sphere explodes by the door, it says "The blast reveals a secret door.")

**Comment by entrez** [comment]
> there seems to be an assumption that all fire explosions caused by the player are the result of the fireball spell.

I don't think it's this so much as that `splatter_burning_oil` uses the fireball zap type for the explosion, and differentiates itself with the `olet` passed to `explode` -- but that information isn't carried over to `zap_over_floor` in any way, so at that point it just looks like a fireball spell.  I think one simple (maybe somewhat kludgey) way to fix it would be to set `exploding_wand_typ` for `olet == BURNING_OIL`, like this:

```diff
diff --git a/src/explode.c b/src/explode.c
index c93fc5818..668eea5e4 100644
--- a/src/explode.c
+++ b/src/explode.c
@@ -82,6 +82,8 @@ explode(
         default:
             break;
         }
+    } else if (olet == BURNING_OIL) {
+        exploding_wand_typ = (short) type;
     }
     /* muse_unslime: SCR_FIRE */
     if (expltype < 0) {
```

That does seem to produce the desired result:

https://user-images.githubusercontent.com/40038830/169880179-72d8c094-5723-41ee-bbd0-c0e334dbbf54.mp4
