### ISSUE TITLE
Clairvoyance while engulfed gives odd messages.

### ISSUE THREAD

**Issue by AndrioCelos** [NetHack/NetHack#78]
I'm currently in a game of NetHack 3.6.1-dev on nethack.alt.org and have let Juiblex try to eat me after grabbing the Amulet of Yendor. At one point I had the clairvoyance effect from carrying the Amulet trigger while I was still inside Juiblex. It was immediately after using a unicorn horn, so this is the message that appeared:
`Nothing seems to happen. (For instructions type a '?')`
Seems like it could be a bit confusing for someone who didn't realise that it's clairvoyance from carrying the Amulet.
In addition, Juiblex showed up as a white `&`, instead of a green `&` as he normally does.

**Comment by nhmall** [comment]
fixed in 094c7f5c1bda8056323815e973928f8ebd95d177
