### ISSUE TITLE
symset enhanced1 and curses windowport don't seem to play nice

### ISSUE THREAD

**Issue by ostrosablin** [NetHack/NetHack#780]
It seems that curses don't work nicely with enhanced1 symset.

I've noticed it first on Hardfought, but was able to reproduce it (sort of) locally, too. I'm using Konsole from KDE with UTF-8 encoding (default). In both cases, tty works with perfectly with enhanced1.

![image](https://user-images.githubusercontent.com/5955408/171367776-fb1483db-46e3-4c3a-a71d-11fdbf7c27b5.png)

Above screenshot is from hardfought. Map window borders are noticeably offset and movement produces ghost characters of player and pet (apparently due to screen updates updating wrong positions) rendering game unplayable, so I have to fallback to IBMGraphics and filterm approach.

![image](https://user-images.githubusercontent.com/5955408/171368392-7ffd3dfa-9f23-4945-9679-3efd39046bc6.png)

This screenshot is from locally-built nethack. It's broken, too, but not same way as on Hardfought. Characters seem to render at proper locations, there's no ghosting, but now symbols themselves seem to be off.

In both cases, symset is:
symset                  [enhanced1, active, handler=UTF8]

**Comment by bhaak** [comment]
Locally, you need to have a proper utf8 locale set up. ncurses is very picky in that way, even though nowadays there is hardly any terminal without utf8 support.

locale -a will show you what is available and then something like "export LC_CTYPE=en_US.utf8" or "export LC_ALL=en_US.utf8" should do.

Hardfought is broken because it links to the wrong ncurses version.

**Comment by k21971** [comment]
There were a couple things not defined in the hints file used for the hardfought build of 3.7.0...

`CFLAGS+=-DCURSES_UNICODE` wasn't set, that's my bad.

In the linux.370 hints file, you have `CURSESLIB = -lncurses -ltinfo`, -lncurses should be -lncursesw instead.

This has been addressed, and the 370-hdf build on the hardfought servers has been updated. Give it a whirl, tmp6154.

**Comment by ostrosablin** [comment]
That worked, @k21971 . Can confirm that 370-hdf now works perfectly with curses and enhanced1.

Apparently, my local build is linked with libncurses.so.6, too, so it's essentially same problem as on 370-hdf (linking to non-widechar ncurses). Because of that, @bhaak 's suggestion didn't work.

This is weird, though. There's a part of hints file that should set CURSES_UNICODE automatically if you pass WANT_WIN_CURSES.

https://github.com/NetHack/NetHack/blob/5977fa4481012004be5a73cd04f3ce4a1880ec0f/sys/unix/hints/linux.370#L109

However, hints file doesn't look correct, since setting CURSES_UNICODE should also automatically switch CURSESLIB to `-lncursesw -linfo`, I guess.

**Comment by nhmall** [comment]
A series of changes (62014be6f8cef20285ddfb519228747454349b45, ae1f5b8d2a99c4e4a1eb7cc9f848fcb4faadd954, 7b1528707b78af5ae5e695ada04bb8d8c45ae161, 168ee4c9a8bf0523d7c96be2b44490822408b2ed, 57cfd7e7ed59df778a24e716f585d07dcedea8a7) should resolve the outstanding issues pertaining to this on Linux.

Among them:
- try to determine if ncursesw is available prior to build.
- If ncursesw is available, use it for curses during the NetHack link.
- If ncursesw is not available, do not add the define for CURSES_UNICODE and use ncurses (without the w).

Caveats:
- It relies on the detection in the Makefile working correctly, although the last related change iteration is meant to provide a working NetHack even if the detection fails, albeit without the ENHANCED_SYMBOLS support included.

**Comment by ostrosablin** [comment]
Yes, after those changes I've managed to successfully build NetHack locally in Docker with working curses and UTF-8 symset. Thanks!

If anyone will find that useful - I'm maintaining a customizable Docker image that builds latest git NetHack (that works both on ARM and x86-64) based on Debian, so it's Dockerfile is essentially a step-by-step instruction how to build latest NetHack 3.7 with curses and enhanced1 unicode symset enabled out of box.

[https://github.com/tmp6154/nethack-docker-ub/blob/master/Dockerfile](https://github.com/tmp6154/nethack-docker-ub/blob/master/Dockerfile)
