### ISSUE TITLE
Grid bugs can block kicks

### ISSUE THREAD

**Issue by NetSysFire** [NetHack/NetHack#799]
```
You kick the grid bug.  The grid bug blocks your kick.  The grid bug bites!
```

Caused by:
https://github.com/NetHack/NetHack/blob/be76727265e7df1be9fcb979bc1afb55c1e694df/src/dokick.c#L258-L259

Grid bugs:
1. Can not wield a weapon
2. Are too small to kick
3. Can not open doors

Yet can block kicks with their "hands"?

Expected behavior:
Grid bugs can not block kicks.

**Comment by k21971** [comment]
This isn't really a bug or issue. However, one could do something like this: https://termbin.com/wio7 - just changes the feedback given based on the monsters size.

**Comment by entrez** [comment]
@k21971 I'd think the weird thing is that grid bugs have hands (and therefore are eligible for this block), less so than the specific feedback.  Unless they do have some kind of hand-equivalent, like a feeler or grabber, and that's the reason they are marked that way?

I mentioned this in an email when it was being discussed on IRC a week ago or so, but I got a little carried away talking about other stuff so it may have been lost in the noise.

**Comment by copperwater** [comment]
Tron grid bugs have four legs, but clearly no hands:

![tron grid bugs](https://i.pinimg.com/736x/09/b0/a4/09b0a43051a662a3c8d033a5c237b8e5--bugs.jpg)

Seems like the most straightforward solution is to make them M1_NOHANDS.
