### ISSUE TITLE
statushilites: support for held (AT_HUGS) equivalent?

### ISSUE THREAD

**Issue by koitsu** [NetHack/NetHack#80]
Not sure if this is a bug, general oversight, "by design", or feature request.

While attempting to migrate my nethackrc from 3.4.3 to 3.6.1 on nethack.alt.org, and following the documentation at https://nethackwiki.com/wiki/Status_hilites#NetHack_3.6.1, I found that there was one or more conditions from the old statuscolors patch that I couldn't find an equivalent for:

STATUSCOLOR=held:red&inverse

I believe this refers to AT_HUGS, such as when an {owlbear,python,coatl,rope golem,etc.} has you in a "grabs you" scenario.  It looks like statushilites only iterates through BL_MASK_xxx bits.  I haven't gone back to look at "where" statuscolors integrated this code-wise, but I wanted to file an issue about it if it hasn't been implemented, else someone can tell me how to accomplish the equivalent.  :-)

Thank you!

**Comment by nhmall** [comment]
4f2375ffe509713fd47162af74e8a6e2a4431904
