### ISSUE TITLE
fruit names get mangled (men at EOL --> man)

### ISSUE THREAD

**Issue by koitsu** [NetHack/NetHack#81]
I've noticed that in some situations, a custom-select fruit name gets automatically changed by Nethack itself.  I apologise for the strange/odd examples, but this is indeed how I determined it.  For years I've used:

OPTIONS=fruit:boiled bear hymen

And noticed that in the Nethack menu (O), this was getting turned into "boiled bear hyman".

Manually hitting O and entering into the fruit name: hyman hymen hymin hymon hymun as a "vowel test" resulted in no mangling of the words, and the message: Fruit is now "hyman hymen hymin hymon hymun".

However, changing the fruit to "mentest snakemen" resulted in: Fruit is now "mentest snakeman".  So it seems Nethack is doing the Perl regex replacement equivalent of s/men$/man/

I don't understand why this would be happening for fruit names, but my guess is there's probably some plurality or "grammar correction" code being used for fruit names that probably shouldn't be.

I confirmed this on Nethack 3.6.0 and Nethack 3.6.1 on nethack.alt.org.  3.4.3 doesn't have this problem.

**Comment by koitsu** [comment]
Looks like this might be fixed/addressed in 467e3bfdab890b8a965fffea740c7475f993733f.

**Comment by ostrosablin** [comment]
Yes, it's fixed, I've checked it on latest build. Now pluralization/singularization works properly.
