### ISSUE TITLE
Problem with stairs

### ISSUE THREAD

**Issue by Meklon2007** [NetHack/NetHack#812]
Hello, I think there is a bug in the current version on github, maybe it will be possible to repeat on another machine, I have this situation reproduced often.

1. create character
2. goto dungeon level 2
3. go down the stairs on level 2
4. immediately go up the stairs (from lev 3 to lev 2 back)
5. get description  - There is a staircase down to level 3 here
6. save and exit
7. restore character
8. get description  - There is a staircase down to level 3 here
9. close window without save game
10. Restore character, press Y
11. get description  - There is a staircase down to level 1 here (must be 3)
12. if go down the stairs character go to 1 level (must be 3)
13. if it did not happen, then do the same for the lower level stairs or create a new character.

in version 3.6.6 - there seems to be no such error.
Examples:
![describe1](https://user-images.githubusercontent.com/12417354/176924146-077cf000-39c6-41d3-a5fa-798d866dd7fb.png)
![describe2](https://user-images.githubusercontent.com/12417354/176924170-3a969f08-ac40-4ef8-ab45-e8958fd2954c.png)

**Comment by entrez** [comment]
This is such a great bug.  In addition to the downstairs going to level 1, the upstairs (supposedly) go to level -1.

<img width="790" alt="upstairs_-1" src="https://user-images.githubusercontent.com/40038830/176936783-1465dd11-7790-4c8d-aedc-c62f4f1c3200.png">

**Comment by Meklon2007** [comment]
Sometimes level was -2, and if i go down game was ended through escape from dungeons.

**Comment by entrez** [comment]
If you get a chance to try #813 let me know if it fixes it for you or whether it's still happening.

**Comment by Meklon2007** [comment]
I corrected the save.c file, compiled NH - the error remained (from the second time the level became 1 again).

**Comment by entrez** [comment]
You're right, it is not working.  I thought it was working earlier, I must have screwed something up when testing it.

**Comment by entrez** [comment]
Oh, okay, I'm an idiot, I was misreading the thing.  No idea why it seemed to "work" at first.

**Comment by Meklon2007** [comment]
another addition: if you continue to perform steps 6-11, the value of the level will decrease, first it becomes 1, then it became -1, then it became -3. If you go down, the game will be completed by escaping:
![describe3](https://user-images.githubusercontent.com/12417354/176964780-90b74b50-b576-4620-8334-df435617b2ba.png)

**Comment by entrez** [comment]
@Meklon2007 Can you check whether it still happens after you apply this patch, when you have a chance?  I think I may understand what's happening, but I don't trust my own ability to test this any more...

```diff
diff --git a/src/restore.c b/src/restore.c
index 2a89b8ca1..04c7d4740 100644
--- a/src/restore.c
+++ b/src/restore.c
@@ -749,7 +749,7 @@ dorecover(NHFILE* nhfp)
     int rtmp;
 
     /* suppress map display if some part of the code tries to update that */
-    g.program_state.restoring = 1;
+    g.program_state.restoring = 2;
 
     get_plname_from_file(nhfp, g.plname);
     getlev(nhfp, 0, (xchar) 0);
@@ -776,6 +776,8 @@ dorecover(NHFILE* nhfp)
     if (rtmp < 2)
         return rtmp; /* dorecover called recursively */
 
+    g.program_state.restoring = 1;
+
     /* these pointers won't be valid while we're processing the
      * other levels, but they'll be reset again by restlevelstate()
      * afterwards, and in the meantime at least u.usteed may mislead
@@ -909,7 +911,7 @@ rest_stairs(NHFILE* nhfp)
         if (nhfp->structlevel) {
             mread(nhfp->fd, (genericptr_t) &stway, sizeof (stairway));
         }
-        if (stway.tolev.dnum == u.uz.dnum) {
+        if (g.program_state.restoring != 2 && stway.tolev.dnum == u.uz.dnum) {
             /* stairway dlevel is relative, make it absolute */
             stway.tolev.dlevel += u.uz.dlevel;
         }
diff --git a/src/save.c b/src/save.c
index 690c5f2f3..95ec07457 100644
--- a/src/save.c
+++ b/src/save.c
@@ -717,7 +717,9 @@ save_stairs(NHFILE* nhfp)
 
     while (stway) {
         if (perform_bwrite(nhfp)) {
-            if (stway->tolev.dnum == u.uz.dnum) {
+            boolean use_relative = (stway->tolev.dnum == u.uz.dnum
+                                    && g.program_state.restoring != 2);
+            if (use_relative) {
                 /* make dlevel relative to current level */
                 stway->tolev.dlevel -= u.uz.dlevel;
             }
@@ -725,7 +727,7 @@ save_stairs(NHFILE* nhfp)
                 bwrite(nhfp->fd, (genericptr_t) &buflen, sizeof buflen);
                 bwrite(nhfp->fd, (genericptr_t) stway, sizeof *stway);
             }
-            if (stway->tolev.dnum == u.uz.dnum) {
+            if (use_relative) {
                 /* reset staiway dlevel back to absolute */
                 stway->tolev.dlevel += u.uz.dlevel;
             }
 ```

**Comment by Meklon2007** [comment]
yes, after the changes made, everything works well, I checked on 3 heroes on four levels of the dungeon, there is no more error.
