### ISSUE TITLE
Do not stop opening tins when your hunger level changes

### ISSUE THREAD

**Issue by NetSysFire** [NetHack/NetHack#834]
Steps to reproduce:

1. Be hungry and close to being weak.
2. Open a tin that is not blessed.
3. "You feel weak. You stop opening the tin."
4. Be doomed to starve.

If the tin was your only source of food in your inventory, it is now impossible to open because the progress of opening the tin is not saved and you will faint from lack of food when you try to open it.

Expected behavior:

"You feel hungry/weak" is ignored when opening tins.

**Comment by pat-rankin** [comment]
"You feel hungry/weak" is already ignored when opening tins.  Even back in 3.4.3 it didn't interrupt the 'opentin' occupation when hunger was changed to either of those states.

If hunger status changes to fainting while eating (not sure whether that could happen) or while opening a tin, you stop doing what you were doing.  But not for becoming hungry or becoming weak.

| For what do you wish? uncursed tin
| h - a tin.
| What do you want to eat? [gh or ?*] h
| It is not so easy to open this tin.  You are beginning to feel weak.
| You succeed in opening the tin.  It smells like jackals.
| Eat it? [yn] (n) y
| You consume smoked jackal.  You only feel hungry now.

Even when fainting you have a chance to open and eat a tin if you first wield a dagger or knife (or tin opener if you manage to find one).  You will have to start over if you get interrupted by going from weak to fainting.
