### ISSUE TITLE
BSD compat code in hacklib.c is no longer necessary

### ISSUE THREAD

**Issue by copperwater** [NetHack/NetHack#838]
(copy pasted from https://github.com/copperwater/xNetHack/issues/83, found by @clausecker)

The file hacklib.c currently has a lot of code guarded with defined(BSD) that makes various functions use long for time stamps instead of time_t. However, this hasn't been the case for decades. Please fix the code by discarding the BSD special code path.

This was first noticed in by a compiler warning:

    hacklib.c:1146:24: warning: incompatible pointer types passing 'long *' to parameter of type 'const time_t *' (aka 'const long long *') [-Wincompatible-pointer-types]
            lt = localtime((long *) (&date));
                           ^~~~~~~~~~~~~~~~
    ../include/system.h:541:38: note: passing argument to parameter here
    E struct tm *localtime(const time_t *);
                                         ^

There are probably more issues coming from this.

**Comment by pat-rankin** [comment]
Better late than never, I hope...

The alternate definition of localtime()'s argument is only used for BSD when POSIX_TYPES is not defined.  NetHack's unixconf.h always defines POSIX_TYPES.  Did you delete that, or comment it out, or is this an xnethack issue?

**Comment by entrez** [comment]
In `yyyymmddhhmmss` it casts the argument to `long *` if `defined(BSD)` instead of using `LOCALTIME_type`; I think that's the source of the warning.
