### ISSUE TITLE
when blind, "Your oil lamp has gone out."

### ISSUE THREAD

**Issue by GorillaSapiens** [NetHack/NetHack#842]
If you're blind, i don't think you should get messages about light sources going out.

**Comment by entrez** [comment]
Maybe you can feel the heat of the flame in your hands disappear... ;)

**Comment by copperwater** [comment]
This also applies to "Your lamp is getting dim" and "Your lantern is getting dim" and "Your lantern has run out of power". In particular, lanterns are electric; none of these would give any tactile feedback.
