### ISSUE TITLE
Function cmdq_push_key not found

### ISSUE THREAD

**Issue by Meklon2007** [NetHack/NetHack#844]
Hello, in the current version of nethack, the game is not compiled for windows due to the lack of implementation of the cmdq_push_key function (it used in allmain.c)
![cmdq_push_key](https://user-images.githubusercontent.com/12417354/184135538-458154fe-e42b-4d3a-a7b6-d112b7b327f9.jpg)
.

**Comment by paxed** [comment]
Committed a fix, it will show up in a few hours.
