### ISSUE TITLE
runmode is always teleport regardless of setting

### ISSUE THREAD

**Issue by mark-mcknight-oncorps** [NetHack/NetHack#874]
NetHack version `Unix NetHack Version 3.7.0-62 Work-in-progress - last build Sep 6`

Steps to reproduce:
- Put `OPTIONS=runmode:walk` in your .nethackrc file
- Launc NetHack and fast-travel with `_` command

Expected behavior:
- Map will update after each step

Actual behavior:
- Map is updated after movement had finished (as runmode:teleport)

**Comment by entrez** [comment]
Does the info in #766 help?

**Comment by DanielKinsman** [comment]
Yes setting `timed_delay` makes it behave like the old `runmode:walk`. It does this regardless of the `runmode` setting though, e.g. `walk`, `teleport` and `crawl` all behave the same. Good enough for me though!

For extra info, this is on curses interface for me, have tmux running locally but not on the servers.

**Comment by entrez** [comment]
> Yes setting timed_delay makes it behave like the old runmode:walk. It does this regardless of the runmode setting though, e.g. walk, teleport and crawl all behave the same.

Are you changing `runmode` in the in-game options menu (you may need to use `mO` or `#optionsfull` to get the full menu), or just in your rcfile?  I think it gets included in the savefile, so if you start a game with `runmode:walk`, it will stay that way when you reload that save even if you've changed your rcfile since then.

**Comment by mark-mcknight-oncorps** [comment]
> Are you changing `runmode` in the in-game options menu (you may need to use `mO` or `#optionsfull` to get the full menu), or just in your rcfile? I think it gets included in the savefile, so if you start a game with `runmode:walk`, it will stay that way when you reload that save even if you've changed your rcfile since then.

Yes `OPTIONS=runmode:walk` and `OPTIONS=timed_delay` in the .nethackrc file and starting a new save makes the travel command work as expected. Is this as designed, should I close this ticket?

**Comment by copperwater** [comment]
Many options aren't designed to be reinitialized from the rc file every time a saved game is resumed. If you were only experiencing this behavior where it works like runmode:teleport in this one save file, and it works like runmode:walk when you start a new save with that set in your rc file, then I don't think there's a bug present.
