### ISSUE TITLE
Hyper terminal

### ISSUE THREAD

**Issue by SHADOWELITE7** [NetHack/NetHack#92]
Although this is a new
 [terminal](https://hyper.is/). Could nethack run in it

**Comment by aeberbach** [comment]
What would be required for nethack to run in it - does it not run regular programs and display regular output?

**Comment by SHADOWELITE7** [comment]
yes, Hyper can run regular programs

**Comment by aeberbach** [comment]
How would you want Nethack to run differently in that case?

**Comment by SHADOWELITE7** [comment]
I would like NetHack to run in Hyper Terminal rather than using the normal way which is the command prompt

**Comment by Xaleth** [comment]
So therefore, NetHack doesn't need any change in the code as it can run in a graphical interface that can be executed by the command prompt.
