### ISSUE TITLE
Throwing one item

### ISSUE THREAD

**Issue by Meklon2007** [NetHack/NetHack#933]
Hello, this problem is in the current version NH in github (windows version).

Quite often when throwing items, a message is displayed - "You can only throw one item at a time" . Even though there is only one item.
I don’t know exactly all the moments when this is displayed, but one determined:
1. press 't' to throw
2. press up key (or down, left, right)
3. select a single item

As far as i understand, this happens because when the control buttons are pressed, a value is entered in the count (in select_menu function, in the windows - tty_select_menu) field, which I did not specify as the number of items, , there should be a value of -1.

The same thing will happen if I specify the number of items for one item, and although the item is still one, a message will be displayed:
1. press 't' to throw
2. press for example 5 (but item is single)
3. select a single item

![neth1](https://user-images.githubusercontent.com/12417354/204006458-570f384c-25a3-44f9-bd29-c3f932807adf.png)
![neth2](https://user-images.githubusercontent.com/12417354/204006474-e245c330-d718-4d78-af77-6d51850e7b82.png)

**Comment by pat-rankin** [comment]
NetHack doesn't know anything about arrow keys.  The Windows port is trying to do you a favor by converting left/down/up/right arrows into 4286 or hjkl depending on the setting for number_pad, but that happens for any type of input, not just when supplying a direction.  Both the tty interface and nethack's core only see the converted value, so if you press up arrow it they will see 8 and behave as if that is what you typed.  So don't type arrow keys.

I've checked in a fix for the feedback messages to distinguish between trying to throw more gold than you have and trying to throw more than 1 non-gold and trying to do both (more than you have of non-gold), but it will make the most sense if you avoid supplying hidden counts.

**Comment by Meklon2007** [comment]
Ok, clearly, I think the arrow is pressed due to the fact that when throwing you need to select an object, and then indicate the direction with the arrows. Looks like I often confuse the order and press the direction, and then the subject, so I see this message.
