### ISSUE TITLE
Question about reading scrolls by enemies

### ISSUE THREAD

**Issue by Meklon2007** [NetHack/NetHack#934]
Hello, it seems to me there is a problem when reading scrolls by invisible monsters. 
For example, there was an invisible quantum mechanic next to my hero - I hit him, then it happened that he teleported after reading the teleportation scroll. 
And the game informed me that a quantum mechanic had teleported, although before that the game had informed me about some monster around me that I was hitting (that is, the game revealed the name of the monster). 

I repeated this problem in wizard mode (create scroll, drop it and create invisible monster) and attached a screenshot (current version NH in github):

![mechanic2](https://user-images.githubusercontent.com/12417354/204113079-01ffc2d4-1778-4451-bd3c-15e3de0f26cc.png)

**Comment by jb4415** [comment]
Maybe you can tell it is a quantum mechanic by the way it talks

**Comment by entrez** [comment]
> Maybe you can tell it is a quantum mechanic by the way it talks

That's how I thought of it before, that you can identify the monster by its voice.  But I don't know whether or not that's consistent with other scenarios where you hear a monster speak.
