### ISSUE TITLE
Cursed iron balls welded to your hands can be dropped when descending

### ISSUE THREAD

**Issue by NetSysFire** [NetHack/NetHack#949]
Steps to reproduce:

1. Have a cursed heavy iron ball.
2. Wield it.
3. Descend the stairs (or maybe step on a hole or trapdoor, too?)
4. You fall down the stairs.  You lose your grip on the iron ball. The iron ball drags you downstairs!  Your movements are now unencumbered.

Expected behavior:

It is welded by a curse to your hands, so falling should not make you lose it that easily. On the other hand, iron balls are usually problematic on their own.

Originally found in evilhack but @k21971 said its a vanilla bug, so here I am.

**Comment by Kufat** [comment]
Is this a bug, though? It seems comparable to having a nymph steal a worn/wielded item, having a foocubus remove it for you, or getting a shopkeeper to grab a loadstone out of your inventory. The fact that it doesn't require the assistance of another monster makes it easier than the above, but it's also a rarer situation and one where the fix deals damage to the player.

**Comment by k21971** [comment]
> Originally found in evilhack but @k21971 said its a vanilla bug, so here I am.

Meaning you can reproduce this in the latest build of 3.7.

> Is this a bug, though?

Yes, it's a bug. If you're wielding a cursed weapon, you don't drop it if you fall down the stairs. Cursed [insert object here] shouldn't be any different. Having a monster stealing it from you is a completely different situation - gravity has no special authority over cursed objects.
