### ISSUE TITLE
Nearness conflicts and "the spellbook spellbook"

### ISSUE THREAD

**Issue by entrez** [NetHack/NetHack#967]
The nearness metrics for `distant_name` and `see_nearby_objects`/`map_object` aren't identical.  `distant_name` considers objects to be close enough to be seen in detail if they're within a radius based on `u.xray_range`:

https://github.com/NetHack/NetHack/blob/7f4e69f88567b43deee0199355bbead575b6a3c5/src/objnam.c#L315-L332

Anything within that radius gets `dknown` set when printing its name (because `gd.distantname` isn't set):

https://github.com/NetHack/NetHack/blob/7f4e69f88567b43deee0199355bbead575b6a3c5/src/objnam.c#L547-L548

`see_nearby_objects` and `map_object`, on the other hand, only count objects that are directly adjacent to the hero as close enough to be seen in detail (and have their generic representations replaced with the real object):

https://github.com/NetHack/NetHack/blob/7f4e69f88567b43deee0199355bbead575b6a3c5/src/objnam.c#L547-L548

https://github.com/NetHack/NetHack/blob/7f4e69f88567b43deee0199355bbead575b6a3c5/src/display.c#L323-L325

This means there's a range within which objects are generic but have `dknown` set to 1 for purposes of printing their names, which is contradictory and causes `xname` to call them things like "the spellbook spellbook" instead of "a spellbook".

**Comment by entrez** [comment]
I tested out a patch locally to use the `distant_name` nearness heuristic everywhere but it feels weird to have objects become visible from such a wide radius away.  On the other hand, it seems like a lot of the former `distant_name` vs `doname` distinctions that 809232914e rolled into `distant_name` are not meant to use immediate adjacency.

Maybe another possible fix would be to just ensure `xname` produces a sane result for a generic object with `dknown` set, and leave the two distinct nearness measures in place.

**Comment by entrez** [comment]
Also, scrolls in shops seem to get named and IDed and price listed (on subsequent examination) within the `distant_name` radius rather than when adjacent.  This is different from previous behavior I think and is related to the main issue (though I don't know why scrolls seem to get their actual names revealed, whereas spellbooks just become "the spellbook spellbook", so maybe it's a slightly different thing somehow).

For example, having just entered a scroll shop in this position:

    ------ 
    |..?.| 
    |....@#
    |..@.| 
    ------ 

Upon first highlighting the scroll in quicklook, it's listed as `a scroll labeled LOREM IPSUM`.  Moving the cursor away and then back onto it, the price is added (`a scroll labeled LOREM IPSUM (for sale, 356 zorkmids)`).  I assume this is because `dknown` gets permanently set partway through the first autodescription.

**Comment by pat-rankin** [comment]
The general weirdness of having the objects change as you get close will probably fade when the new behavior has been in use for a while.

Only potions, gems, and spellbooks get shown as generic (to hide their color, which has traditionally given away too much information).  Other classes of objects don't use generic glyphs so don't change from generic to specific when you get close.

I haven't looked at the shop behavior.

**Comment by entrez** [comment]
> The general weirdness of having the objects change as you get close will probably fade when the new behavior has been in use for a while.

Yes, I didn't mean the color-changing generally but that it felt strange to have dknown being set automatically at 2 (or more) squares away instead of 1.  But I guess that's a similar thing in that it's not really weird in and of itself, just different.

Makes sense that generic types are only used for items where the glyphs can be a "tell".
