### ISSUE TITLE
place_object: off map error with shops

### ISSUE THREAD

**Issue by k21971** [NetHack/NetHack#969]
Scenario: player dies while standing in the space where a hole was dug into the wall of a shop. As their objects are placed in that space, the 'program in disorder' occurs. Version of 3.7 - editlevel 71. Report from the player:

> <desertgreg> Hi K2, I got a bunch of messages while playing nethack on hardfought.org. "place_object: "elven boots" [0] off map <0,0>  Program in disorder!  <desertgreg> What happened is I died in minetown while standing in a hole in the wall of a shop. think the errors are occurring while placing all of my items on the ground.

**Comment by entrez** [comment]
I haven't been able to reproduce this yet just by standing in a random shop wall and dying.

Edit: Turns out the missing piece is that it must be a shared wall between two shops.  The shared shop wall strikes again!

**Comment by pat-rankin** [comment]
I haven't been able to reproduce this even when dying in a gap in a wall shared by two shops, but I'm going to check in the blind fix attempt I made before these followups.

**Comment by entrez** [comment]
I think whether it happens depends on the orientation of the shop wall and the position of the shopkeepers in the linked list.  (Because the first shopkeeper given to `inherits` must occupy the second place in `u.ushops`, and vice-versa).

I do have a save file where it happens and can confirm it no longer happens after applying the first commit in that PR (plus the other commits, but they aren't actually necessary to prevent it), so something similar to that should work.

**Comment by entrez** [comment]
A short review of effects with the savefile/scenario I have that triggered this bug:

    ...---+--+--
    ...|..@| <-- Pasawahan
    ...|%%%|....
    ...|%](|.@..
    ...|%%.|....
    ...|-@------
    ...|.(((|...
    ...+.((.|...
    ...|@(((|.<-- Zlaw
    ...------...
    ............


Pre 1d06fa62a906dce4f2495694a87da857599aeae3: "Zlaw looks at your corpse and sighs.", impossibles when placing items
After 1d06fa62a906dce4f2495694a87da857599aeae3: "Zlaw looks at your corpse and sighs.", no impossibles, Zlaw inherits inventory
With #974 (rebased onto 1d06fa62) applied: "Pasawahan gratefully inherits all your possessions.  Zlaw looks at your corpse and sighs.", Pasawahan inherits inventory

Edit: @pat-rankin, I found that if you have a shared wall that does not trigger the bug, using `#wizfliplevel` to flip it around the axis of the wall often gets it working.
