### ISSUE TITLE
New "valid square" highlights can make map less comprehensible

### ISSUE THREAD

**Issue by entrez** [NetHack/NetHack#983]
<img alt="Screen Shot 2023-02-13 at 2 40 01 PM" src="https://user-images.githubusercontent.com/40038830/218558163-edccbfd8-b025-4a69-a851-1276acf60775.png">

One of these polearm target squares has a water troll on it, but it's impossible to tell which it is without putting the cursor over it.  Even when the feature isn't blue itself, it can be difficult to read certain monsters and terrain when they're highlighted with this background color, for various low-contrast color combinations (such as white, though I'm sure that depends on your terminal's color scheme -- for some it may be black, if they use a darker blue).  Is there a way to turn this "position highlighting" behavior off and fall back to the normal '?' based indication of valid positions?  Maybe it could work like autodescription, where there's a key to toggle the highlighting on and off in addition to an option?

**Comment by nhmall** [comment]
Re-opening to continue to address the contrast aspects of this report.

**Comment by nhmall** [comment]
Maybe we can workshop this a bit further...
It doesn't seem like it's easy (or even possible) for NetHack to be able to retrieve the custom colors that someone has set up on their terminal. Is that true?

If so, then maybe the best way to work-around this is by running a shell script/something prior to playing NetHack that can take your colors and spit out a new OPTIONS=bgcontrasts: line containing the background colours that have a suitable _**contrast ratio**_ for your custom colors.
https://medium.muz.li/the-science-of-color-contrast-an-expert-designers-guide-33e84c41d156 
https://www.accessibility-developer-guide.com/knowledge/colours-and-contrast/how-to-calculate/

Place that OPTIONS=bgcontrasts line into your .nethackrc and use it in NetHack (if set) when displaying backgrounds.
Thoughts?

**Comment by paxed** [comment]
I don't think there's a reliable way to ask the terminal for the colors.

Couple solutions come to mind: a) If foreground color is the same as the hilite color, use black foreground, effectively using inverse attribute.
b) Allow the user define two hilite colors, primary and secondary, in their config. The secondary is used when the foreground color is the same as primary. `OPTIONS=hilitecolor:blue/green` (Possibly combined with the option a: `OPTIONS=hilitecolor:blue/inverse`)

**Comment by nhmall** [comment]
> b) Allow the user define two hilite colors, primary and secondary, in their config. The secondary is used when the foreground color is the same as primary. `OPTIONS=hilitecolor:blue/green` (Possibly combined with the option a: `OPTIONS=hilitecolor:blue/inverse`)

If we went that direction, I think I'd prefer to do it in a way that doesn't limit future uses of background highlights to a single color pair. I'd probably tie it to a keyword that reflects the current specific usage for targeting, rather than for all background highlights into the future.

c) (a variation of my earlier suggestion, but leave it up to user entirely, rather than generated) Load a set of preferred predefined background colors for particular foreground colors via a config file option such as framecolor:fg/bg
OPTIONS=framecolor:404040/A8A8A8, framecolor:0000FF/FFFFFF
The usual NetHack color names would be accepted too.

**Comment by entrez** [comment]
Maybe I am just not thinking inventively enough, but I'm not sure if there is a way to do distinct background colors in a normal configurable 16-color terminal where every foreground color may be in use, without making some low-contrast combinations unreadable, or else having a very unwieldy system like needing to manually set tons of possible fg/bg color combinations.  That doesn't sound like a fun time (kind of like the complexity of new `verbose`, except that some people would likely feel forced to do the configuration because otherwise they'll have trouble reading the map).  The script where you type in your terminal colors might also be somewhat tough since many people download colorschemes from the web or select them from a settings GUI, so don't have easy access to their actual RGB values (depends on the terminal emulator, of course).

I think at least it should be possible to disable the bg color highlights (and/or opt to use inverse video instead), unless there is some feature that it is absolutely required for (and imo the benefits would have to be pretty high to justify adding one, unless this problem is solved).

**Comment by nhmall** [comment]
d801736d09face354273590cbb96fb158190927d in pipeline.
