### ISSUE TITLE
Screen is not cleared when travelling up/down stairs on windows when using tiles - 3.7 dev

### ISSUE THREAD

**Issue by mataamad** [NetHack/NetHack#997]
When travelling up and down stairs in the windows version of nethack-3.7 when using tiles the screen is not cleared, causing the previous level to be displayed with the new level overlaid on top.

![image](https://user-images.githubusercontent.com/2156335/225445917-a3834096-5764-4e53-87c7-048ebf654670.png)

It appears that this issue was introduced in 5ac96e9318d066c38d9c418cf53af3cfaecc17e3 on Dec 12 by @nhmall :
```
-    if (bkglyph != NO_GLYPH) {
+    if (bkglyph != NO_GLYPH
+        /* Don't use all black GLYPH_UNEXPLORED tile as a background */
+        && bkglyph != GLYPH_UNEXPLORED) {
```
 (if I revert the change, lighting is messed up again but now the level change is redrawn)
I think that the issue is that the level gets cleared when switching levels by redrawing over the entire screen with GLYPH_UNEXPLORED, and with this change that doesn't happen anymore.

I'm not sure what the best way is to fix the issue without breaking lighting again. Any ideas @nhmall ?

Reproduced on Windows 10, I assume it happens for all versions of windows though.

**Comment by mataamad** [comment]
Maybe unrelated, but there's also a graphical issue where when partially lit (I think? or maybe on first render, not sure...) some tiles are shown as their text character (I've noticed it for gems - * and potions - ! so far)
![image](https://user-images.githubusercontent.com/2156335/225448141-5a5b2e4c-54d6-4a04-9a1b-5c89c8297d3e.png)

Then getting closer it displays the tile correctly:
![image](https://user-images.githubusercontent.com/2156335/225448231-c58e5f93-0d78-41c3-a8f4-b3e85339e42d.png)

**Comment by mataamad** [comment]
I tried checking for `&& (glyph != NO_GLYPH && bkglyph != GLYPH_UNEXPLORED)` but that didn't seem to help.

Changing it to instead not increment the layer seems to fix the original lighting issue without breaking redraw on going up/down stairs:

![image](https://user-images.githubusercontent.com/2156335/225451177-ad969dcb-32f3-4108-ab9a-0c0f8e016872.png)

It doesn't fix the issue with items being sometimes drawn as text though. Guessing that's unrelated. I can open another issue for it if you'd like?

![image](https://user-images.githubusercontent.com/2156335/225451358-5f11e78b-a4d4-40b2-8406-8eca57c18125.png).

**Comment by paxed** [comment]
> 
> It doesn't fix the issue with items being sometimes drawn as text though. Guessing that's unrelated. I can open another issue for it if you'd like?
> 

Indeed it is unrelated; see commit 85c908cb038bc - especially the note about the tiles at the end there.
